Repository open-telemetry/opentelemetry-js, pull requests merged in 2019-11, with the labels that each got.

#472 fix(core): add missing semver dependency
  packages/opentelemetry-core/package.json
Labels: bug

#437 feat(metrics): add registerMetric and getMetrics
  packages/opentelemetry-metrics/src/Handle.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/index.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-types/src/metrics/Metric.ts
Labels: feature-request

#466 chore: fixing coverage for karma using istanbul
  karma.base.js
  karma.webpack.js
  packages/opentelemetry-core/karma.conf.js
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/test/index-webpack.ts
  packages/opentelemetry-plugin-document-load/karma.conf.js
  packages/opentelemetry-plugin-document-load/package.json
  packages/opentelemetry-plugin-document-load/test/index-webpack.ts
  packages/opentelemetry-plugin-document-load/webpack/test.config.js
  packages/opentelemetry-tracing/karma.conf.js
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-tracing/test/index-webpack.ts
  packages/opentelemetry-tracing/webpack/test.config.js
  packages/opentelemetry-web/karma.conf.js
  packages/opentelemetry-web/package.json
  packages/opentelemetry-web/test/index-webpack.ts
  packages/opentelemetry-web/webpack/test.config.js
Labels: enhancement

#469 chore: fixing problem with load event and performance for loadend
  packages/opentelemetry-plugin-document-load/src/documentLoad.ts
  packages/opentelemetry-plugin-document-load/test/documentLoad.test.ts
Labels: enhancement

#475 add shutdown method on MetricExporter interface
  packages/opentelemetry-metrics/src/export/types.ts
Labels: enhancement

#470 chore: remove examples from lerna packages
  lerna.json
Labels: enhancement

#473 chore(plugin): postgres-pool plugin skeleton
  lerna.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/.npmignore
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/LICENSE
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/README.md
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/pg-pool.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/pg-pool.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/tsconfig.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/tslint.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/.npmignore
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/LICENSE
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/README.md
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/enums.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/index.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/pg.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/types.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/utils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/assertionUtils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/pg.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/testUtils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/tsconfig.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/tslint.json
  packages/opentelemetry-plugin-postgres/tslint.json
Labels: document

#484 chore: update README for new milestones
  README.md
Labels: document

#487 fix(grpc): use correct supportedVersions
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-grpc/src/grpc.ts
Labels: bug

#497 chore: bump typescript version to ^3.7.2
  .gitignore
  package.json
  packages/opentelemetry-base/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-dns/test/integrations/dnspromise-lookup.test.ts
  packages/opentelemetry-plugin-document-load/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-http2/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-scope-async-hooks/package.json
  packages/opentelemetry-scope-base/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-types/package.json
  packages/opentelemetry-web/package.json
Labels: enhancement

#477 feat(traceparent): setting parent span from server
  examples/tracer-web/index.html
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-plugin-document-load/README.md
  packages/opentelemetry-plugin-document-load/src/documentLoad.ts
  packages/opentelemetry-plugin-document-load/test/documentLoad.test.ts
Labels: feature-request

#512 chore: minor name change
  packages/opentelemetry-types/README.md
  packages/opentelemetry-types/tsconfig.json
Labels: document

#500 feat: add ConsoleMetricExporter
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts
  packages/opentelemetry-metrics/src/index.ts
  packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
Labels: feature-request

#483 feat: Add prometheus exporter
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-prometheus/src/export/types.ts
  packages/opentelemetry-exporter-prometheus/src/index.ts
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-exporter-prometheus/tslint.json
Labels: feature-request

#507 feat: direct calling of metric instruments
  packages/opentelemetry-core/src/metrics/NoopMeter.ts
  packages/opentelemetry-metrics/src/LabelSet.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-types/src/metrics/Metric.ts
Labels: enhancement

#514 ci: enumerate caching paths manually
  .circleci/config.yml
Labels: enhancement

#510 chore(circleci): remove duplicate compile step
  .circleci/config.yml
Labels: enhancement

#521 chore: update prometheus exporter readme with usage and links
  packages/opentelemetry-exporter-prometheus/README.md
Labels: document

#205 feat: add mongodb plugin
  .circleci/config.yml
  packages/opentelemetry-plugin-mongodb-core/.npmignore
  packages/opentelemetry-plugin-mongodb-core/LICENSE
  packages/opentelemetry-plugin-mongodb-core/README.md
  packages/opentelemetry-plugin-mongodb-core/package.json
  packages/opentelemetry-plugin-mongodb-core/src/index.ts
  packages/opentelemetry-plugin-mongodb-core/src/mongodb.ts
  packages/opentelemetry-plugin-mongodb-core/src/types.ts
  packages/opentelemetry-plugin-mongodb-core/test/mongodb.test.ts
  packages/opentelemetry-plugin-mongodb-core/tsconfig.json
  packages/opentelemetry-plugin-mongodb-core/tslint.json
Labels: feature-request, plugin-request

#548 fix(plugin-http): adapt to current @types/node
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-http/test/utils/assertSpan.ts
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-https/test/utils/assertSpan.ts
Labels: enhancement

#526 fix: zipkin-exporter: don't export after shutdown
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts
Labels: bug

#537 examples(tracing): add multi exporter example
  examples/basic-tracer-node/README.md
  examples/basic-tracer-node/multi_exporter.js
  examples/basic-tracer-node/package.json
Labels: document

#551 chore: fix minor typo
  packages/opentelemetry-plugin-redis/README.md
Labels: document

#546 chore: fixing issue when metric time is 0 in document-load plugin
  packages/opentelemetry-plugin-document-load/src/documentLoad.ts
  packages/opentelemetry-plugin-document-load/test/documentLoad.test.ts
Labels: enhancement

#562 chore(web-example): Added a README for the existing example
  examples/tracer-web/README.md
  examples/tracer-web/images/traces.png
Labels: document

#534 feat: add redis plugin example
  examples/redis/README.md
  examples/redis/client.js
  examples/redis/express-tracer-handlers.js
  examples/redis/images/jaeger.jpg
  examples/redis/images/zipkin.jpg
  examples/redis/package.json
  examples/redis/server.js
  examples/redis/setup-redis.js
  examples/redis/setup.js
Labels: document

#490 chore: update metrics README
  packages/opentelemetry-metrics/README.md
Labels: document

#525 feat: mysql support
  .circleci/config.yml
  README.md
  examples/mysql/README.md
  examples/mysql/client.js
  examples/mysql/images/jaeger-ui.png
  examples/mysql/images/zipkin-ui.png
  examples/mysql/package.json
  examples/mysql/server.js
  examples/mysql/setup.js
  packages/opentelemetry-node/src/config.ts
  packages/opentelemetry-plugin-mysql/.npmignore
  packages/opentelemetry-plugin-mysql/LICENSE
  packages/opentelemetry-plugin-mysql/README.md
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-mysql/src/enums.ts
  packages/opentelemetry-plugin-mysql/src/index.ts
  packages/opentelemetry-plugin-mysql/src/mysql.ts
  packages/opentelemetry-plugin-mysql/src/types.ts
  packages/opentelemetry-plugin-mysql/src/utils.ts
  packages/opentelemetry-plugin-mysql/test/mysql.test.ts
  packages/opentelemetry-plugin-mysql/test/testUtils.ts
  packages/opentelemetry-plugin-mysql/tsconfig.json
  packages/opentelemetry-plugin-mysql/tslint.json
Labels: Merge:LGTM, Target:NodeJS, feature-request

#569 chore: allow parent span to be null
  packages/opentelemetry-core/src/trace/TracerDelegate.ts
  packages/opentelemetry-node/test/NodeTracer.test.ts
  packages/opentelemetry-plugin-dns/src/dns.ts
  packages/opentelemetry-plugin-document-load/src/documentLoad.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/utils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/pg.test.ts
  packages/opentelemetry-plugin-redis/src/utils.ts
  packages/opentelemetry-tracing/src/BasicTracer.ts
  packages/opentelemetry-tracing/test/BasicTracer.test.ts
  packages/opentelemetry-types/src/trace/SpanOptions.ts
  packages/opentelemetry-types/src/trace/tracer.ts
Labels: Merge:LGTM, enhancement

#564 docs: add usage for mongodb-core plugin #543
  packages/opentelemetry-plugin-mongodb-core/README.md
Labels: Merge:LGTM, document

#577 fix: add missing `main` in package.json
  packages/opentelemetry-shim-opentracing/package.json
Labels: bug
