Repository open-telemetry/opentelemetry-js, pull requests merged in 2019-12, with the labels that each got.

#561 fix: prometheus counters can only count up
  examples/prometheus/index.js
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: Merge:LGTM

#580 fix(plugin-http): http.url attribute
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/utils/assertSpan.ts
Labels: Merge:LGTM, bug

#575 Add exporter guide
  doc/exporter-guide.md
Labels: Merge:LGTM, document

#576 Allow label sets to be created from meter or Meter
  packages/opentelemetry-metrics/src/Meter.ts
Labels: Merge:LGTM

#574 chore: add CHANGELOG.md
  CHANGELOG.md
Labels: Discussion, document

#589 fix(plugin-http): correct handling of WHATWG urls
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/utils/httpRequest.ts
Labels: Merge:LGTM, bug

#597 chore(plugin-https): sync https tests with http
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts
  packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-plugin-https/README.md
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-https/src/https.ts
  packages/opentelemetry-plugin-https/test/functionals/https-disable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-package.test.ts
  packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/utils/assertSpan.ts
  packages/opentelemetry-plugin-https/test/utils/httpsRequest.ts
Labels: Merge:LGTM, enhancement

#613 fix(plugin-dns): remove from default plugin list
  packages/opentelemetry-node/src/config.ts
  packages/opentelemetry-plugin-dns/README.md
Labels: Agreed, Merge:LGTM, bug

#609 Jaeger no flush interval
  examples/basic-tracer-node/multi_exporter.js
  examples/dns/setup.js
  examples/grpc/setup.js
  examples/grpc_dynamic_codegen/setup.js
  examples/http/setup.js
  examples/https/setup.js
  examples/mysql/setup.js
  examples/redis/setup.js
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/src/types.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
Labels: bug

#593 fix: transpile to es2017 as esnext may result in unsupported JS code
  packages/tsconfig.base.json
Labels: Merge:LGTM

#581 feat: add OpenTracing example
  examples/opentracing-shim/README.md
  examples/opentracing-shim/client.js
  examples/opentracing-shim/images/jaeger-ui.png
  examples/opentracing-shim/images/zipkin-ui.png
  examples/opentracing-shim/package.json
  examples/opentracing-shim/server.js
  examples/opentracing-shim/shim.js
  examples/opentracing-shim/utils.js
Labels: Merge:LGTM, document

#633 chore: enable incremental builds
  packages/tsconfig.base.json
Labels: Merge:LGTM, enhancement

#631 fix(grpc): patch original client methods
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-grpc/test/grpc.test.ts
Labels: Merge:LGTM, bug

#629 ci: deploy documentation on releases
  .circleci/config.yml
  package.json
Labels: Merge:LGTM, document

#645 chore(plugin-pg): move dev dependencies out of `dependencies` in package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
Labels: Merge:LGTM, cleanup, enhancement

#501 feat(plugin): pg-pool plugin implementation
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/enums.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/index.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/pg-pool.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/types.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/utils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/assertionUtils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/pg-pool.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/testUtils.ts
Labels: Merge:LGTM, plugin-request

#542 feat: add example for postgres plugin
  examples/postgres/README.md
  examples/postgres/client.js
  examples/postgres/images/jaeger.png
  examples/postgres/images/zipkin.png
  examples/postgres/package.json
  examples/postgres/server.js
  examples/postgres/setup.js
  examples/postgres/setupPsql.js
Labels: Merge:LGTM, document

#644 feat: test-utils
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-mysql/test/mysql.test.ts
  packages/opentelemetry-plugin-mysql/test/testUtils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/assertionUtils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/pg-pool.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/testUtils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/pg.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/testUtils.ts
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-plugin-redis/test/assertionUtils.ts
  packages/opentelemetry-plugin-redis/test/redis.test.ts
  packages/opentelemetry-plugin-redis/test/testUtils.ts
  packages/opentelemetry-test-utils/package.json
  packages/opentelemetry-test-utils/testUtils.ts
  packages/opentelemetry-test-utils/tsconfig.json
  packages/opentelemetry-test-utils/tslint.json
Labels: Merge:LGTM, cleanup

#558 Add ioredis
  packages/opentelemetry-plugin-ioredis/.npmignore
  packages/opentelemetry-plugin-ioredis/LICENSE
  packages/opentelemetry-plugin-ioredis/README.md
  packages/opentelemetry-plugin-ioredis/package.json
  packages/opentelemetry-plugin-ioredis/src/enums.ts
  packages/opentelemetry-plugin-ioredis/src/index.ts
  packages/opentelemetry-plugin-ioredis/src/ioredis.ts
  packages/opentelemetry-plugin-ioredis/src/types.ts
  packages/opentelemetry-plugin-ioredis/src/utils.ts
  packages/opentelemetry-plugin-ioredis/test/ioredis.test.ts
  packages/opentelemetry-plugin-ioredis/tsconfig.json
  packages/opentelemetry-plugin-ioredis/tslint.json
Labels: Merge:LGTM, plugin-request

#539 chore(docs:postgres): add usage instructions
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/README.md
Labels: document

#647 chore: update plugin readme with example links
  packages/opentelemetry-plugin-document-load/README.md
  packages/opentelemetry-plugin-mysql/README.md
  packages/opentelemetry-plugin-redis/README.md
  packages/opentelemetry-plugin-xml-http-request/README.md
  packages/opentelemetry-shim-opentracing/README.md
Labels: document
