Repository open-telemetry/opentelemetry-js, pull requests merged in 2019-10, with the labels that each got.

#445 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: document

#444 fix: batchSpanProcessor test failing intermittently
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: bug

#454 fix(span): rename span recording flag
  packages/opentelemetry-core/src/trace/NoopSpan.ts
  packages/opentelemetry-core/test/trace/NoopSpan.test.ts
  packages/opentelemetry-core/test/trace/NoopTracer.test.ts
  packages/opentelemetry-node/test/NodeTracer.test.ts
  packages/opentelemetry-tracing/src/BasicTracer.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/test/BasicTracer.test.ts
  packages/opentelemetry-tracing/test/Span.test.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
  packages/opentelemetry-types/src/trace/SpanOptions.ts
  packages/opentelemetry-types/src/trace/span.ts
Labels: enhancement

#449 fix: allow recording links only at Span creation time
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/src/BasicTracer.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/test/Span.test.ts
  packages/opentelemetry-types/src/trace/SpanOptions.ts
  packages/opentelemetry-types/src/trace/span.ts
Labels: enhancement

#451 feat: add IsRemote field to SpanContext, set by propagators
  packages/opentelemetry-core/src/context/propagation/B3Format.ts
  packages/opentelemetry-core/src/context/propagation/BinaryTraceContext.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/test/context/B3Format.test.ts
  packages/opentelemetry-core/test/context/BinaryTraceContext.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-types/src/trace/span_context.ts
Labels: feature-request

#460 chore: move members list out of community repo
  .github/CODEOWNERS
  README.md
Labels: document

#459 chore: update API docs
  packages/opentelemetry-types/src/distributed_context/EntryValue.ts
  packages/opentelemetry-types/src/metrics/Handle.ts
  packages/opentelemetry-types/src/trace/SpanOptions.ts
  packages/opentelemetry-types/src/trace/link.ts
  packages/opentelemetry-types/src/trace/span_context.ts
  packages/opentelemetry-types/src/trace/tracer.ts
Labels: document

#462 chore: update README
  README.md
Labels: document

#417 feature(plugin): implement postgres plugin
  .circleci/config.yml
  packages/opentelemetry-plugin-postgres/README.md
  packages/opentelemetry-plugin-postgres/package.json
  packages/opentelemetry-plugin-postgres/src/enums.ts
  packages/opentelemetry-plugin-postgres/src/index.ts
  packages/opentelemetry-plugin-postgres/src/pg.ts
  packages/opentelemetry-plugin-postgres/src/types.ts
  packages/opentelemetry-plugin-postgres/src/utils.ts
  packages/opentelemetry-plugin-postgres/test/assertionUtils.ts
  packages/opentelemetry-plugin-postgres/test/pg.test.ts
  packages/opentelemetry-plugin-postgres/test/testUtils.ts
Labels: feature-request

#468 feat: validate metric names
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: feature-request
