Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-07, with the labels that each got.

#1262 feat(opentelemetry-web): capture encodedBodySize / http.response_content_length
  packages/opentelemetry-plugin-fetch/src/enums/AttributeNames.ts
  packages/opentelemetry-plugin-fetch/test/fetch.test.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-semantic-conventions/src/trace/http.ts
  packages/opentelemetry-web/package.json
  packages/opentelemetry-web/src/enums/PerformanceTimingNames.ts
  packages/opentelemetry-web/src/types.ts
  packages/opentelemetry-web/src/utils.ts
  packages/opentelemetry-web/test/utils.test.ts
Labels: enhancement

#1276 chore: updating aggregator MinMaxLastSumCount and use it for value observer and value recorder
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/src/export/aggregators/MinMaxLastSumCount.ts
  packages/opentelemetry-metrics/src/export/aggregators/MinMaxSumCount.ts
  packages/opentelemetry-metrics/src/export/aggregators/index.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: Merge:LGTM, enhancement, required-by-spec, size/L

#1277 refactor: remove unnecessary new Promise operation
  packages/opentelemetry-metrics/src/Meter.ts
Labels: size/S

#1274 fix: do not crash on fetch(new Request(url))
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-plugin-fetch/test/fetch.test.ts
Labels: bug

#1296 feat: force flush and shutdown callback for span exporters
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
Labels: Merge:LGTM, enhancement

#1289 fix(grpc): camelCase methods can be double patched
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-grpc/test/fixtures/grpc-test.proto
  packages/opentelemetry-plugin-grpc/test/grpc.test.ts
Labels: bug

#1328 chore: changing all env params to be required
  packages/opentelemetry-core/src/platform/browser/environment.ts
  packages/opentelemetry-core/src/platform/node/environment.ts
  packages/opentelemetry-core/src/utils/environment.ts
Labels: size/XS

#1302 feat: adding proto over http for collector exporter
  examples/collector-exporter-node/docker/collector-config.yaml
  examples/collector-exporter-node/docker/docker-compose.yaml
  examples/collector-exporter-node/package.json
  examples/collector-exporter-node/start.js
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-collector/src/enums.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/README.md
  packages/opentelemetry-exporter-collector/src/platform/node/util.ts
  packages/opentelemetry-exporter-collector/src/platform/node/utilWithGrpc.ts
  packages/opentelemetry-exporter-collector/src/platform/node/utilWithJson.ts
  packages/opentelemetry-exporter-collector/src/platform/node/utilWithJsonProto.ts
  packages/opentelemetry-exporter-collector/src/types.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorExporterWithProto.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
Labels: enhancement, size/XL

#1343 feat(grpc-js): enable autoinstrumentation by default
  metapackages/plugins-node-core/README.md
  metapackages/plugins-node-core/package.json
  packages/opentelemetry-node/README.md
  packages/opentelemetry-node/src/config.ts
Labels: enhancement

#1069 feat: add OTEL_SAMPLING_PROBABILITY env var
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-tracing/src/utility.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: enhancement

#918 feat: add baggage support to the opentracing shim
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: enhancement

#974 feat: add OTEL_LOG_LEVEL env var
  packages/opentelemetry-core/src/common/ConsoleLogger.ts
  packages/opentelemetry-core/src/common/types.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/common/ConsoleLogger.test.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-tracing/src/config.ts
Labels: Merge:LGTM, enhancement

#1358 fix: add missing grpc-js index
  packages/opentelemetry-plugin-grpc-js/src/index.ts
Labels: bug

#1331 Feat: Make ID generator configurable
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/platform/browser/RandomIdGenerator.ts
  packages/opentelemetry-core/src/platform/browser/id.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/node/RandomIdGenerator.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-core/src/trace/IdGenerator.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-core/test/platform/RandomIdGenerator.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/types.ts
Labels: enhancement

#1364 fix: require grpc-js instead of grpc in grpc-js example
  examples/grpc-js/helloworld_grpc_pb.js
  examples/grpc-js/server.js
Labels: Merge:LGTM
