Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-02, with the labels that each got.

#759 chore: fix typos and minor README
  README.md
  examples/postgres/server.js
  packages/opentelemetry-core/README.md
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-scope-async-hooks/README.md
Labels: document, size/S

#763 chore: use os specific line endings for version updates
  scripts/version-update.js
Labels: enhancement, size/XS

#747 chore: fix build errors
  .circleci/config.yml
  CONTRIBUTING.md
  doc/development-guide.md
  lerna.json
  package.json
  packages/opentelemetry-api/package.json
  packages/opentelemetry-base/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-stackdriver-trace/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-ioredis/package.json
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-scope-async-hooks/package.json
  packages/opentelemetry-scope-base/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
Labels: Merge:LGTM, bug

#760 fix: upgraded commitlint to fix warnings
  package.json
Labels: Merge:LGTM

#563 skeleton(metrics): createMeasure
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-metrics/src/BoundInstrument.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: Merge:LGTM

#750 update examples and getting started for provider and api package
  benchmark/tracer.js
  examples/basic-tracer-node/index.js
  examples/basic-tracer-node/multi_exporter.js
  examples/basic-tracer-node/package.json
  examples/dns/package.json
  examples/dns/tracer.js
  examples/grpc/package.json
  examples/grpc/tracer.js
  examples/grpc_dynamic_codegen/capitalize_server.js
  examples/grpc_dynamic_codegen/package.json
  examples/grpc_dynamic_codegen/tracer.js
  examples/http/package.json
  examples/http/tracer.js
  examples/https/package.json
  examples/https/tracer.js
  examples/ioredis/package.json
  examples/ioredis/tracer.js
  examples/mysql/package.json
  examples/mysql/tracer.js
  examples/opentracing-shim/shim.js
  examples/postgres/package.json
  examples/postgres/server.js
  examples/postgres/tracer.js
  examples/prometheus/index.js
  examples/redis/client.js
  examples/redis/express-tracer-handlers.js
  examples/redis/package.json
  examples/redis/tracer.js
  examples/stackdriver-trace/index.js
  examples/stackdriver-trace/package.json
  examples/tracer-web/examples/document-load/index.js
  examples/tracer-web/package.json
  getting-started/README.md
  getting-started/monitored-example/monitoring.js
  getting-started/traced-example/tracing.js
  getting-started/ts-example/README.md
  getting-started/ts-example/monitoring.ts
  getting-started/ts-example/package.json
  getting-started/ts-example/tracing.ts
  packages/opentelemetry-node/README.md
Labels: Merge:LGTM, document

#767 chore: adding information to main readme about user interaction plugin
  README.md
Labels: enhancement, size/XS

#765 chore: upgrade lerna-changelog to ^1.0.0
  package.json
Labels: Merge:LGTM, size/XS

#772 chore: add typing to propagator carrier
  packages/opentelemetry-api/src/context/propagation/HttpTextFormat.ts
  packages/opentelemetry-api/src/context/propagation/NoopHttpTextFormat.ts
  packages/opentelemetry-api/src/context/propagation/carrier.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-core/src/context/propagation/B3Format.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTraceFormat.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: enhancement, size/M

#775 cleanup: remove unused tsconfig-release.json
  packages/opentelemetry-base/tsconfig-release.json
  packages/opentelemetry-core/tsconfig-release.json
  packages/opentelemetry-exporter-collector/tsconfig-release.json
  packages/opentelemetry-plugin-xml-http-request/tsconfig-release.json
  packages/opentelemetry-propagator-jaeger/tsconfig-release.json
  packages/opentelemetry-web/tsconfig-release.json
Labels: size/M

#654 feat: warn user when a instrumented package was already required #636
  packages/opentelemetry-node/src/instrumentation/PluginLoader.ts
  packages/opentelemetry-node/test/instrumentation/PluginLoader.test.ts
  packages/opentelemetry-node/test/instrumentation/node_modules/already-require-module/index.js
  packages/opentelemetry-node/test/instrumentation/node_modules/already-require-module/package.json
Labels: Merge:LGTM, enhancement, size/M

#778 chore: fix npm img for api package
  packages/opentelemetry-api/README.md
Labels: size/XS

#653 Prevent loading plugins for incorrect module #626
  packages/opentelemetry-api/src/trace/instrumentation/Plugin.ts
  packages/opentelemetry-core/src/trace/instrumentation/BasePlugin.ts
  packages/opentelemetry-node/src/instrumentation/PluginLoader.ts
  packages/opentelemetry-node/test/instrumentation/PluginLoader.test.ts
  packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-http-module/http-module.js
  packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-notsupported-module/simple-module.js
  packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-simple-module/simple-module.js
  packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-supported-module/simple-module.js
  packages/opentelemetry-node/test/instrumentation/node_modules/random-module/index.js
  packages/opentelemetry-node/test/instrumentation/node_modules/random-module/package.json
  packages/opentelemetry-web/test/WebTracer.test.ts
Labels: enhancement, size/M

#743 fix: left pad jaeger trace ids
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
Labels: Merge:LGTM, bug, size/S

#779 Chore: minor fixes to API docs
  doc/plugin-guide.md
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/MeterProvider.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-api/src/trace/tracer_provider.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-web/README.md
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
Labels: Merge:LGTM, document

#738 feat: Metrics SDK - aggregator, batcher, controller
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-metrics/src/BoundInstrument.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/Aggregator.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts
  packages/opentelemetry-metrics/src/export/Controller.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-metrics/test/MeterProvider.test.ts
  packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
  packages/opentelemetry-metrics/test/mocks/Exporter.ts
Labels: Discussion, Merge:LGTM, prototype, size/XL

#769 Separate context propagation (OTEP 66)
  .circleci/config.yml
  packages/opentelemetry-api/package.json
  packages/opentelemetry-api/src/context/propagation/HttpTextFormat.ts
  packages/opentelemetry-api/src/context/propagation/NoopHttpTextFormat.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/src/context/context.ts
  packages/opentelemetry-core/src/context/propagation/B3Format.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/context/B3Format.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-xml-http-request/src/xhr.ts
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTraceFormat.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTraceFormat.test.ts
  packages/opentelemetry-scope-async-hooks/src/AsyncHooksScopeManager.ts
  packages/opentelemetry-scope-async-hooks/test/AsyncHooksScopeManager.test.ts
  packages/opentelemetry-scope-base/src/NoopScopeManager.ts
  packages/opentelemetry-scope-base/src/context.ts
  packages/opentelemetry-scope-base/src/index.ts
  packages/opentelemetry-scope-base/src/types.ts
  packages/opentelemetry-scope-base/test/NoopScopeManager.test.ts
  packages/opentelemetry-scope-zone-peer-dep/src/ZoneScopeManager.ts
  packages/opentelemetry-scope-zone-peer-dep/test/ZoneScopeManager.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerRegistry.test.ts
  packages/opentelemetry-web/src/StackScopeManager.ts
  packages/opentelemetry-web/test/StackScopeManager.test.ts
Labels: Merge:LGTM, enhancement, size/XL

#771 chore: lint api package
  .circleci/config.yml
  packages/opentelemetry-api/package.json
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-meter.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-span.test.ts
  packages/opentelemetry-api/tsconfig.json
Labels: Merge:LGTM, size/M

#685 feat: add express plugin #666
  .circleci/config.yml
  README.md
  packages/opentelemetry-plugin-express/.npmignore
  packages/opentelemetry-plugin-express/LICENSE
  packages/opentelemetry-plugin-express/README.md
  packages/opentelemetry-plugin-express/package.json
  packages/opentelemetry-plugin-express/src/express.ts
  packages/opentelemetry-plugin-express/src/index.ts
  packages/opentelemetry-plugin-express/src/types.ts
  packages/opentelemetry-plugin-express/src/utils.ts
  packages/opentelemetry-plugin-express/src/version.ts
  packages/opentelemetry-plugin-express/test/express.test.ts
  packages/opentelemetry-plugin-express/test/utils.test.ts
  packages/opentelemetry-plugin-express/tsconfig.json
  packages/opentelemetry-plugin-express/tslint.json
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
Labels: enhancement, feature-request, size/XXL

#793 remove getDefaultBound and setCallback from Metric API
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/test/noop-implementations/noop-meter.test.ts
  packages/opentelemetry-metrics/src/Metric.ts
Labels: Merge:LGTM

#792 Add context API
  packages/opentelemetry-api/src/api/context.ts
  packages/opentelemetry-api/src/index.ts
Labels: API, enhancement

#798 Respect sampled bit in probability sampler
  packages/opentelemetry-core/src/trace/sampler/ProbabilitySampler.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: bug

#807 chore: aligning names for npm linting scripts
  .circleci/config.yml
  CONTRIBUTING.md
  doc/development-guide.md
  package.json
  packages/opentelemetry-api/package.json
  packages/opentelemetry-base/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-stackdriver-trace/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-document-load/package.json
  packages/opentelemetry-plugin-express/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-ioredis/package.json
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-plugin-user-interaction/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-scope-async-hooks/package.json
  packages/opentelemetry-scope-base/package.json
  packages/opentelemetry-scope-zone-peer-dep/package.json
  packages/opentelemetry-scope-zone/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-test-utils/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: enhancement, size/M

#805 ci(circleci): add node13 for tests
  .circleci/config.yml
Labels: Merge:LGTM, size/XS

#809 chore(metrics): add @todo tests
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: size/M

#813 fix: prometheus example
  examples/prometheus/index.js
  packages/opentelemetry-exporter-prometheus/README.md
Labels: document, size/XS

#797 Add propagation API
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/index.ts
Labels: API, enhancement

#804 chore: remove binary propagator
  packages/opentelemetry-api/src/context/propagation/BinaryFormat.ts
  packages/opentelemetry-api/src/context/propagation/HttpTextFormat.ts
  packages/opentelemetry-api/src/context/propagation/NoopBinaryFormat.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-api/src/trace/tracer.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-core/src/context/propagation/BinaryTraceContext.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/context/BinaryTraceContext.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/config.ts
  packages/opentelemetry-tracing/src/types.ts
  packages/opentelemetry-tracing/test/BasicTracerRegistry.test.ts
Labels: nonconforming
