Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-05, with the labels that each got.

#1009 fix(opentracing-shim): register tracer provider for complete traces
  examples/opentracing-shim/shim.js
Labels: Merge:express, size/XS

#1008 fix: permission denied error when cloning submodules
  .gitmodules
Labels: Merge:express, size/XS

#1005 fix: add missing error status handler
  packages/opentelemetry-plugin-grpc/src/grpc.ts
Labels: Merge:express, bug, size/XS

#1002 fix(opentelemetry-plugin-xml-http-request): define span kind as CLIENT for xmlhttprequests
  packages/opentelemetry-plugin-xml-http-request/src/xhr.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
Labels: Merge:express, size/XS

#1003 chore: test on node 14
  .circleci/config.yml
  README.md
Labels: document, enhancement

#1014 feat(metrics): use MetricDescriptor to determine aggregator #989
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: size/S

#1021 fix: left pad short b3 trace identifiers
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
Labels: Merge:LGTM, bug, size/S

#1015 fix: prevent duplicated resource creation
  packages/opentelemetry-metrics/src/MeterProvider.ts
  packages/opentelemetry-metrics/test/MeterProvider.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: enhancement, size/M

#1001 fix: observers should not expose bind/unbind method
  packages/opentelemetry-api/src/metrics/BoundInstrument.ts
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-metrics/src/BoundInstrument.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/test/Batcher.test.ts
Labels: Merge:LGTM, breaking, bug

#1024 fix: multi span processor should flush child span processors
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
Labels: enhancement

#948 feat(http-plugin): add options to disable new spans if no parent #931
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
Labels: Merge:LGTM, size/L

#1029 Fix typo in opentelemetry-tracing types.js
  packages/opentelemetry-tracing/src/types.ts
Labels: Merge:express

#1026 Reintroduce node 13 tests
  .circleci/config.yml
  README.md
Labels: Merge:express

#1035 chore: fix build on latest typings
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
Labels: Merge:express, size/XS

#1036 chore: fixing build
  packages/opentelemetry-plugin-grpc/test/grpc.test.ts
Labels: Merge:express, size/XS

#1037 fix(tracing): span processor should receive a readable span as parameters
  packages/opentelemetry-exporter-zipkin/test/transform.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: enhancement

#984 fix(http-plugin): strip otel custom http header #983
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
Labels: bug, size/S

#981 chore: splitting BasePlugin into browser and node
  packages/opentelemetry-core/karma.conf.js
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/platform/BaseAbstractPlugin.ts
  packages/opentelemetry-core/src/platform/browser/BasePlugin.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/node/BasePlugin.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-core/test/index-webpack.ts
  packages/opentelemetry-core/test/platform/BasePlugin.test.ts
  packages/opentelemetry-core/test/platform/browser/BasePlugin.test.ts
Labels: Merge:LGTM, size/L

#1047 chore(deps): update dependency mocha and ts-mocha to v7
  packages/opentelemetry-api/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-base/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: dependencies

#1049 chore: pipe resource through to MetricRecord
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: enhancement, size/S

#963 feat(plugin-http): add plugin hooks before processing req and res
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
Labels: Merge:LGTM, enhancement

#1032 Make Labels Optional for CounterMetric::add
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: API, breaking, bug, size/S

#1053 fix: include proto files in deployment package
  packages/opentelemetry-exporter-collector/package.json
Labels: Merge:express, bug

#1051 chore: deploy docs using github action
  .circleci/config.yml
  .github/workflows/docs.yml
Labels: Merge:express, document

#1056 fix readme: setting labelKeys when creating the counter
  packages/opentelemetry-exporter-prometheus/README.md
Labels: document

#1061 Update dependency karma,karma-coverage-istanbul-reporter and karma mocha
  packages/opentelemetry-api/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: express

#1055 chore(opentelemetry-resources): add instance type and az to aws detector
  packages/opentelemetry-resources/src/platform/node/detectors/AwsEc2Detector.ts
  packages/opentelemetry-resources/test/detect-resources.test.ts
  packages/opentelemetry-resources/test/detectors/AwsEc2Detector.test.ts
Labels: enhancement, express, size/S

#1064 chore: update README
  README.md
Labels: document, express

#1060 fix(http-plugin): don't modify user's headers object in plugin
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
Labels: bug, express

#1065 style: format README
  README.md
Labels: document

#1050 feat: add plugin metapackages
  lerna.json
  metapackages/plugins-node-core/README.md
  metapackages/plugins-node-core/package.json
  metapackages/plugins-web-core/README.md
  metapackages/plugins-web-core/package.json
Labels: enhancement

#1072 chore: mark metapackages as public
  metapackages/plugins-node-core/package.json
  metapackages/plugins-web-core/package.json
Labels: express

#1073 chore: change personal access token to github token
  .github/workflows/docs.yml
Labels: express

#838 feat: implement W3C Correlation Context propagator
  packages/opentelemetry-core/src/correlation-context/correlation-context.ts
  packages/opentelemetry-core/src/correlation-context/propagation/HttpCorrelationContext.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/correlation-context/HttpCorrelationContext.test.ts
Labels: enhancement, size/L

#1080 docs: document CorrelationContext propagator under Built-in Implement…
  packages/opentelemetry-core/README.md
Labels: document

#1063 feat: exporter collector TLS option
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-collector/src/CollectorExporterBase.ts
  packages/opentelemetry-exporter-collector/src/index.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/index.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/sendSpans.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/index.ts
  packages/opentelemetry-exporter-collector/src/platform/node/sendSpans.ts
  packages/opentelemetry-exporter-collector/src/platform/node/types.ts
  packages/opentelemetry-exporter-collector/src/transform.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorExporter.test.ts
  packages/opentelemetry-exporter-collector/test/certs/ca.crt
  packages/opentelemetry-exporter-collector/test/certs/ca.key
  packages/opentelemetry-exporter-collector/test/certs/client.crt
  packages/opentelemetry-exporter-collector/test/certs/client.csr
  packages/opentelemetry-exporter-collector/test/certs/client.key
  packages/opentelemetry-exporter-collector/test/certs/regenerate.sh
  packages/opentelemetry-exporter-collector/test/certs/server.crt
  packages/opentelemetry-exporter-collector/test/certs/server.csr
  packages/opentelemetry-exporter-collector/test/certs/server.key
  packages/opentelemetry-exporter-collector/test/common/CollectorExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorExporter.test.ts
Labels: Merge:LGTM, enhancement

#1057 chore: add examples README.md
  examples/README.md
Labels: document, express

#1067 fix: missing `global` in browser environments
  packages/opentelemetry-api/package.json
  packages/opentelemetry-api/src/api/global-utils.ts
  packages/opentelemetry-api/src/platform/browser/globalThis.ts
  packages/opentelemetry-api/src/platform/browser/index.ts
  packages/opentelemetry-api/src/platform/index.ts
  packages/opentelemetry-api/src/platform/node/globalThis.ts
  packages/opentelemetry-api/src/platform/node/index.ts
Labels: bug

#1104 Fix:Spelling Mistake
  examples/basic-tracer-node/index.js
Labels: express

#1078 Add the missing plugin dependencies in tracing example
  getting-started/traced-example/package.json
Labels: express

#1085 chore: guidelines for Pull Requests and general Merge Requirements
  CONTRIBUTING.md
Labels: express

#1107 chore: test build
  .circleci/config.yml
  README.md
  packages/opentelemetry-api/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-base/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: express

#1091 chore: fixing a list of files to be in unit test coverage report
  .nycrc
Labels: express, size/XS

#980 feat: merge user supplied and default plugin configs
  examples/grpc/tracer.js
  packages/opentelemetry-node/README.md
  packages/opentelemetry-node/src/NodeTracerProvider.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-http-module/package.json
Labels: Merge:LGTM, enhancement

#1086 chore: send a welcome message to first time contributors
  .github/workflows/first-time-contributor.yml
Labels: express

#1106 chore: improve API documentation
  packages/opentelemetry-api/README.md
  packages/opentelemetry-api/src/context/propagation/HttpTextPropagator.ts
  packages/opentelemetry-api/src/metrics/MeterProvider.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/trace/NoopTracerProvider.ts
  packages/opentelemetry-api/src/trace/SpanOptions.ts
  packages/opentelemetry-api/src/trace/attributes.ts
  packages/opentelemetry-api/src/trace/link.ts
  packages/opentelemetry-api/src/trace/span.ts
  packages/opentelemetry-api/src/trace/tracer.ts
  packages/opentelemetry-api/src/trace/tracer_provider.ts
Labels: Merge:LGTM, document

#1100 docs(batcher): document how to configure custom aggregators #989
  doc/batcher-api.md
Labels: document, size/L

#1099 fix(asynchooks-scope): fix context loss using .with() #1101
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: bug, size/L

#1058 feat: spec compliant sampling result support
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/trace/Sampler.ts
  packages/opentelemetry-api/src/trace/SamplingResult.ts
  packages/opentelemetry-core/src/trace/sampler/ProbabilitySampler.ts
  packages/opentelemetry-core/test/trace/ProbabilitySampler.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: breaking
