Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-06, with the labels that each got.

#1117 chore: rename meaure to value recorder
  packages/opentelemetry-api/src/metrics/BoundInstrument.ts
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-api/test/noop-implementations/noop-meter.test.ts
  packages/opentelemetry-metrics/README.md
  packages/opentelemetry-metrics/src/BoundInstrument.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/src/export/aggregators/ValueRecorderExact.ts
  packages/opentelemetry-metrics/src/export/aggregators/index.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: API, breaking

#1134 chore: remove first time contribution greeting
  .github/workflows/first-time-contributor.yml
Labels: express

#1140 update nyc to 15.1.0 in all package.json file
  packages/opentelemetry-api/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-base/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: dependencies

#1133 fix(plugin-xml-http-request): support sync requests
  packages/opentelemetry-plugin-xml-http-request/src/xhr.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
Labels: enhancement

#1142 chore: template prometheus endpoint in examples rather than hardcode
  examples/metrics/metrics/observer.js
  examples/prometheus/index.js
  getting-started/README.md
  getting-started/monitored-example/monitoring.js
  getting-started/ts-example/README.md
  getting-started/ts-example/monitoring.ts
Labels: express, size/XS

#1145 chore: creating new metric kind
  packages/opentelemetry-metrics/src/export/types.ts
Labels: size/XS

#1138 feat(opentelemetry-js): infer zipkin service name from resource
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-exporter-zipkin/src/types.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts
Labels: enhancement

#1126 feat!: remove label keys as they are no longer part of the spec
  examples/metrics/metrics/observer.js
  examples/prometheus/index.js
  getting-started/README.md
  getting-started/monitored-example/monitoring.js
  getting-started/ts-example/README.md
  getting-started/ts-example/monitoring.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-exporter-prometheus/README.md
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-metrics/README.md
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Batcher.test.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
Labels: breaking

#1151 chore(todo): add missing span sampling test
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
Labels: Merge:LGTM

#1185 chore: remove double blank lines
  examples/grpc/helloworld_pb.js
Labels: express, size/XS

#1120 feat: add the UpDownCounter instrument
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-metrics/src/BoundInstrument.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/UpDownCounterMetric.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/index.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
Labels: breaking, enhancement

#1148 chore: add grpc-js skeleton
  packages/opentelemetry-plugin-grpc-js/.eslintignore
  packages/opentelemetry-plugin-grpc-js/.eslintrc.js
  packages/opentelemetry-plugin-grpc-js/.npmignore
  packages/opentelemetry-plugin-grpc-js/LICENSE
  packages/opentelemetry-plugin-grpc-js/README.md
  packages/opentelemetry-plugin-grpc-js/package.json
  packages/opentelemetry-plugin-grpc-js/src/enums/AttributeNames.ts
  packages/opentelemetry-plugin-grpc-js/src/grpcJs.ts
  packages/opentelemetry-plugin-grpc-js/src/version.ts
  packages/opentelemetry-plugin-grpc-js/tsconfig.json
Labels: Merge:LGTM

#1181 feat: add node-plugins-all package
  metapackages/plugins-node-all/README.md
  metapackages/plugins-node-all/package.json
Labels: Merge:LGTM

#1204 feat: collector exporter custom headers and metadata
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/types.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorExporter.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorExporter.test.ts
Labels: enhancement, size/L

#1209 chore: fixing zone from which to fork a new zone
  packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts
  packages/opentelemetry-context-zone-peer-dep/test/ZoneContextManager.test.ts
Labels: Merge:LGTM, bug, size/XS

#1217 chore: fix markdown linting and add npm script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/plugin_request.md
  .markdownlint.json
  examples/tracer-web/README.md
  metapackages/plugins-node-all/README.md
  package.json
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-plugin-fetch/README.md
  packages/opentelemetry-plugin-grpc-js/README.md
Labels: express

#1202 Adds possibility to set headers to zipkin exporter
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-exporter-zipkin/src/types.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts
Labels: Merge:LGTM, enhancement, size/S

#1218 fix: change default propagator to match spec
  packages/opentelemetry-core/README.md
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-web/test/registration.test.ts
Labels: Merge:LGTM, enhancement

#1226 chore(renovate): remove rebaseWhen config
  renovate.json
Labels: express

#1231 fix(jsdoc): change null to undefined
  packages/opentelemetry-api/src/trace/tracer.ts
Labels: document, express

#1216 Increase Test Coverage for XML Http Plugin
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
Labels: Merge:LGTM, enhancement

#1171 feat: add instrumentation library and update collector exporter
  packages/opentelemetry-core/src/common/types.ts
  packages/opentelemetry-exporter-collector/src/transform.ts
  packages/opentelemetry-exporter-collector/test/common/transform.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/MeterProvider.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/UpDownCounterMetric.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/export/ReadableSpan.ts
  packages/opentelemetry-tracing/test/Span.test.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: Merge:LGTM

#1210 AsyncLocalStorage based ContextManager
  packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/src/AsyncLocalStorageContextManager.ts
  packages/opentelemetry-context-async-hooks/src/index.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: Merge:LGTM

#1239 chore: update metrics example with UpDownCounter
  examples/prometheus/README.md
  examples/prometheus/images/prom-counter.png
  examples/prometheus/images/prom-ui.png
  examples/prometheus/images/prom-updowncounter.png
  examples/prometheus/index.js
  getting-started/README.md
  getting-started/monitored-example/monitoring.js
  getting-started/ts-example/README.md
  getting-started/ts-example/monitoring.ts
  packages/opentelemetry-metrics/README.md
Labels: document
