Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-01, with the labels that each got.

#643 feat(plugin-http): add/modify attributes
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-http/src/enums/AttributeNames.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/utils/assertSpan.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/utils/assertSpan.ts
Labels: Merge:LGTM, enhancement

#646 chore: update default plugins list and fix npm badge
  README.md
  packages/opentelemetry-node/src/config.ts
  packages/opentelemetry-plugin-xml-http-request/README.md
Labels: Merge:LGTM, document

#652 feat: port mongodb-core plugin to mongodb #622
  .circleci/config.yml
  README.md
  packages/opentelemetry-node/src/config.ts
  packages/opentelemetry-plugin-mongodb-core/src/version.ts
  packages/opentelemetry-plugin-mongodb/.npmignore
  packages/opentelemetry-plugin-mongodb/LICENSE
  packages/opentelemetry-plugin-mongodb/README.md
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mongodb/src/index.ts
  packages/opentelemetry-plugin-mongodb/src/mongodb.ts
  packages/opentelemetry-plugin-mongodb/src/types.ts
  packages/opentelemetry-plugin-mongodb/test/mongodb.test.ts
  packages/opentelemetry-plugin-mongodb/tsconfig.json
  packages/opentelemetry-plugin-mongodb/tslint.json
Labels: enhancement

#662 feat: add pg-pool to default list of instrumented plugins
  packages/opentelemetry-node/src/config.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
Labels: enhancement

#664 Code cleanup
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/export/MetricProducerManager.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-node/test/NodeTracer.test.ts
  packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts
  packages/opentelemetry-plugin-mongodb/test/mongodb.test.ts
  packages/opentelemetry-web/test/utils.test.ts
Labels: cleanup, size/L

#675 chore: adding missing information about exporter-collector
  README.md
Labels: document, size/XS

#676 remove HTTP2 package skeleton
  packages/opentelemetry-plugin-http2/.npmignore
  packages/opentelemetry-plugin-http2/LICENSE
  packages/opentelemetry-plugin-http2/README.md
  packages/opentelemetry-plugin-http2/package.json
  packages/opentelemetry-plugin-http2/src/index.ts
  packages/opentelemetry-plugin-http2/src/version.ts
  packages/opentelemetry-plugin-http2/tsconfig.json
  packages/opentelemetry-plugin-http2/tslint.json
Labels: cleanup

#687 chore: upgrade ts-node version to ^8.6.2
  packages/opentelemetry-base/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-document-load/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-scope-async-hooks/package.json
  packages/opentelemetry-scope-base/package.json
  packages/opentelemetry-scope-zone-peer-dep/package.json
  packages/opentelemetry-scope-zone/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-test-utils/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: dependencies

#677 chore: update date for v0.4
  README.md
Labels: document

#702 chore: add missing semver type dependency
  packages/opentelemetry-plugin-dns/package.json
Labels: dependencies

#648 feat: stackdriver trace exporter
  .circleci/config.yml
  README.md
  examples/basic-tracer-node/multi_exporter.js
  examples/stackdriver-trace/.gitignore
  examples/stackdriver-trace/README.md
  examples/stackdriver-trace/images/trace.png
  examples/stackdriver-trace/index.js
  examples/stackdriver-trace/package.json
  packages/opentelemetry-exporter-stackdriver-trace/.npmignore
  packages/opentelemetry-exporter-stackdriver-trace/LICENSE
  packages/opentelemetry-exporter-stackdriver-trace/README.md
  packages/opentelemetry-exporter-stackdriver-trace/package.json
  packages/opentelemetry-exporter-stackdriver-trace/src/external-types.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/index.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/trace.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/transform.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/types.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/version.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/exporter.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/transform.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/tsconfig.json
  packages/opentelemetry-exporter-stackdriver-trace/tslint.json
Labels: Merge:LGTM, enhancement, size/XXL

#704 fix(getting-started): remove extra comma
  getting-started/ts-example/package.json
Labels: dependencies, document, size/XS

#701 feat: add jaeger http trace format (#696)
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-propagator-jaeger/.npmignore
  packages/opentelemetry-propagator-jaeger/LICENSE
  packages/opentelemetry-propagator-jaeger/README.md
  packages/opentelemetry-propagator-jaeger/jaeger-tracing.png
  packages/opentelemetry-propagator-jaeger/karma.conf.js
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTraceFormat.ts
  packages/opentelemetry-propagator-jaeger/src/index.ts
  packages/opentelemetry-propagator-jaeger/src/version.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTraceFormat.test.ts
  packages/opentelemetry-propagator-jaeger/test/index-webpack.ts
  packages/opentelemetry-propagator-jaeger/tsconfig-release.json
  packages/opentelemetry-propagator-jaeger/tsconfig.json
  packages/opentelemetry-propagator-jaeger/tslint.json
Labels: Merge:LGTM, enhancement

#709 update getting started to tracer registry
  getting-started/README.md
  getting-started/traced-example/tracing.js
  getting-started/ts-example/tracing.ts
Labels: document

#716 docs: typo in Ville de Montréal
  README.md
Labels: document, size/XS

#714 fix: return module exports from ioredis
  packages/opentelemetry-plugin-ioredis/src/ioredis.ts
Labels: Merge:LGTM, bug, size/XS

#710 Update README to include documentation link
  README.md
Labels: document

#708 Simplify and speed up trace context parsing
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
Labels: Merge:LGTM, enhancement

#661 Release process
  RELEASING.md
Labels: Merge:LGTM, document

#720 fix: package links in README
  README.md
Labels: Merge:LGTM, document

#725 Post Release: update CHANGELOG.md
  CHANGELOG.md
Labels: Merge:LGTM, document

#726 chore: remove redundant statement
  README.md
Labels: document, size/XS

#715 fix: unref jaeger socket to prevent process running indefinitely
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
Labels: Merge:LGTM, bug, size/XS

#730 chore: publish docs on all tags
  .circleci/config.yml
Labels: document

#689 Add benchmark README and latest numbers
  benchmark/README.md
  benchmark/benchmark.js
  benchmark/index.js
  benchmark/propagator.js
  benchmark/tracer.js
Labels: Merge:LGTM, document, size/M

#719 feat(plugin-http): sync. specs for statuscode
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
Labels: Merge:LGTM, enhancement, size/M

#733 chore: add instruction for pg-pool plugin
  packages/opentelemetry-plugin-grpc/README.md
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-https/README.md
  packages/opentelemetry-plugin-ioredis/README.md
  packages/opentelemetry-plugin-mongodb/README.md
  packages/opentelemetry-plugin-mysql/README.md
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/README.md
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/README.md
  packages/opentelemetry-plugin-redis/README.md
Labels: Merge:LGTM, document

#671 [ioredis plugin] fix: change supportedVersions to >1 <5
  packages/opentelemetry-plugin-ioredis/src/ioredis.ts
Labels: Merge:LGTM, bug, size/XS

#731 Update Stackdriver exporter example
  examples/postgres/package.json
  examples/stackdriver-trace/index.js
Labels: Has Merge Conflict

#735 feat: decode jaeger header
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTraceFormat.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTraceFormat.test.ts
Labels: enhancement
