Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-12, with the labels that each got.

#1693 chore: use getParentSpanContext() where applicable
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-propagator-b3/test/B3MultiPropagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3SinglePropagator.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: internal

#1696 chore: use WebTracerProvider instead of WebTracer in docs
  packages/opentelemetry-context-zone-peer-dep/README.md
  packages/opentelemetry-context-zone/README.md
  packages/opentelemetry-instrumentation-xml-http-request/README.md
Labels: document

#1700 Metrics updates
  doc/processor-api.md
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/helper.ts
  packages/opentelemetry-exporter-collector/src/transformMetrics.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/common/transformMetrics.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-prometheus/test/ExactProcessor.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
  packages/opentelemetry-metrics/src/BaseObserverMetric.ts
  packages/opentelemetry-metrics/src/BatchObserverMetric.ts
  packages/opentelemetry-metrics/src/CounterMetric.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/MonotonicObserverResult.ts
  packages/opentelemetry-metrics/src/SumObserverMetric.ts
  packages/opentelemetry-metrics/src/UpDownCounterMetric.ts
  packages/opentelemetry-metrics/src/UpDownSumObserverMetric.ts
  packages/opentelemetry-metrics/src/ValueObserverMetric.ts
  packages/opentelemetry-metrics/src/ValueRecorderMetric.ts
  packages/opentelemetry-metrics/src/export/Controller.ts
  packages/opentelemetry-metrics/src/export/Processor.ts
  packages/opentelemetry-metrics/src/index.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-metrics/test/Processor.test.ts
  packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
  packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-sdk-node/src/sdk.ts
  packages/opentelemetry-sdk-node/src/types.ts
Labels: breaking, enhancement

#1669 Feat: Added Amazon EKS Resource Detector
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/index.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsEksDetector.test.ts
Labels: enhancement

#1715 chore: moving plugin from api to core
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/platform/BaseAbstractPlugin.ts
  packages/opentelemetry-core/src/platform/browser/BasePlugin.ts
  packages/opentelemetry-core/src/platform/node/BasePlugin.ts
  packages/opentelemetry-core/src/trace/Plugin.ts
  packages/opentelemetry-grpc-utils/test/grpcUtils.test.ts
  packages/opentelemetry-node/src/instrumentation/PluginLoader.ts
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-plugin-grpc-js/src/types.ts
  packages/opentelemetry-plugin-grpc/src/types.ts
  packages/opentelemetry-plugin-http/src/types.ts
Labels: breaking, enhancement

#1720 fix(xhr): check for resource timing support
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
Labels: bug

#1708 feat(exporter-collector): implement concurrencyLimit option
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-collector/src/CollectorExporterBase.ts
  packages/opentelemetry-exporter-collector/src/types.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorTraceExporter.test.ts
Labels: enhancement

#1625 feat(opentelemetry-js): add content size attributes to HTTP spans
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-plugin-http/test/utils/assertSpan.ts
  packages/opentelemetry-semantic-conventions/src/trace/http.ts
Labels: enhancement, release:required-for-ga

#1734 chore: requires user to pass context to propagation APIs
  integration-tests/propagation-validation-server/validation-server.js
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/src/version.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-plugin-grpc-js/src/client/utils.ts
  packages/opentelemetry-plugin-grpc-js/src/server/patchServer.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: API, breaking

#1747 feat: fixing failing test
  packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts
Labels: bug

#1697 fix(exporter-prometheus): add appendTimestamp option to ExporterConfig
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-prometheus/src/export/types.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
Labels: enhancement

#1687 chore: rename CorrelationContext to Baggage
  README.md
  packages/opentelemetry-api/src/baggage/Baggage.ts
  packages/opentelemetry-api/src/baggage/EntryValue.ts
  packages/opentelemetry-api/src/context/context.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-api/src/trace/span_context.ts
  packages/opentelemetry-core/README.md
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggage.ts
  packages/opentelemetry-core/src/correlation-context/correlation-context.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/baggage/HttpBaggage.test.ts
  packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
Labels: enhancement, release:required-for-ga

#1685 chore: remove ordered attribute dropping
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: enhancement, release:required-for-ga

#1709 refactor: batch observer to be independent from metric types
  examples/metrics/metrics/observer.js
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-metrics/README.md
  packages/opentelemetry-metrics/src/BatchObserver.ts
  packages/opentelemetry-metrics/src/BatchObserverResult.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: breaking

#1684 feat(semantic-conventions): messaging specifications
  packages/opentelemetry-semantic-conventions/src/trace/index.ts
  packages/opentelemetry-semantic-conventions/src/trace/messaging.ts
Labels: enhancement

#1758 fix(@opentelemetry/exporter-jaeger): fixed issue #1757
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
Labels: bug

#1749 chore: improve naming of span related context APIs
  packages/opentelemetry-api/src/context/context.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts
  packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts
  packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts
  packages/opentelemetry-propagator-b3/test/B3MultiPropagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3SinglePropagator.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/export/InMemorySpanExporter.test.ts
Labels: API, breaking

#1725 Use new gRPC default port
  examples/collector-exporter-node/docker/docker-compose.yaml
  packages/opentelemetry-exporter-collector-grpc/README.md
  packages/opentelemetry-exporter-collector-grpc/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/README.md
Labels: breaking, bug

#1764 chore: remove tracer apis not part of spec
  README.md
  examples/basic-tracer-node/index.js
  examples/collector-exporter-node/tracing.js
  examples/grpc-js/client.js
  examples/grpc-js/server.js
  examples/grpc/client.js
  examples/grpc/server.js
  examples/http/client.js
  examples/http/server.js
  examples/https/client.js
  examples/https/server.js
  examples/tracer-web/examples/document-load/index.js
  examples/tracer-web/examples/fetch/index.js
  examples/tracer-web/examples/xml-http-request/index.js
  integration-tests/propagation-validation-server/validation-server.js
  packages/opentelemetry-api/README.md
  packages/opentelemetry-api/src/api/global-utils.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-api/src/trace/ProxyTracer.ts
  packages/opentelemetry-api/src/trace/tracer.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-api/test/proxy-implementations/proxy-tracer.test.ts
  packages/opentelemetry-context-zone-peer-dep/README.md
  packages/opentelemetry-context-zone/README.md
  packages/opentelemetry-grpc-utils/test/grpcUtils.test.ts
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-disable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-disable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-plugin-fetch/test/fetch.test.ts
  packages/opentelemetry-plugin-grpc-js/src/client/utils.ts
  packages/opentelemetry-plugin-grpc-js/src/server/clientStreamAndUnary.ts
  packages/opentelemetry-plugin-grpc-js/src/server/patchServer.ts
  packages/opentelemetry-plugin-grpc-js/src/server/serverStreamAndBidi.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-disable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-disable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
Labels: API, Merge:LGTM, breaking

#1771 feat(http-instrumentation): add content size attributes to spans
  packages/opentelemetry-instrumentation-http/src/utils.ts
  packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
  packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
Labels: enhancement

#1755 feat: batch span processor environment config
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: enhancement, release:required-for-ga, size/M

#1781 chore: fix docs workflow
  .github/workflows/docs.yml
Labels: express, internal, size/XS
