Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-04, with the labels that each got.

#915 Remove label set from metrics API
  examples/metrics/metrics/observer.js
  examples/prometheus/index.js
  getting-started/README.md
  getting-started/monitored-example/monitoring.js
  getting-started/ts-example/README.md
  getting-started/ts-example/monitoring.ts
  packages/opentelemetry-api/src/metrics/Meter.ts
  packages/opentelemetry-api/src/metrics/Metric.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-api/src/metrics/ObserverResult.ts
  packages/opentelemetry-api/test/noop-implementations/noop-meter.test.ts
  packages/opentelemetry-exporter-prometheus/README.md
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-metrics/README.md
  packages/opentelemetry-metrics/src/BoundInstrument.ts
  packages/opentelemetry-metrics/src/LabelSet.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/ObserverResult.ts
  packages/opentelemetry-metrics/src/Utils.ts
  packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/src/index.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
  packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
Labels: API, Merge:LGTM, breaking, size/L

#916 chore: removing force flush
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/src/types.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
Labels: Merge:LGTM, size/S

#937 fix: Jaeger propagator example of usage"
  packages/opentelemetry-propagator-jaeger/README.md
Labels: Merge:LGTM, document

#933 feat(meter): allow custom batcher #932
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: Merge:express, enhancement, size/S

#941 fix: do not clear other labelsets when updating metrics
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
  packages/opentelemetry-metrics/src/export/Batcher.ts
  packages/opentelemetry-metrics/test/Batcher.test.ts
Labels: bug

#946 Remove bad null check
  packages/opentelemetry-plugin-http/src/utils.ts
Labels: Merge:express, bug

#939 Updating out of date @types/mocha packages
  packages/opentelemetry-api/package.json
  packages/opentelemetry-base/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-base/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-document-load/package.json
  packages/opentelemetry-plugin-express/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-ioredis/package.json
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-plugin-user-interaction/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: dependencies

#924 [Jaeger-Exporter] host default env var
  packages/opentelemetry-exporter-jaeger/README.md
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
Labels: Merge:express, enhancement

#949 chore: fixing wrong return type for metric observer callback
  packages/opentelemetry-api/src/metrics/BoundInstrument.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-metrics/src/BoundInstrument.ts
Labels: Merge:express, size/XS

#947 chore: adding timestamp for prometheus metric Counter
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts
Labels: size/M

#957 Removing @types/nock from all package.json files
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
Labels: Merge:express, dependencies

#958 chore: adding example for collector-exporter for node with opentelemetry-collector
  .circleci/config.yml
  examples/collector-exporter-node/README.md
  examples/collector-exporter-node/docker/collector-config.yaml
  examples/collector-exporter-node/docker/docker-compose.yaml
  examples/collector-exporter-node/images/spans.png
  examples/collector-exporter-node/package.json
  examples/collector-exporter-node/start.js
Labels: size/L

#910 fix(plugin-express): fix double span end #908
  packages/opentelemetry-plugin-express/README.md
  packages/opentelemetry-plugin-express/src/express.ts
  packages/opentelemetry-plugin-express/src/utils.ts
  packages/opentelemetry-plugin-express/src/version.ts
  packages/opentelemetry-plugin-express/test/express.test.ts
Labels: bug, size/S

#960 [http] fix: use url.URL
  packages/opentelemetry-plugin-http/src/http.ts
Labels: Merge:express

#977 fix(B3Propagator): B3 sampled causing gRPC error
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
Labels: Merge:express, bug

#943 Use global API instances
  packages/opentelemetry-api/README.md
  packages/opentelemetry-api/src/api/context.ts
  packages/opentelemetry-api/src/api/global-utils.ts
  packages/opentelemetry-api/src/api/metrics.ts
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/api/trace.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-api/test/api/global.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-plugin-grpc/test/grpc.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts
  packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-package.test.ts
  packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
  packages/opentelemetry-web/test/registration.test.ts
Labels: API, Merge:LGTM, enhancement

#990 fix(opentracing-shim): update opentracing shim example
  examples/opentracing-shim/client.js
  examples/opentracing-shim/server.js
Labels: document

#926 feat(context): implement withAsync #752
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: size/L
