Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-09, with the labels that each got.

#1470 IMPORTANT - Fixing collecting data from observers when using batch observer in first run
  packages/opentelemetry-metrics/src/BatchObserverMetric.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: bug, size/M

#1439 unifying shutdown across code base
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-proto/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/CollectorExporterBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporterBrowserBase.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/MeterProvider.ts
  packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts
  packages/opentelemetry-metrics/src/export/Controller.ts
  packages/opentelemetry-metrics/src/export/NoopExporter.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/test/MeterProvider.test.ts
  packages/opentelemetry-plugin-fetch/test/fetch.test.ts
  packages/opentelemetry-plugin-xml-http-request/test/unmocked.test.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/ConsoleSpanExporter.ts
  packages/opentelemetry-tracing/src/export/InMemorySpanExporter.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SpanExporter.ts
  packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/TestTracingSpanExporter.ts
Labels: enhancement

#1532 fix: decrease level of non-supported-version logs to warn
  packages/opentelemetry-node/src/instrumentation/PluginLoader.ts
Labels: enhancement

#1539 fix: include missing proto files in npm distribution
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
Labels: bug

#1530 fix: ignore TIMERWRAP in AsyncHooksContextManager
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: bug

#1515 chore: use interface for context types
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/src/AsyncLocalStorageContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
  packages/opentelemetry-context-base/src/NoopContextManager.ts
  packages/opentelemetry-context-base/src/context.ts
  packages/opentelemetry-context-base/src/index.ts
  packages/opentelemetry-context-base/src/types.ts
  packages/opentelemetry-context-base/test/NoopContextManager.test.ts
  packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts
  packages/opentelemetry-context-zone-peer-dep/test/ZoneContextManager.test.ts
  packages/opentelemetry-core/src/context/context.ts
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/src/correlation-context/correlation-context.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-core/test/context/context.test.ts
  packages/opentelemetry-core/test/correlation-context/HttpCorrelationContext.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
  packages/opentelemetry-tracing/test/export/TestStackContextManager.ts
  packages/opentelemetry-web/src/StackContextManager.ts
  packages/opentelemetry-web/test/StackContextManager.test.ts
Labels: API, enhancement

#1522 Remove process listener
  packages/opentelemetry-core/src/platform/browser/ShutdownNotifier.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/node/ShutdownNotifier.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  packages/opentelemetry-metrics/src/MeterProvider.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-metrics/test/MeterProvider.test.ts
  packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-sdk-node/src/sdk.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
Labels: breaking

#1531 feat: process resource detector
  packages/opentelemetry-resources/src/constants.ts
  packages/opentelemetry-resources/src/platform/node/detectors/ProcessDetector.ts
  packages/opentelemetry-resources/src/platform/node/detectors/index.ts
  packages/opentelemetry-resources/test/detectors/ProcessDetector.test.ts
  packages/opentelemetry-resources/test/util/resource-assertions.ts
  packages/opentelemetry-sdk-node/src/sdk.ts
Labels: enhancement

#1488 chore: ensure attributes are spec compliant
  packages/opentelemetry-api/src/trace/attributes.ts
  packages/opentelemetry-api/src/trace/span.ts
  packages/opentelemetry-core/src/common/attributes.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/common/attributes.test.ts
  packages/opentelemetry-exporter-collector/test/common/transform.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: internal, release:required-for-ga

#1537 chore: change SpanContext.traceFlags to number
  packages/opentelemetry-api/src/trace/span_context.ts
Labels: API, internal

#1543 feat: enable dns instrumentation by default
  README.md
  packages/opentelemetry-node/src/config.ts
Labels: enhancement

#1536 chore: variable names cleanup
  examples/tracer-web/examples/fetch/index.js
Labels: document

#1551 fix: avoid circular require in plugins
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-https/src/https.ts
  packages/opentelemetry-plugin-https/src/utils.ts
Labels: bug

#1404 Feat: Added AWS ECS Plugins Resource Detector
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/index.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsEcsDetector.test.ts
  packages/opentelemetry-resources/src/constants.ts
  packages/opentelemetry-resources/test/resource-assertions.test.ts
  packages/opentelemetry-resources/test/util/resource-assertions.ts
Labels: enhancement, feature-request

#1503 feat: add deep-merge util
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/deep-merge.ts
  packages/opentelemetry-core/test/utils/deep-merge.test.ts
Labels: enhancement

#1555 chore: disallow null attribute values
  packages/opentelemetry-api/src/trace/attributes.ts
  packages/opentelemetry-api/src/trace/span.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: release:required-for-ga

#1550 EOL semantics by adding .gitattributes and changing tsconfig.json
  .gitattributes
  packages/tsconfig.base.json
  scripts/version-update.js
Labels: enhancement

#1375 feat: make prometheus config preventServerStart optional
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-prometheus/src/export/types.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
Labels: breaking

#1540 Plugins refactoring - new instrumentation package for plugins
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/trace/NoopLogger.ts
  packages/opentelemetry-instrumentation/.eslintignore
  packages/opentelemetry-instrumentation/.eslintrc.js
  packages/opentelemetry-instrumentation/.npmignore
  packages/opentelemetry-instrumentation/LICENSE
  packages/opentelemetry-instrumentation/README.md
  packages/opentelemetry-instrumentation/karma.conf.js
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-instrumentation/src/index.ts
  packages/opentelemetry-instrumentation/src/instrumentation.ts
  packages/opentelemetry-instrumentation/src/platform/browser/index.ts
  packages/opentelemetry-instrumentation/src/platform/browser/instrumentation.ts
  packages/opentelemetry-instrumentation/src/platform/index.ts
  packages/opentelemetry-instrumentation/src/platform/node/index.ts
  packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
  packages/opentelemetry-instrumentation/src/platform/node/instrumentationNodeModuleDefinition.ts
  packages/opentelemetry-instrumentation/src/platform/node/instrumentationNodeModuleFile.ts
  packages/opentelemetry-instrumentation/src/platform/node/require-in-the-middle.d.ts
  packages/opentelemetry-instrumentation/src/platform/node/types.ts
  packages/opentelemetry-instrumentation/src/types.ts
  packages/opentelemetry-instrumentation/src/utils.ts
  packages/opentelemetry-instrumentation/src/version.ts
  packages/opentelemetry-instrumentation/test/browser/index-webpack.ts
  packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
  packages/opentelemetry-instrumentation/tsconfig.json
  packages/opentelemetry-node/package.json
Labels: enhancement
