Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-11, with the labels that each got.

#1636 chore: eslint - fix unused vars warnings, add precommit lint - part 1
  eslint.config.js
  package.json
  packages/opentelemetry-api/src/context/propagation/NoopTextMapPropagator.ts
  packages/opentelemetry-api/src/metrics/NoopMeter.ts
  packages/opentelemetry-api/src/trace/NoopLogger.ts
  packages/opentelemetry-api/src/trace/NoopSpan.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-context-base/src/NoopContextManager.ts
  packages/opentelemetry-core/src/common/ConsoleLogger.ts
  packages/opentelemetry-core/src/common/NoopLogger.ts
  packages/opentelemetry-core/src/platform/browser/timer-util.ts
  packages/opentelemetry-core/src/trace/sampler/AlwaysOffSampler.ts
  packages/opentelemetry-core/src/trace/sampler/AlwaysOnSampler.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-metrics/src/export/Controller.ts
  packages/opentelemetry-metrics/src/export/NoopExporter.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
Labels: internal

#1642 feat: isRecording return false if span is ended #1633
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: size/M

#1612 chore: remove explicit parent option
  packages/opentelemetry-api/src/api/global-utils.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-api/src/trace/SpanOptions.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: enhancement, release:required-for-ga

#1474 chore(zipkin): export ExporterConfig
  packages/opentelemetry-exporter-zipkin/src/index.ts
Labels: enhancement

#1643 refactor: new interface for ExportResult #1569
  packages/opentelemetry-core/src/ExportResult.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/src/CollectorExporterBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/util.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
  packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts
  packages/opentelemetry-metrics/src/export/Controller.ts
  packages/opentelemetry-metrics/test/export/Controller.test.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/ConsoleSpanExporter.ts
  packages/opentelemetry-tracing/src/export/InMemorySpanExporter.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/InMemorySpanExporter.test.ts
  packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
Labels: breaking, internal, release:required-for-ga, size/L

#1644 fix!: change status codes from grpc status codes
  packages/opentelemetry-api/README.md
  packages/opentelemetry-api/src/trace/span.ts
  packages/opentelemetry-api/src/trace/status.ts
  packages/opentelemetry-api/test/noop-implementations/noop-span.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
  packages/opentelemetry-exporter-collector-proto/test/helper.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/src/transform.ts
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/helper.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-grpc-utils/test/utils/assertionUtils.ts
  packages/opentelemetry-plugin-grpc-js/src/client/utils.ts
  packages/opentelemetry-plugin-grpc-js/src/server/clientStreamAndUnary.ts
  packages/opentelemetry-plugin-grpc-js/src/server/serverStreamAndBidi.ts
  packages/opentelemetry-plugin-grpc-js/src/utils.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-grpc/src/utils.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: breaking, release:required-for-ga

#1641 fix: do not access promise before resolve
  examples/tracer-web/examples/user-interaction/index.js
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-proto/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporterBrowserBase.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
Labels: bug

#1653 chore: env vars for span limit as per specification
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-tracing/src/config.ts
  packages/opentelemetry-tracing/src/utility.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: enhancement

#1659 feat: replacing base plugin with instrumentation for xml-http-request
  .circleci/config.yml
  README.md
  examples/tracer-web/examples/user-interaction/index.html
  examples/tracer-web/examples/user-interaction/index.js
  examples/tracer-web/examples/xml-http-request/index.js
  examples/tracer-web/package.json
  metapackages/plugins-web-core/README.md
  metapackages/plugins-web-core/package.json
  packages/opentelemetry-instrumentation-xml-http-request/.eslintignore
  packages/opentelemetry-instrumentation-xml-http-request/.eslintrc.js
  packages/opentelemetry-instrumentation-xml-http-request/.npmignore
  packages/opentelemetry-instrumentation-xml-http-request/LICENSE
  packages/opentelemetry-instrumentation-xml-http-request/README.md
  packages/opentelemetry-instrumentation-xml-http-request/images/cors.jpg
  packages/opentelemetry-instrumentation-xml-http-request/images/main.jpg
  packages/opentelemetry-instrumentation-xml-http-request/images/request.jpg
  packages/opentelemetry-instrumentation-xml-http-request/karma.conf.js
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation-xml-http-request/src/enums/EventNames.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/index.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/types.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/version.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/index-webpack.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/unmocked.test.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-instrumentation-xml-http-request/tsconfig.json
  packages/opentelemetry-instrumentation/src/instrumentation.ts
  packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
  packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
  packages/opentelemetry-web/package.json
  packages/opentelemetry-web/src/WebTracerProvider.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
Labels: enhancement

#1666 fix: clear BatchSpanProcessor internal spans buffer before exporting
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: bug

#1651 chore: use performance directly in xhr plugin
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Labels: enhancement

#1650 docs: document null and undefined attribute values undefined behavior
  packages/opentelemetry-api/src/trace/attributes.ts
  packages/opentelemetry-api/src/trace/span.ts
Labels: release:required-for-ga

#1607 feat(exporter-collector): log upstream error #1459
  packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/helper.ts
  packages/opentelemetry-exporter-collector/src/platform/node/util.ts
  packages/opentelemetry-exporter-collector/src/types.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/nodeHelpers.ts
Labels: enhancement, size/M

#1628 fix: boundaries option propagation in ValueRecorder Metric
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/helper.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/common/transformMetrics.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
  packages/opentelemetry-metrics/src/Metric.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: enhancement

#1670 feat(semantic-conventions): FaaS specifications
  packages/opentelemetry-semantic-conventions/src/trace/faas.ts
  packages/opentelemetry-semantic-conventions/src/trace/index.ts
Labels: enhancement

#1692 chore: remove unused tracer config gracefulShutdown
  packages/opentelemetry-tracing/src/config.ts
  packages/opentelemetry-tracing/src/types.ts
Labels: enhancement
