Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-10, with the labels that each got.

#1548 chore(http): remove `x-opentelemetry-outgoing-request` header #1547
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/types.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/src/utils.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
  packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
  packages/opentelemetry-exporter-zipkin/src/utils.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-grpc-utils/test/grpcUtils.test.ts
  packages/opentelemetry-plugin-grpc-js/src/client/utils.ts
  packages/opentelemetry-plugin-grpc-js/src/server/patchServer.ts
  packages/opentelemetry-plugin-grpc-js/src/utils.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-grpc/src/utils.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/src/utils.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
Labels: enhancement, size/L

#1525 feat(node-tracer): use AsyncLocalStorageContextManager by default starting Node 14.8 #1511
  packages/opentelemetry-node/src/NodeTracerProvider.ts
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-sdk-node/test/sdk.test.ts
Labels: size/S

#1527 feat(api): propagate spanContext only using API #1456
  benchmark/propagator.js
  packages/opentelemetry-api/src/context/context.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-api/test/context/context.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
  packages/opentelemetry-tracing/test/export/InMemorySpanExporter.test.ts
Labels: enhancement, size/L

#1562 feat(core): rename ProbabilitySampler to TraceIdRatioBasedSampler
  packages/opentelemetry-core/README.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/sampler/ProbabilitySampler.ts
  packages/opentelemetry-core/src/trace/sampler/TraceIdRatioBasedSampler.ts
  packages/opentelemetry-core/test/trace/ParentOrElseSampler.test.ts
  packages/opentelemetry-core/test/trace/ProbabilitySampler.test.ts
  packages/opentelemetry-core/test/trace/TraceIdRatioBasedSampler.test.ts
  packages/opentelemetry-tracing/src/utility.ts
Labels: breaking

#1570 fix: make prometheus histogram export cumulative
  packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
Labels: enhancement

#1579 fix: correlation-context header
  packages/opentelemetry-core/src/correlation-context/propagation/HttpCorrelationContext.ts
Labels: enhancement

#1560 feat: b3 single header support
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-core/src/context/propagation/B3MultiPropagator.ts
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/src/context/propagation/B3SinglePropagator.ts
  packages/opentelemetry-core/src/context/propagation/b3-common.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/context/B3MultiPropagator.test.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/B3SinglePropagator.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-plugin-fetch/test/fetch.test.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
Labels: breaking, release:required-for-ga, size/XXL

#1581 chore: remove duplicate hostname resource attribute
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts
  packages/opentelemetry-resources/src/constants.ts
  packages/opentelemetry-resources/test/resource-assertions.test.ts
  packages/opentelemetry-resources/test/util/resource-assertions.ts
Labels: breaking, size/S

#1546 fix(http): do not set outgoing http span as active in the context #1479
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
Labels: bug, size/M

#1577 feat: implement parent based sampler
  packages/opentelemetry-core/README.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts
  packages/opentelemetry-core/src/trace/sampler/ParentOrElseSampler.ts
  packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-tracing/src/utility.ts
Labels: enhancement, release:required-for-ga

#1589 feat: simplify active span logic
  packages/opentelemetry-api/src/context/context.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-core/test/context/B3MultiPropagator.test.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/B3SinglePropagator.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: breaking, release:required-for-ga, size/M

#1576 feat: add keys operation to getter
  benchmark/propagator.js
  packages/opentelemetry-api/src/api/global-utils.ts
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/context/propagation/NoopTextMapPropagator.ts
  packages/opentelemetry-api/src/context/propagation/TextMapPropagator.ts
  packages/opentelemetry-api/src/context/propagation/getter.ts
  packages/opentelemetry-api/src/context/propagation/setter.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-core/src/context/propagation/B3MultiPropagator.ts
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/src/context/propagation/B3SinglePropagator.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/src/context/propagation/composite.ts
  packages/opentelemetry-core/src/correlation-context/propagation/HttpCorrelationContext.ts
  packages/opentelemetry-core/test/context/B3MultiPropagator.test.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/B3SinglePropagator.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-core/test/correlation-context/HttpCorrelationContext.test.ts
  packages/opentelemetry-plugin-fetch/src/fetch.ts
  packages/opentelemetry-plugin-grpc-js/src/client/utils.ts
  packages/opentelemetry-plugin-grpc-js/src/server/patchServer.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: API, breaking, release:required-for-ga

#1597 fix: make TraceState immutable
  packages/opentelemetry-api/src/trace/trace_state.ts
  packages/opentelemetry-core/src/trace/TraceState.ts
  packages/opentelemetry-core/test/trace/tracestate.test.ts
Labels: enhancement

#1621 chore: ensure onStart is called with a writeable span
  packages/opentelemetry-plugin-xml-http-request/test/unmocked.test.ts
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: enhancement, release:required-for-ga

#1616 docs: zone ctx manager can only be used with es2015
  packages/opentelemetry-context-zone-peer-dep/README.md
  packages/opentelemetry-web/README.md
Labels: document, release:required-for-ga

#1595 chore!: move b3 into its own package
  benchmark/propagator.js
  examples/tracer-web/examples/fetch/index.js
  examples/tracer-web/examples/xml-http-request/index.js
  examples/tracer-web/package.json
  packages/opentelemetry-api/README.md
  packages/opentelemetry-core/README.md
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-plugin-fetch/package.json
  packages/opentelemetry-plugin-fetch/test/fetch.test.ts
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-propagator-b3/.eslintignore
  packages/opentelemetry-propagator-b3/.eslintrc.js
  packages/opentelemetry-propagator-b3/.npmignore
  packages/opentelemetry-propagator-b3/LICENSE
  packages/opentelemetry-propagator-b3/README.md
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts
  packages/opentelemetry-propagator-b3/src/B3Propagator.ts
  packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts
  packages/opentelemetry-propagator-b3/src/common.ts
  packages/opentelemetry-propagator-b3/src/index.ts
  packages/opentelemetry-propagator-b3/src/types.ts
  packages/opentelemetry-propagator-b3/src/version.ts
  packages/opentelemetry-propagator-b3/test/B3MultiPropagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3SinglePropagator.test.ts
  packages/opentelemetry-propagator-b3/tsconfig.json
  packages/opentelemetry-web/package.json
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
Labels: breaking, release:required-for-ga, size/XL

#1615 chore: add fields operation to TextMapPropagator
  packages/opentelemetry-api/src/context/propagation/NoopTextMapPropagator.ts
  packages/opentelemetry-api/src/context/propagation/TextMapPropagator.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/src/context/propagation/composite.ts
  packages/opentelemetry-core/src/correlation-context/propagation/HttpCorrelationContext.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-core/test/correlation-context/HttpCorrelationContext.test.ts
  packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts
  packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts
  packages/opentelemetry-propagator-b3/src/B3Propagator.ts
  packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
Labels: enhancement

#1627 chore: fixing conversion of id to hex and base64
  examples/collector-exporter-node/docker/docker-compose.yaml
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
  packages/opentelemetry-exporter-collector-proto/test/helper.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/transform.ts
  packages/opentelemetry-exporter-collector/test/common/transform.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
Labels: bug

#1622 fix(tracing): use globalErrorHandler when flushing fails
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
Labels: enhancement

#1631 chore: sampler gets a full context
  packages/opentelemetry-api/src/trace/Sampler.ts
  packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts
  packages/opentelemetry-core/src/trace/sampler/TraceIdRatioBasedSampler.ts
  packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
Labels: enhancement, release:required-for-ga

#1632 feat: span processor onstart recieves context
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/Span.test.ts
  packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
Labels: enhancement, release:required-for-ga
