Repository open-telemetry/opentelemetry-js, pull requests merged in 2020-03, with the labels that each got.

#816 feat: use context-based tracing
  packages/opentelemetry-api/src/api/context.ts
  packages/opentelemetry-api/src/trace/SpanOptions.ts
  packages/opentelemetry-api/src/trace/tracer.ts
  packages/opentelemetry-node/src/NodeTracerProvider.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-dns/src/dns.ts
  packages/opentelemetry-plugin-document-load/src/documentLoad.ts
  packages/opentelemetry-plugin-document-load/test/documentLoad.test.ts
  packages/opentelemetry-plugin-express/package.json
  packages/opentelemetry-plugin-express/src/express.ts
  packages/opentelemetry-plugin-express/test/express.test.ts
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-plugin-grpc/test/grpc.test.ts
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts
  packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
  packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-https/test/functionals/https-disable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-package.test.ts
  packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts
  packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts
  packages/opentelemetry-plugin-ioredis/package.json
  packages/opentelemetry-plugin-ioredis/src/utils.ts
  packages/opentelemetry-plugin-ioredis/test/ioredis.test.ts
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mongodb/src/mongodb.ts
  packages/opentelemetry-plugin-mongodb/test/mongodb.test.ts
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-mysql/src/mysql.ts
  packages/opentelemetry-plugin-mysql/test/mysql.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/pg-pool.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/pg-pool.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/utils.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/pg.test.ts
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-plugin-redis/src/utils.ts
  packages/opentelemetry-plugin-redis/test/redis.test.ts
  packages/opentelemetry-plugin-user-interaction/src/userInteraction.ts
  packages/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
  packages/opentelemetry-plugin-user-interaction/test/userInteraction.test.ts
  packages/opentelemetry-plugin-xml-http-request/src/xhr.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/types.ts
  packages/opentelemetry-tracing/test/BasicTracerRegistry.test.ts
  packages/opentelemetry-tracing/test/export/InMemorySpanExporter.test.ts
  packages/opentelemetry-web/src/WebTracerProvider.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
Labels: enhancement, size/XXL

#830 chore: leftovers from merge
  packages/opentelemetry-resources/src/version.ts
Labels: size/XS

#802 chore: adding force flush to span processors
  packages/opentelemetry-exporter-collector/src/CollectorExporter.ts
  packages/opentelemetry-exporter-collector/test/common/CollectorExporter.test.ts
  packages/opentelemetry-exporter-zipkin/src/types.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts
  packages/opentelemetry-tracing/src/MultiSpanProcessor.ts
  packages/opentelemetry-tracing/src/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/SpanProcessor.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: Merge:LGTM, enhancement, nonconforming, size/L

#832 chore(Prometheus): fix broken badges
  packages/opentelemetry-exporter-prometheus/README.md
Labels: document, size/XS

#824 Faster trace id generation
  packages/opentelemetry-core/src/platform/browser/id.ts
  packages/opentelemetry-core/src/platform/node/id.ts
  packages/opentelemetry-core/test/platform/id.test.ts
Labels: Merge:LGTM, enhancement

#817 chore: remove SpanOptions.isRecording
  packages/opentelemetry-api/src/trace/SpanOptions.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: Merge:LGTM

#836 chore: fix usage instructions from READMEs
  packages/opentelemetry-node/README.md
  packages/opentelemetry-plugin-dns/README.md
  packages/opentelemetry-plugin-document-load/README.md
  packages/opentelemetry-plugin-user-interaction/README.md
  packages/opentelemetry-tracing/README.md
Labels: Merge:LGTM, document

#821 feat: add composite propagator
  packages/opentelemetry-core/src/context/propagation/composite.ts
  packages/opentelemetry-core/src/context/propagation/types.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/context/composite.test.ts
Labels: enhancement

#827 Add getter and setter arguments to propagation API
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/context/propagation/HttpTextFormat.ts
  packages/opentelemetry-api/src/context/propagation/NoopHttpTextFormat.ts
  packages/opentelemetry-api/src/context/propagation/getter.ts
  packages/opentelemetry-api/src/context/propagation/setter.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-core/src/context/propagation/B3Format.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/src/context/propagation/composite.ts
  packages/opentelemetry-core/test/context/B3Format.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-core/test/context/composite.test.ts
  packages/opentelemetry-plugin-grpc/src/grpc.ts
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTraceFormat.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTraceFormat.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: API, enhancement, nonconforming

#837 Simplify SDK registration
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-node/package.json
  packages/opentelemetry-node/src/NodeTracerProvider.ts
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/src/types.ts
  packages/opentelemetry-web/src/WebTracerProvider.ts
  packages/opentelemetry-web/test/registration.test.ts
Labels: Merge:LGTM, enhancement

#839 Rename api init methods to set
  examples/basic-tracer-node/index.js
  examples/basic-tracer-node/multi_exporter.js
  examples/dns/tracer.js
  examples/express/tracer.js
  examples/grpc/tracer.js
  examples/grpc_dynamic_codegen/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/ioredis/tracer.js
  examples/mysql/tracer.js
  examples/opentracing-shim/client.js
  examples/opentracing-shim/server.js
  examples/postgres/tracer.js
  examples/redis/tracer.js
  examples/stackdriver-trace/index.js
  getting-started/README.md
  getting-started/traced-example/tracing.js
  getting-started/ts-example/README.md
  getting-started/ts-example/tracing.ts
  packages/opentelemetry-api/README.md
  packages/opentelemetry-api/src/api/context.ts
  packages/opentelemetry-api/src/api/metrics.ts
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/api/trace.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-node/README.md
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-plugin-document-load/test/documentLoad.test.ts
  packages/opentelemetry-plugin-express/test/express.test.ts
  packages/opentelemetry-plugin-grpc/test/grpc.test.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
  packages/opentelemetry-plugin-ioredis/test/ioredis.test.ts
  packages/opentelemetry-plugin-mongodb/test/mongodb.test.ts
  packages/opentelemetry-plugin-mysql/test/mysql.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/pg-pool.test.ts
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/test/pg.test.ts
  packages/opentelemetry-plugin-redis/test/redis.test.ts
  packages/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
  packages/opentelemetry-plugin-user-interaction/test/userInteraction.test.ts
  packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
  packages/opentelemetry-web/test/registration.test.ts
Labels: API, Merge:LGTM

#625 feat: introduce ended property on Span
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/exporter.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/export/ReadableSpan.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: enhancement, waiting-for-spec

#848 chore: update examples to use register
  examples/basic-tracer-node/index.js
  examples/basic-tracer-node/multi_exporter.js
  examples/dns/tracer.js
  examples/express/tracer.js
  examples/grpc/tracer.js
  examples/grpc_dynamic_codegen/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/ioredis/tracer.js
  examples/mysql/tracer.js
  examples/postgres/tracer.js
  examples/redis/tracer.js
  examples/stackdriver-trace/index.js
  getting-started/README.md
  getting-started/traced-example/tracing.js
  getting-started/ts-example/README.md
  getting-started/ts-example/tracing.ts
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-node/README.md
  packages/opentelemetry-tracing/README.md
Labels: Merge:LGTM

#843 export resource to exporters
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-collector/src/CollectorExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/sendSpans.ts
  packages/opentelemetry-exporter-collector/src/platform/node/sendSpans.ts
  packages/opentelemetry-exporter-collector/src/transform.ts
  packages/opentelemetry-exporter-collector/test/common/transform.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/package.json
  packages/opentelemetry-exporter-stackdriver-trace/src/transform.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-exporter-zipkin/src/transform.ts
  packages/opentelemetry-exporter-zipkin/test/transform.test.ts
Labels: enhancement

#856 fix: change loglevel for beta
  packages/opentelemetry-core/src/common/ConsoleLogger.ts
  packages/opentelemetry-core/test/common/ConsoleLogger.test.ts
  packages/opentelemetry-metrics/src/types.ts
  packages/opentelemetry-tracing/src/config.ts
Labels: Merge:LGTM, enhancement, size/XS

#858 chore: update out-of-date dependencies
  packages/opentelemetry-api/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
Labels: Merge:LGTM

#857 Update core README with Built-in Implementations
  packages/opentelemetry-core/README.md
Labels: document

#859 chore: remove stackdriver trace exporter
  .circleci/config.yml
  README.md
  examples/stackdriver-trace/.gitignore
  examples/stackdriver-trace/README.md
  examples/stackdriver-trace/images/trace.png
  examples/stackdriver-trace/index.js
  examples/stackdriver-trace/package.json
  packages/opentelemetry-exporter-stackdriver-trace/.npmignore
  packages/opentelemetry-exporter-stackdriver-trace/LICENSE
  packages/opentelemetry-exporter-stackdriver-trace/README.md
  packages/opentelemetry-exporter-stackdriver-trace/package.json
  packages/opentelemetry-exporter-stackdriver-trace/src/external-types.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/index.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/trace.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/transform.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/types.ts
  packages/opentelemetry-exporter-stackdriver-trace/src/version.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/exporter.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/test/transform.test.ts
  packages/opentelemetry-exporter-stackdriver-trace/tsconfig.json
  packages/opentelemetry-exporter-stackdriver-trace/tslint.json
Labels: Merge:LGTM

#855 Update API docs for beta
  packages/opentelemetry-api/README.md
Labels: document

#881 fix: @opentelemetry/metrics fails to run due to bad import
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/export/NoopExporter.ts
Labels: bug

#880 Do not multiwrap pool queries
  packages/opentelemetry-plugin-mysql/src/mysql.ts
Labels: bug

#873 Remove unnecessary `this` overwrite in stack context manager
  packages/opentelemetry-web/src/StackContextManager.ts
Labels: bug

#884 chore: fixing main package.json version
  package.json
Labels: bug, size/XS

#875 chore: update module names and fix typo
  packages/opentelemetry-api/README.md
  packages/opentelemetry-core/README.md
  packages/opentelemetry-exporter-prometheus/README.md
  packages/opentelemetry-node/README.md
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-web/README.md
Labels: Merge:LGTM

#900 chore: update reference URL in enums.ts
  packages/opentelemetry-plugin-redis/src/enums.ts
Labels: size/XS

#889 feat: start a root span with spanOptions.parent = null
  packages/opentelemetry-api/src/trace/SpanOptions.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: Merge:LGTM, enhancement

#906 chore: fixing documentation for web tracer provider, fixing examples …
  examples/tracer-web/examples/document-load/index.js
  examples/tracer-web/examples/xml-http-request/index.js
  packages/opentelemetry-context-base/package.json
  packages/opentelemetry-core/src/context/context.ts
  packages/opentelemetry-plugin-document-load/src/documentLoad.ts
  packages/opentelemetry-plugin-user-interaction/README.md
  packages/opentelemetry-plugin-user-interaction/src/userInteraction.ts
  packages/opentelemetry-web/README.md
  packages/opentelemetry-web/src/WebTracerProvider.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
Labels: Target:Browser, bug, document, size/L

#896 Do not export empty span lists
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: enhancement

#904 fix: add type checking in propagators
  packages/opentelemetry-core/src/context/propagation/B3Propagator.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/test/context/B3Propagator.test.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
Labels: bug

#893 Metrics: Add lastUpdateTimestamp associated with point
  packages/opentelemetry-exporter-prometheus/src/prometheus.ts
  packages/opentelemetry-metrics/src/export/Aggregator.ts
  packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts
  packages/opentelemetry-metrics/src/export/types.ts
  packages/opentelemetry-metrics/test/Meter.test.ts
Labels: enhancement

#917 Updating out of date nyc packages
  packages/opentelemetry-api/package.json
  packages/opentelemetry-base/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-base/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-dns/package.json
  packages/opentelemetry-plugin-document-load/package.json
  packages/opentelemetry-plugin-express/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-plugin-mongodb/package.json
  packages/opentelemetry-plugin-mysql/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
  packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
  packages/opentelemetry-plugin-redis/package.json
  packages/opentelemetry-plugin-user-interaction/package.json
  packages/opentelemetry-plugin-xml-http-request/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: dependencies
