Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-01, with the labels that each got.

#1777 chore: remove fix option from husky lint
  package.json
Labels: express, internal

#1791 docs: fix readme MetricProvider -> MeterProvider
  packages/opentelemetry-exporter-collector/README.md
Labels: document, express

#1731 feat: creating one auto loader for instrumentation and old plugins
  examples/tracer-web/package.json
  lerna.json
  packages/opentelemetry-instrumentation/.gitignore
  packages/opentelemetry-instrumentation/README.md
  packages/opentelemetry-instrumentation/src/autoLoader.ts
  packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts
  packages/opentelemetry-instrumentation/src/index.ts
  packages/opentelemetry-instrumentation/src/platform/browser/index.ts
  packages/opentelemetry-instrumentation/src/platform/browser/old/autoLoader.ts
  packages/opentelemetry-instrumentation/src/platform/node/index.ts
  packages/opentelemetry-instrumentation/src/platform/node/old/PluginLoader.ts
  packages/opentelemetry-instrumentation/src/platform/node/old/autoLoader.ts
  packages/opentelemetry-instrumentation/src/platform/node/old/utils.ts
  packages/opentelemetry-instrumentation/src/types_internal.ts
  packages/opentelemetry-instrumentation/src/types_plugin_only.ts
  packages/opentelemetry-instrumentation/test/browser/autoLoader.test.ts
  packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
  packages/opentelemetry-instrumentation/test/common/autoLoaderUtils.test.ts
  packages/opentelemetry-instrumentation/test/node/BasePlugin.ts
  packages/opentelemetry-instrumentation/test/node/PluginLoader.test.ts
  packages/opentelemetry-instrumentation/test/node/autoLoader.test.ts
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-http-module/http-module.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-http-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-http-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-notsupported-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-notsupported-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-notsupported-module/simple-module.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-simple-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-simple-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-simple-module/simple-module.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-supported-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-supported-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/plugin-supported-module/simple-module.js
  packages/opentelemetry-instrumentation/test/node/node_modules/already-require-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/already-require-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/notsupported-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/notsupported-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/random-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/random-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/simple-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/simple-module/package.json
  packages/opentelemetry-instrumentation/test/node/node_modules/supported-module/index.js
  packages/opentelemetry-instrumentation/test/node/node_modules/supported-module/package.json
  packages/opentelemetry-instrumentation/test/node/utils.test.ts
Labels: Merge:LGTM, enhancement

#1790 chore: improve dev setup for windows
  .gitattributes
  package.json
  packages/opentelemetry-resource-detector-gcp/tsconfig.json
Labels: internal

#1785 Add CodeQL security scans
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#1796 Convert fetch plugin to instrumentation
  examples/tracer-web/examples/fetch/index.js
  examples/tracer-web/package.json
  packages/opentelemetry-instrumentation-fetch/.eslintignore
  packages/opentelemetry-instrumentation-fetch/.eslintrc.js
  packages/opentelemetry-instrumentation-fetch/.npmignore
  packages/opentelemetry-instrumentation-fetch/LICENSE
  packages/opentelemetry-instrumentation-fetch/README.md
  packages/opentelemetry-instrumentation-fetch/images/trace1.png
  packages/opentelemetry-instrumentation-fetch/images/trace2.png
  packages/opentelemetry-instrumentation-fetch/images/trace3.png
  packages/opentelemetry-instrumentation-fetch/karma.conf.js
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-fetch/src/enums/AttributeNames.ts
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/src/index.ts
  packages/opentelemetry-instrumentation-fetch/src/types.ts
  packages/opentelemetry-instrumentation-fetch/src/version.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
  packages/opentelemetry-instrumentation-fetch/test/index-webpack.ts
  packages/opentelemetry-instrumentation-fetch/tsconfig.json
  tsconfig.json
Labels: enhancement

#1807 perf(opentelemetry-node): plugin loader search required cache
  packages/opentelemetry-instrumentation/src/platform/node/old/PluginLoader.ts
  packages/opentelemetry-node/src/instrumentation/PluginLoader.ts
Labels: enhancement

#1784 fix(opentelemetry-core): fixed timeInputToHrTime when time is Date type
  packages/opentelemetry-core/src/common/time.ts
  packages/opentelemetry-core/test/common/time.test.ts
Labels: bug

#1803 chore: adding async function for safe execute in instrumentation
  packages/opentelemetry-instrumentation/src/utils.ts
  packages/opentelemetry-instrumentation/test/common/utils.test.ts
Labels: enhancement

#1813 fix(api): add public 'fields' function to api.propagator
  packages/opentelemetry-api/src/api/propagation.ts
  packages/opentelemetry-api/src/context/propagation/TextMapPropagator.ts
  packages/opentelemetry-api/test/api/api.test.ts
Labels: API, enhancement, release:required-for-ga

#1815 chore: change SpanOptions startTime to TimeInput
  packages/opentelemetry-api/src/trace/SpanOptions.ts
Labels: API, enhancement

#1822 chore: remove unused dependency
  packages/opentelemetry-exporter-collector/package.json
Labels: enhancement, express

#1800 chore: disable apis after use in tests
  packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-package.test.ts
  packages/opentelemetry-instrumentation-http/test/integrations/http-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/integrations/https-enable.test.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Labels: internal

#1789 feat(exporter-zipkin): per-span service name
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
Labels: enhancement

#1662 fix(plugin-fetch): check if PerformanceObserver exists
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/src/types.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Labels: enhancement

#1769 Allow zero/negative performance timings
  packages/opentelemetry-web/src/enums/PerformanceTimingNames.ts
  packages/opentelemetry-web/src/utils.ts
  packages/opentelemetry-web/test/utils.test.ts
Labels: enhancement

#1849 Add @johnbley to codeowners
  .github/CODEOWNERS
Labels: express

#1838 improv(instrumentation-http): supressInstrumentation when we get a request on ignoredPath [#1831]
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
  packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
Labels: enhancement

#1832 chore: prepare for branch rename
  .github/workflows/canary.yaml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  .github/workflows/w3c-integration-test.yml
Labels: internal

#1860 chore: fixing status code aligning it with proto
  packages/opentelemetry-api/src/trace/status.ts
  packages/opentelemetry-exporter-collector/src/transform.ts
  packages/opentelemetry-exporter-collector/src/types.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
Labels: enhancement

#1837 chore(http-propagation): reduce complexity of traceparent parsing
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
Labels: enhancement

#1865 Fix all links to point to main
  .github/ISSUE_TEMPLATE/request_for_instrumentation.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/canary.yaml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  .github/workflows/w3c-integration-test.yml
  CONTRIBUTING.md
  README.md
  RELEASING.md
  doc/exporter-guide.md
  doc/plugin-guide.md
  doc/processor-api.md
  examples/README.md
  examples/basic-tracer-node/README.md
  examples/collector-exporter-node/README.md
  examples/grpc-js/README.md
  examples/grpc/README.md
  examples/http/README.md
  examples/https/README.md
  examples/metrics/README.md
  examples/opentracing-shim/README.md
  examples/prometheus/README.md
  examples/tracer-web/README.md
  metapackages/plugins-node-core/README.md
  metapackages/plugins-web-core/README.md
  packages/opentelemetry-api-metrics/README.md
  packages/opentelemetry-api/README.md
  packages/opentelemetry-context-async-hooks/README.md
  packages/opentelemetry-context-base/README.md
  packages/opentelemetry-context-zone-peer-dep/README.md
  packages/opentelemetry-context-zone/README.md
  packages/opentelemetry-core/README.md
  packages/opentelemetry-exporter-collector-grpc/README.md
  packages/opentelemetry-exporter-collector-grpc/submodule.md
  packages/opentelemetry-exporter-collector-proto/README.md
  packages/opentelemetry-exporter-collector-proto/submodule.md
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-jaeger/README.md
  packages/opentelemetry-exporter-prometheus/README.md
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-grpc-utils/README.md
  packages/opentelemetry-instrumentation-fetch/README.md
  packages/opentelemetry-instrumentation-grpc/README.md
  packages/opentelemetry-instrumentation-http/README.md
  packages/opentelemetry-instrumentation-xml-http-request/README.md
  packages/opentelemetry-instrumentation/README.md
  packages/opentelemetry-metrics/README.md
  packages/opentelemetry-node/README.md
  packages/opentelemetry-plugin-grpc-js/README.md
  packages/opentelemetry-plugin-grpc/README.md
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-https/README.md
  packages/opentelemetry-resource-detector-aws/README.md
  packages/opentelemetry-resource-detector-gcp/README.md
  packages/opentelemetry-resources/README.md
  packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-semantic-conventions/README.md
  packages/opentelemetry-shim-opentracing/README.md
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-web/README.md
Labels: document, express

#1869 Add info that the project only works with Node.js
  packages/opentelemetry-exporter-jaeger/README.md
Labels: document

#1866 chore: remove all gitter links and replace with dicussions
  CONTRIBUTING.md
  README.md
  metapackages/plugins-node-core/README.md
  metapackages/plugins-web-core/README.md
  packages/opentelemetry-api-metrics/README.md
  packages/opentelemetry-api/README.md
  packages/opentelemetry-context-async-hooks/README.md
  packages/opentelemetry-context-base/README.md
  packages/opentelemetry-context-zone-peer-dep/README.md
  packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts
  packages/opentelemetry-context-zone/README.md
  packages/opentelemetry-core/README.md
  packages/opentelemetry-exporter-collector-grpc/README.md
  packages/opentelemetry-exporter-collector-proto/README.md
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-jaeger/README.md
  packages/opentelemetry-exporter-prometheus/README.md
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-grpc-utils/README.md
  packages/opentelemetry-instrumentation-fetch/README.md
  packages/opentelemetry-instrumentation-grpc/README.md
  packages/opentelemetry-instrumentation-http/README.md
  packages/opentelemetry-instrumentation-http/src/types.ts
  packages/opentelemetry-instrumentation-xml-http-request/README.md
  packages/opentelemetry-instrumentation/README.md
  packages/opentelemetry-metrics/README.md
  packages/opentelemetry-node/README.md
  packages/opentelemetry-plugin-grpc-js/README.md
  packages/opentelemetry-plugin-grpc/README.md
  packages/opentelemetry-plugin-http/README.md
  packages/opentelemetry-plugin-http/src/types.ts
  packages/opentelemetry-plugin-https/README.md
  packages/opentelemetry-propagator-b3/README.md
  packages/opentelemetry-resource-detector-aws/README.md
  packages/opentelemetry-resource-detector-gcp/README.md
  packages/opentelemetry-resources/README.md
  packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-semantic-conventions/README.md
  packages/opentelemetry-shim-opentracing/README.md
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-web/README.md
Labels: document

#1864 chore: export API singleton types
  packages/opentelemetry-api/src/index.ts
Labels: document

#1868 fix(instrumentation-fetch): perf observer bugs
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Labels: bug

#1851 chore: require value in setAttribute
  packages/opentelemetry-api/src/trace/span.ts
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-web/src/utils.ts
Labels: API, breaking, enhancement, size/S

#1867 docs(exporter-collector): document breaking change in README
  README.md
Labels: document
