Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-12, with the labels that each got.

#2588 feat: spec compliant metric creation and sync instruments
  .github/workflows/peer-api.yaml
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Metric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts
Labels: breaking

#2647 chore: update opentelemetry dependencies to latest versions
  examples/grpc-js/package.json
  examples/grpc/package.json
Labels: document

#2651 docs: fix links to the context document
  packages/opentelemetry-context-async-hooks/README.md
  packages/opentelemetry-sdk-trace-node/README.md
Labels: document

#2652 Update nock
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  experimental/packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-semantic-conventions/package.json
Labels: internal

#2650 fix: clientMethodTrace missing original properties
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
  experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
Labels: bug

#2556 chore: add esm2015 entry for web apps aiming at modern browsers
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-api-metrics/tsconfig.all.json
  experimental/packages/opentelemetry-api-metrics/tsconfig.esm2015.json
  experimental/packages/opentelemetry-api-metrics/tsconfig.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.all.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.esm2015.json
  experimental/packages/opentelemetry-exporter-trace-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-trace-otlp-http/tsconfig.all.json
  experimental/packages/opentelemetry-exporter-trace-otlp-http/tsconfig.esm2015.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/tsconfig.all.json
  experimental/packages/opentelemetry-instrumentation-fetch/tsconfig.esm2015.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/tsconfig.all.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/tsconfig.esm2015.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-instrumentation/tsconfig.all.json
  experimental/packages/opentelemetry-instrumentation/tsconfig.esm2015.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/tsconfig.all.json
  experimental/packages/opentelemetry-sdk-metrics-base/tsconfig.esm2015.json
  experimental/tsconfig.esm.json
  experimental/tsconfig.json
  package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone-peer-dep/tsconfig.all.json
  packages/opentelemetry-context-zone-peer-dep/tsconfig.esm2015.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-context-zone/tsconfig.all.json
  packages/opentelemetry-context-zone/tsconfig.esm2015.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/tsconfig.all.json
  packages/opentelemetry-core/tsconfig.esm2015.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-exporter-zipkin/tsconfig.all.json
  packages/opentelemetry-exporter-zipkin/tsconfig.esm2015.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-b3/tsconfig.all.json
  packages/opentelemetry-propagator-b3/tsconfig.esm2015.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-resources/tsconfig.all.json
  packages/opentelemetry-resources/tsconfig.esm2015.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-base/tsconfig.all.json
  packages/opentelemetry-sdk-trace-base/tsconfig.esm2015.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-sdk-trace-web/tsconfig.all.json
  packages/opentelemetry-sdk-trace-web/tsconfig.esm2015.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-semantic-conventions/tsconfig.all.json
  packages/opentelemetry-semantic-conventions/tsconfig.esm2015.json
  tsconfig.base.esm2015.json
  tsconfig.esm.json
  tsconfig.json
Labels: enhancement

#2657 chore: add markdown link checks
  .github/workflows/markdown-lint.config.json
  .github/workflows/markdown-lint.yml
  README.md
  doc/processor-api.md
  examples/metrics/README.md
  examples/otlp-exporter-node/README.md
  examples/prometheus/README.md
  experimental/packages/opentelemetry-api-metrics/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/README.md
  experimental/packages/opentelemetry-exporter-prometheus/README.md
  experimental/packages/opentelemetry-exporter-trace-otlp-grpc/README.md
  experimental/packages/opentelemetry-exporter-trace-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-trace-otlp-proto/README.md
  experimental/packages/opentelemetry-instrumentation-fetch/README.md
  experimental/packages/opentelemetry-instrumentation-grpc/README.md
  experimental/packages/opentelemetry-instrumentation-http/README.md
  experimental/packages/opentelemetry-instrumentation-xml-http-request/README.md
  experimental/packages/opentelemetry-instrumentation/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/README.md
  experimental/packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-context-async-hooks/README.md
  packages/opentelemetry-context-zone-peer-dep/README.md
  packages/opentelemetry-context-zone/README.md
  packages/opentelemetry-core/README.md
  packages/opentelemetry-exporter-jaeger/README.md
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-propagator-b3/README.md
  packages/opentelemetry-propagator-jaeger/README.md
  packages/opentelemetry-resources/README.md
  packages/opentelemetry-sdk-trace-base/README.md
  packages/opentelemetry-sdk-trace-node/README.md
  packages/opentelemetry-sdk-trace-web/README.md
  packages/opentelemetry-semantic-conventions/README.md
  packages/opentelemetry-shim-opentracing/README.md
Labels: internal

#2658 Update metrics example
  experimental/packages/opentelemetry-sdk-metrics-base/examples/.eslintrc.json
  experimental/packages/opentelemetry-sdk-metrics-base/examples/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer.js
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer.png
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer_batch.png
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer_batch2.png
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/package.json
Labels: document

#2684 chore: remove @obecny as maintainer
  README.md
  renovate.json
Labels: internal

#2683 chore: start a style guide
  style.md
Labels: internal

#2689 fix: remove window and document dependencies in web packages
  experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
  packages/opentelemetry-sdk-trace-web/src/utils.ts
  packages/opentelemetry-sdk-trace-web/test/utils.test.ts
Labels: bug

#2688 docs: update typedoc config
  package.json
  tsconfig.json
Labels: document

#2679 fix: span events count limit when set to 0
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: bug

#2673 feat(@opentelemetry/propagator-jaeger): support custom baggage prefix
  packages/opentelemetry-propagator-jaeger/src/JaegerPropagator.ts
  packages/opentelemetry-propagator-jaeger/src/types.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerPropagator.test.ts
Labels: enhancement

#2641 feat(sdk-metrics-base): bootstrap metrics exemplars
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/AlignedHistogramBucketExemplarReservoir.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/AlwaysSampleExemplarFilter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/Exemplar.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/ExemplarFilter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/ExemplarReservoir.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/NeverSampleExemplarFilter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/SimpleFixedSizeExemplarReservoir.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/WithTraceExemplarFilter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/exemplar/index.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/ExemplarFilter.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/ExemplarReservoir.test.ts
Labels: enhancement

#2669 chore: checks links in typedoc html
  .github/workflows/lint.yml
  .github/workflows/markdown-lint.config.json
  .github/workflows/markdown-lint.yml
  README.md
  package.json
Labels: internal

#2687 feat(api-metrics): remove observable types
  experimental/packages/opentelemetry-api-metrics/src/NoopMeter.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Metric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts
Labels: enhancement

#2693 chore: retry link checks on code 429 with 'retry-after' header
  package.json
Labels: internal
