Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-02, with the labels that each got.

#1896 chore: do not check in lockfiles but cache them
  .github/workflows/canary.yaml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  .github/workflows/w3c-integration-test.yml
  .gitignore
  backwards-compatability/node10/package-lock.json
  backwards-compatability/node12/package-lock.json
  backwards-compatability/node8/package-lock.json
  integration-tests/propagation-validation-server/package-lock.json
  packages/opentelemetry-api-metrics/package-lock.json
  packages/opentelemetry-api/package-lock.json
  packages/opentelemetry-context-async-hooks/package-lock.json
  packages/opentelemetry-context-base/package-lock.json
  packages/opentelemetry-context-zone-peer-dep/package-lock.json
  packages/opentelemetry-context-zone/package-lock.json
  packages/opentelemetry-core/package-lock.json
  packages/opentelemetry-exporter-collector-grpc/package-lock.json
  packages/opentelemetry-exporter-collector-proto/package-lock.json
  packages/opentelemetry-exporter-collector/package-lock.json
  packages/opentelemetry-exporter-jaeger/package-lock.json
  packages/opentelemetry-exporter-prometheus/package-lock.json
  packages/opentelemetry-exporter-zipkin/package-lock.json
  packages/opentelemetry-grpc-utils/package-lock.json
  packages/opentelemetry-instrumentation-fetch/package-lock.json
  packages/opentelemetry-instrumentation-grpc/package-lock.json
  packages/opentelemetry-instrumentation-http/package-lock.json
  packages/opentelemetry-instrumentation-xml-http-request/package-lock.json
  packages/opentelemetry-instrumentation/package-lock.json
  packages/opentelemetry-metrics/package-lock.json
  packages/opentelemetry-node/package-lock.json
  packages/opentelemetry-plugin-grpc-js/package-lock.json
  packages/opentelemetry-plugin-grpc/package-lock.json
  packages/opentelemetry-plugin-http/package-lock.json
  packages/opentelemetry-plugin-https/package-lock.json
  packages/opentelemetry-propagator-b3/package-lock.json
  packages/opentelemetry-resource-detector-aws/package-lock.json
  packages/opentelemetry-resource-detector-gcp/package-lock.json
  packages/opentelemetry-resources/package-lock.json
  packages/opentelemetry-sdk-node/package-lock.json
  packages/opentelemetry-semantic-conventions/package-lock.json
  packages/opentelemetry-shim-opentracing/package-lock.json
  packages/opentelemetry-tracing/package-lock.json
  packages/opentelemetry-web/package-lock.json
  packages/template/package-lock.json
Labels: internal

#1876 refactor!: specification compliant baggage
  packages/opentelemetry-api/src/baggage/Baggage.ts
  packages/opentelemetry-api/src/baggage/Entry.ts
  packages/opentelemetry-api/src/baggage/index.ts
  packages/opentelemetry-api/src/baggage/internal/baggage.ts
  packages/opentelemetry-api/src/baggage/internal/symbol.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/test/baggage/Baggage.test.ts
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggage.ts
  packages/opentelemetry-core/test/baggage/HttpBaggage.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: API, breaking, enhancement

#1901 doc: correct tracer docs
  packages/opentelemetry-api/src/trace/tracer.ts
Labels: document, express

#1879 feat(prometheus): add `getMetricsRequestHandler`-method to Prometheus
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
Labels: enhancement

#1913 chore: no verify access on publish
  .github/workflows/canary.yaml
Labels: express, internal

#1904 chore: fix upgrade guideline
  README.md
Labels: document, express

#1900 chore: remove NoRecordingSpan
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/NoRecordingSpan.ts
  packages/opentelemetry-core/test/trace/NoRecordingSpan.test.ts
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: breaking

#1883 feat: add support to forward args in context.with
  packages/opentelemetry-api/src/api/context.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/src/AsyncLocalStorageContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
  packages/opentelemetry-context-base/src/NoopContextManager.ts
  packages/opentelemetry-context-base/src/types.ts
  packages/opentelemetry-context-base/test/NoopContextManager.test.ts
  packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts
  packages/opentelemetry-context-zone-peer-dep/test/ZoneContextManager.test.ts
  packages/opentelemetry-tracing/test/export/TestStackContextManager.ts
  packages/opentelemetry-web/src/StackContextManager.ts
  packages/opentelemetry-web/test/StackContextManager.test.ts
Labels: enhancement

#1908 chore: remove config from BasicTracerProvider#getTracer
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
Labels: breaking

#1920 chore: adding compatibility matrix for core and contrib versions
  README.md
Labels: enhancement, express

#1899 chore: create NoopSpan instead reusing NOOP_SPAN
  packages/opentelemetry-api/src/context/context.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/trace/NoopSpan.ts
  packages/opentelemetry-api/src/trace/NoopTracer.ts
  packages/opentelemetry-api/test/api/api.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-span.test.ts
  packages/opentelemetry-api/test/noop-implementations/noop-tracer.test.ts
  packages/opentelemetry-api/test/proxy-implementations/proxy-tracer.test.ts
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-disable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-disable.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-plugin-http/src/http.ts
  packages/opentelemetry-plugin-http/test/functionals/http-disable.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: API, breaking

#1880 feat(diag-logger): introduce a new global level api.diag for internal diagnostic logging
  .gitignore
  benchmark/tracer.js
  examples/collector-exporter-node/metrics.js
  examples/collector-exporter-node/tracing.js
  examples/metrics/metrics/observer.js
  examples/tracer-web/examples/metrics/index.js
  packages/opentelemetry-api/src/api/diag.ts
  packages/opentelemetry-api/src/api/global-utils.ts
  packages/opentelemetry-api/src/common/Logger.ts
  packages/opentelemetry-api/src/diag/consoleLogger.ts
  packages/opentelemetry-api/src/diag/logLevel.ts
  packages/opentelemetry-api/src/diag/logger.ts
  packages/opentelemetry-api/src/index.ts
  packages/opentelemetry-api/src/trace/NoopLogger.ts
  packages/opentelemetry-api/test/diag/consoleLogger.test.ts
  packages/opentelemetry-api/test/diag/logLevel.test.ts
  packages/opentelemetry-api/test/diag/logger.test.ts
  packages/opentelemetry-core/src/common/ConsoleLogger.ts
  packages/opentelemetry-core/src/common/logging-error-handler.ts
  packages/opentelemetry-core/src/common/types.ts
Labels: API, enhancement

#1918 chore: batch processor, aligning with latest spec changes for environments variables
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/types.ts
  packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
Labels: enhancement

#1857 feat: add prometheus exporter host and port env vars
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-prometheus/src/export/types.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
Labels: enhancement

#1941 fix: update readme upgrade guidelines version setting
  README.md
Labels: express

#1937 fix: isolate binding EventEmitter
  packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/src/AsyncLocalStorageContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: bug

#1960 chore: updating current state of compatibility matrix
  README.md
Labels: internal

#1938 fix(exporter-collector): wrong data type for numbers
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
  packages/opentelemetry-exporter-collector/src/transform.ts
  packages/opentelemetry-exporter-collector/test/common/transform.test.ts
  packages/opentelemetry-exporter-collector/test/helper.ts
Labels: bug
