Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-04, with the labels that each got.

#2063 chore: update API dependency to 1.0.0-rc.0
  examples/basic-tracer-node/package.json
  examples/collector-exporter-node/package.json
  examples/grpc-js/package.json
  examples/grpc/package.json
  examples/http/package.json
  examples/https/package.json
  examples/tracer-web/package.json
  integration-tests/propagation-validation-server/package.json
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-grpc-utils/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-grpc-js/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: breaking

#2074 chore: peer depend on API
  .github/workflows/peer-api.yaml
  integration-tests/propagation-validation-server/package.json
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-grpc-utils/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-plugin-grpc-js/package.json
  packages/opentelemetry-plugin-grpc/package.json
  packages/opentelemetry-plugin-http/package.json
  packages/opentelemetry-plugin-https/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
  scripts/peer-api-check.js
Labels: breaking

#1986 fix(propagator-jaeger): zero pad extracted trace id to 32 characters
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
Labels: bug

#2051 Add opentelemetry.io docs
  website_docs/_index.md
  website_docs/getting_started/_index.md
  website_docs/getting_started/browser.md
  website_docs/getting_started/nodejs.md
  website_docs/instrumentation.md
  website_docs/instrumentation_examples.md
Labels: document

#2086 fix: exception.type should always be a string
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: bug

#2080 fix: do not inject invalid span context
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
Labels: bug

#2082 chore: do not inject span context when instrumentation is suppressed
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggage.ts
  packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts
  packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
  packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts
  packages/opentelemetry-propagator-b3/src/B3Propagator.ts
  packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts
  packages/opentelemetry-propagator-b3/test/B3MultiPropagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3SinglePropagator.test.ts
  packages/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
Labels: bug

#2076 fix: await http response in AWS EKS detector
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsEksDetector.test.ts
Labels: bug

#2061 chore: adding info to debug whenever headers are being skipped due to cors policy
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Labels: enhancement

#2088 fix: correct removeAllListeners in case no event is passed
  packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: bug

#2043 chore: avoid unneeded context.with in http instrumentation
  packages/opentelemetry-instrumentation-http/src/http.ts
Labels: enhancement

#2073 chore: pin own deps
  backwards-compatability/node10/package.json
  backwards-compatability/node12/package.json
  backwards-compatability/node8/package.json
  integration-tests/propagation-validation-server/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: internal

#2094 chore: fixing readme info
  README.md
Labels: document

#2098 chore(env): update default value for span's attributes/links/events count #1675
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: breaking

#2092 Migrate exporter-collector-grpc to grpc-js
  examples/grpc-js/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-grpc/src/types.ts
  packages/opentelemetry-exporter-collector-grpc/src/util.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
Labels: enhancement

#2050 chore: adding interceptor for getting headers before each request
  examples/tracer-web/examples/zipkin/index.js
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
  packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
  packages/opentelemetry-exporter-zipkin/src/types.ts
  packages/opentelemetry-exporter-zipkin/src/utils.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/browser/zipkin.test.ts
  packages/opentelemetry-exporter-zipkin/test/common/zipkin.test.ts
Labels: enhancement

#2097 feat(zipkin): allow to configure url via environment #1675
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/browser/zipkin.test.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
Labels: enhancement

#2105 fix: don't use spanId from invalid parent
  packages/opentelemetry-instrumentation-http/test/utils/DummyPropagation.ts
  packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: bug

#2115 feat: upgrade semantic conventions to v1.2.0 of spec
  packages/opentelemetry-semantic-conventions/src/resource/ResourceAttributes.ts
  packages/opentelemetry-semantic-conventions/src/trace/SemanticAttributes.ts
  scripts/semconv/generate.sh
  scripts/semconv/templates/SemanticAttributes.ts.j2
Labels: enhancement

#2111 feat: handle OTEL_TRACES_SAMPLER env var
  README.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/src/utils/sampling.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-tracing/README.md
  packages/opentelemetry-tracing/src/config.ts
  packages/opentelemetry-tracing/src/utility.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
  packages/opentelemetry-tracing/test/config.test.ts
  packages/opentelemetry-tracing/test/export/ConsoleSpanExporter.test.ts
Labels: breaking

#2120 fix(instrumentation): support multiple module definitions with different versions
  packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
Labels: bug

#2121 feat: ensure the label names are sanitised
  packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts
  packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
Labels: bug

#2135 fix: add isEnabled to InstrumentationBase
  packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
Labels: enhancement

#2112 feat: add ESM builds for packages used in browser
  CONTRIBUTING.md
  package.json
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-api-metrics/tsconfig.esm.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone-peer-dep/tsconfig.esm.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-context-zone/tsconfig.esm.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/tsconfig.esm.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-collector/tsconfig.esm.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-exporter-zipkin/tsconfig.esm.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-fetch/tsconfig.esm.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation-xml-http-request/tsconfig.esm.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-instrumentation/tsconfig.esm.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/MeterProvider.ts
  packages/opentelemetry-metrics/tsconfig.esm.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-b3/tsconfig.esm.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-propagator-jaeger/tsconfig.esm.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-resources/tsconfig.esm.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-semantic-conventions/tsconfig.esm.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/tsconfig.esm.json
  packages/opentelemetry-web/package.json
  packages/opentelemetry-web/tsconfig.esm.json
  packages/template/package.json
  packages/template/tsconfig.esm.json
  tsconfig.base.esm.json
  tsconfig.esm.json
Labels: internal

#2127 chore: prefer use of global TracerProvider/MeterProvider
  examples/grpc-js/tracer.js
  examples/grpc/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/opentracing-shim/shim.js
  examples/tracer-web/examples/fetch/index.js
  examples/tracer-web/examples/xml-http-request/index.js
  getting-started/README.md
  getting-started/traced-example/tracing.js
  getting-started/ts-example/README.md
  getting-started/ts-example/traced-example/tracing.ts
  packages/opentelemetry-instrumentation-fetch/README.md
  packages/opentelemetry-instrumentation-grpc/README.md
  packages/opentelemetry-instrumentation-http/README.md
  packages/opentelemetry-instrumentation-xml-http-request/README.md
  packages/opentelemetry-instrumentation/README.md
  packages/opentelemetry-node/README.md
  packages/opentelemetry-sdk-node/src/sdk.ts
  packages/opentelemetry-web/README.md
Labels: document

#2134 feat(instrumentation-xhr): add applyCustomAttributesOnSpan hook
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Labels: enhancement

#2165 [sampler] treat invalid SpanContext as no SpanContext
  packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts
  packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts
Labels: bug, spec-v1

#2168 chore: update feature status in readme
  README.md
Labels: document

#2155 chore: move tracecontext propagator into trace
  packages/opentelemetry-core/src/context/propagation/types.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/propagation/composite.ts
  packages/opentelemetry-core/src/trace/HttpTraceContext.ts
  packages/opentelemetry-core/test/propagation/composite.test.ts
  packages/opentelemetry-core/test/trace/HttpTraceContext.test.ts
Labels: internal

#2149 chore: adding sufix propagator to http baggage and http trace context
  README.md
  benchmark/README.md
  benchmark/propagator.js
  integration-tests/propagation-validation-server/validation-server.js
  packages/opentelemetry-core/README.md
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggagePropagator.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/HttpTraceContextPropagator.ts
  packages/opentelemetry-core/test/baggage/HttpBaggagePropagator.test.ts
  packages/opentelemetry-core/test/propagation/composite.test.ts
  packages/opentelemetry-core/test/trace/HttpTraceContextPropagator.test.ts
  packages/opentelemetry-instrumentation-grpc/test/helper.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
Labels: breaking
