Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-05, with the labels that each got.

#2171 fix: move initialization of const above first use #2170
  packages/opentelemetry-tracing/src/config.ts
Labels: bug

#2167 semantic-conventions: include built esm files in package
  packages/opentelemetry-semantic-conventions/package.json
Labels: enhancement, express

#2180 fix docs typo
  packages/opentelemetry-node/README.md
Labels: document

#2130 chore: url validation & README to prevent gRPC footguns.
  packages/opentelemetry-exporter-collector-grpc/README.md
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-grpc/src/util.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
Labels: enhancement

#2179 chore(grpc-instrumentation): fix grpc example #2160
  packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
Labels: bug

#2148 chore: renaming jaeger http trace propagator to jaeger propagator
  README.md
  packages/opentelemetry-node/src/NodeTracerProvider.ts
  packages/opentelemetry-propagator-jaeger/README.md
  packages/opentelemetry-propagator-jaeger/src/JaegerPropagator.ts
  packages/opentelemetry-propagator-jaeger/src/index.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerPropagator.test.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: breaking

#2117 feat(exporter-collector): support config from env #2099
  examples/collector-exporter-node/docker/collector-config.yaml
  examples/collector-exporter-node/docker/docker-compose.yaml
  packages/opentelemetry-core/src/baggage/constants.ts
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggagePropagator.ts
  packages/opentelemetry-core/src/baggage/utils.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/baggage/HttpBaggagePropagator.test.ts
  packages/opentelemetry-exporter-collector-grpc/README.md
  packages/opentelemetry-exporter-collector-grpc/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/README.md
  packages/opentelemetry-exporter-collector-proto/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-proto/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporterBrowserBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/util.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
Labels: enhancement

#2100 feat(tracing): allow to configure exporter by environment #1676
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-tracing/src/export/NoopSpanProcessor.ts
  packages/opentelemetry-tracing/src/index.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
Labels: enhancement

#2190 feat: apply spec changes for `TraceParams`
  packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-sdk-node/src/sdk.ts
  packages/opentelemetry-sdk-node/src/types.ts
  packages/opentelemetry-tracing/src/Span.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/config.ts
  packages/opentelemetry-tracing/src/types.ts
  packages/opentelemetry-tracing/src/utility.ts
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/Span.test.ts
Labels: breaking

#2185 fix: use invalid parent for sampler when options.root
  packages/opentelemetry-tracing/src/Tracer.ts
Labels: bug

#2204 Remove GTS and prettier
  .github/workflows/lint.yml
  eslint.config.js
  package.json
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-jaeger/src/types.ts
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-metrics/src/Meter.ts
  packages/opentelemetry-metrics/src/MeterProvider.ts
  packages/opentelemetry-node/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-tracing/src/BasicTracerProvider.ts
  packages/opentelemetry-web/package.json
  packages/template/package.json
Labels: internal

#2214 chore: fixes after last changes to url
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-grpc/src/types.ts
  packages/opentelemetry-exporter-collector-grpc/src/util.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/certs/ca.crt
  packages/opentelemetry-exporter-collector-grpc/test/certs/ca.key
  packages/opentelemetry-exporter-collector-grpc/test/certs/client.crt
  packages/opentelemetry-exporter-collector-grpc/test/certs/client.csr
  packages/opentelemetry-exporter-collector-grpc/test/certs/client.key
  packages/opentelemetry-exporter-collector-grpc/test/certs/server.crt
  packages/opentelemetry-exporter-collector-grpc/test/certs/server.csr
  packages/opentelemetry-exporter-collector-grpc/test/certs/server.key
Labels: bug

#2202 Move suppress tracing context key to SDK
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggagePropagator.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/HttpTraceContextPropagator.ts
  packages/opentelemetry-core/src/trace/suppress-tracing.ts
  packages/opentelemetry-core/test/propagation/composite.test.ts
  packages/opentelemetry-core/test/trace/HttpTraceContextPropagator.test.ts
  packages/opentelemetry-core/tsconfig.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts
  packages/opentelemetry-propagator-b3/src/B3Propagator.ts
  packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts
  packages/opentelemetry-propagator-b3/test/B3MultiPropagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
  packages/opentelemetry-propagator-b3/test/B3SinglePropagator.test.ts
  packages/opentelemetry-propagator-b3/tsconfig.json
  packages/opentelemetry-propagator-jaeger/src/JaegerPropagator.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerPropagator.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
  packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: enhancement

#2219 fix(opentelemetry-sdk-node): move nock to dev dependencies
  packages/opentelemetry-sdk-node/package.json
Labels: internal

#2224 feat(opentelemetry-instrumentation): getConfig and setConfig
  packages/opentelemetry-instrumentation/src/instrumentation.ts
  packages/opentelemetry-instrumentation/src/types.ts
  packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
Labels: enhancement

#2234 chore: downgrade karma-webpack
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
  renovate.json
Labels: internal

#2230 chore: remove references to Noop classes from API
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-sdk-node/test/sdk.test.ts
  packages/opentelemetry-web/test/registration.test.ts
Labels: internal

#2229 chore: remove references to NOOP singletons
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-disable.test.ts
  packages/opentelemetry-instrumentation-http/test/functionals/https-disable.test.ts
  packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
  packages/opentelemetry-tracing/src/Tracer.ts
Labels: internal
