Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-08, with the labels that each got.

#2397 chore: change codeowners to point to team
  .github/CODEOWNERS
Labels: internal

#2390 chore: fix Lint warnings in api-metrics and context-zone-peer-dep
  packages/opentelemetry-api-metrics/src/NoopMeter.ts
  packages/opentelemetry-api-metrics/src/api/metrics.ts
  packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts
  packages/opentelemetry-context-zone-peer-dep/src/types.ts
Labels: internal

#2399 chore: update doc identifier names in readme
  packages/opentelemetry-resources/README.md
  packages/opentelemetry-semantic-conventions/README.md
Labels: document

#2402 chore: sort entries in tsconfig
  packages/opentelemetry-exporter-collector-grpc/tsconfig.json
  packages/opentelemetry-exporter-collector-proto/tsconfig.json
  packages/opentelemetry-exporter-collector/tsconfig.json
  packages/opentelemetry-exporter-jaeger/tsconfig.json
  packages/opentelemetry-exporter-zipkin/tsconfig.json
  packages/opentelemetry-instrumentation-fetch/tsconfig.json
  packages/opentelemetry-instrumentation-grpc/tsconfig.json
  packages/opentelemetry-instrumentation-http/tsconfig.json
  packages/opentelemetry-instrumentation-xml-http-request/tsconfig.json
  packages/opentelemetry-sdk-node/tsconfig.json
  packages/opentelemetry-sdk-trace-node/tsconfig.json
  packages/opentelemetry-sdk-trace-web/tsconfig.json
  packages/opentelemetry-shim-opentracing/tsconfig.json
  tsconfig.json
Labels: internal

#2396 fix: respect sampled flag in Span Processors, fix associated tests
  packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts
  packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/BatchSpanProcessorBase.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/SimpleSpanProcessor.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/TestRecordOnlySampler.ts
Labels: bug

#2392 refactor: move detectors to opentelemetry-js-contrib repo
  packages/opentelemetry-resource-detector-aws/.eslintignore
  packages/opentelemetry-resource-detector-aws/.eslintrc.js
  packages/opentelemetry-resource-detector-aws/.npmignore
  packages/opentelemetry-resource-detector-aws/LICENSE
  packages/opentelemetry-resource-detector-aws/README.md
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsBeanstalkDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsLambdaDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/index.ts
  packages/opentelemetry-resource-detector-aws/src/index.ts
  packages/opentelemetry-resource-detector-aws/src/version.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsBeanstalkDetector.test.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsEc2Detector.test.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsEcsDetector.test.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsEksDetector.test.ts
  packages/opentelemetry-resource-detector-aws/test/detectors/AwsLambdaDetector.test.ts
  packages/opentelemetry-resource-detector-aws/tsconfig.json
  packages/opentelemetry-resource-detector-gcp/.eslintignore
  packages/opentelemetry-resource-detector-gcp/.eslintrc.js
  packages/opentelemetry-resource-detector-gcp/.npmignore
  packages/opentelemetry-resource-detector-gcp/LICENSE
  packages/opentelemetry-resource-detector-gcp/README.md
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts
  packages/opentelemetry-resource-detector-gcp/src/detectors/index.ts
  packages/opentelemetry-resource-detector-gcp/src/index.ts
  packages/opentelemetry-resource-detector-gcp/src/version.ts
  packages/opentelemetry-resource-detector-gcp/test/detectors/GcpDetector.test.ts
  packages/opentelemetry-resource-detector-gcp/tsconfig.json
  packages/opentelemetry-sdk-node/tsconfig.json
  tsconfig.json
Labels: internal

#2400 Website docs update 0821
  website_docs/_index.md
  website_docs/exporters.md
  website_docs/getting_started/nodejs.md
  website_docs/instrumentation.md
Labels: document

#2336 feat: use Blob in sendBeacon to add application/json type
  packages/opentelemetry-exporter-collector/src/CollectorExporterBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporterBrowserBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/util.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorTraceExporter.test.ts
Labels: enhancement

#2405 chore: Fix lint warnings in core package
  packages/opentelemetry-core/src/baggage/propagation/HttpBaggagePropagator.ts
  packages/opentelemetry-core/src/baggage/utils.ts
  packages/opentelemetry-core/src/common/attributes.ts
  packages/opentelemetry-core/src/common/global-error-handler.ts
  packages/opentelemetry-core/src/common/time.ts
  packages/opentelemetry-core/src/common/types.ts
  packages/opentelemetry-core/src/propagation/composite.ts
  packages/opentelemetry-core/src/trace/HttpTraceContextPropagator.ts
  packages/opentelemetry-core/src/utils/wrap.ts
Labels: internal

#1775 fix(@opentelemetry/exporter-collector): remove fulfilled promises cor…
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorExporterNodeBase.test.ts
  packages/opentelemetry-exporter-collector-proto/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporterBrowserBase.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
Labels: enhancement

#2411 fix(instrumentation-fetch): `fetch(string, Request)` silently drops request body
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Labels: bug

#2416 chore: hoist dependencies to speed up ci
  .github/workflows/canary.yaml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  examples/basic-tracer-node/package.json
  examples/collector-exporter-node/package.json
  examples/grpc-js/package.json
  examples/grpc/package.json
  examples/http/package.json
  examples/https/package.json
  package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-sdk-trace-node/package.json
Labels: internal

#2425 chore(deps): remove shimmer from dependencies
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-sdk-trace-node/package.json
Labels: dependencies

#2418 feat(opentelemetry-sdk-trace-base): implemented option to limit length of values of attributes
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/src/config.ts
  packages/opentelemetry-sdk-trace-base/src/types.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: enhancement

#2297 eslint configuration for getting-started examples
  examples/.eslintrc.json
  getting-started/.eslintrc.js
  getting-started/example/app.js
  getting-started/monitored-example/app.js
  getting-started/monitored-example/monitoring.js
  getting-started/traced-example/app.js
  getting-started/traced-example/tracing.js
  getting-started/ts-example/.eslintrc
  getting-started/ts-example/example/app.ts
  getting-started/ts-example/monitored-example/app.ts
  getting-started/ts-example/monitored-example/monitoring.ts
  getting-started/ts-example/traced-example/app.ts
  getting-started/ts-example/traced-example/tracing.ts
  package.json
Labels: document

#2426 fix(opentelemetry-instrumentation-fetch): fixed override of headers
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Labels: bug

#2435 chore: simplify unit test cache
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
Labels: internal

#2437 docs(examples): updated examples readme links
  examples/README.md
Labels: document

#2429 fix!: remove 'Http' from W3C propagator names
  README.md
  benchmark/propagator.js
  integration-tests/propagation-validation-server/validation-server.js
  packages/opentelemetry-core/README.md
  packages/opentelemetry-core/src/baggage/propagation/W3CBaggagePropagator.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/W3CTraceContextPropagator.ts
  packages/opentelemetry-core/test/baggage/W3CBaggagePropagator.test.ts
  packages/opentelemetry-core/test/propagation/composite.test.ts
  packages/opentelemetry-core/test/trace/W3CTraceContextPropagator.test.ts
  packages/opentelemetry-instrumentation-grpc/test/helper.ts
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: breaking

#2431 chore: add release-please automation
  .github/workflows/release-please.yml
  .github/workflows/w3c-integration-test.yml
  .gitignore
  .release-please-manifest.json
  lerna.json
  package.json
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-api-metrics/src/version.ts
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-async-hooks/src/version.ts
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone-peer-dep/src/version.ts
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-context-zone/src/version.ts
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/src/version.ts
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-grpc/src/version.ts
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector-proto/src/version.ts
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-collector/src/version.ts
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-jaeger/src/version.ts
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-prometheus/src/version.ts
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-exporter-zipkin/src/version.ts
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-fetch/src/version.ts
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-grpc/src/version.ts
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-http/src/version.ts
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation-xml-http-request/src/version.ts
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-instrumentation/src/version.ts
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-b3/src/version.ts
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-propagator-jaeger/src/version.ts
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-resources/src/version.ts
  packages/opentelemetry-sdk-metrics-base/package.json
  packages/opentelemetry-sdk-metrics-base/src/version.ts
  packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-sdk-node/src/version.ts
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-base/src/version.ts
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-node/src/version.ts
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-sdk-trace-web/src/version.ts
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-semantic-conventions/src/version.ts
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-shim-opentracing/src/version.ts
  packages/template/package.json
  release-please-config.json
Labels: internal

#2438 feat: OTEL_EXPORTER_OTLP_ENDPOINT append version and signal
  packages/opentelemetry-exporter-collector-proto/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-proto/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-proto/src/util.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/README.md
  packages/opentelemetry-exporter-collector/src/index.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector/src/util.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/browser/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
Labels: enhancement
