Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-11, with the labels that each got.

#2529 feat(api-metrics): add schemaUrl to meter creations
  experimental/packages/opentelemetry-api-metrics/src/NoopMeterProvider.ts
  experimental/packages/opentelemetry-api-metrics/src/api/metrics.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts
  experimental/packages/opentelemetry-api-metrics/src/types/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/types.ts
  packages/opentelemetry-core/src/common/types.ts
Labels: breaking

#2563 feat(sdk-metrics-base): remove per-meter config on MeterProvider.getMeter
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/Meter.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts
Labels: enhancement

#2579 doc: Move upgrade propagator notes to correct section
  README.md
Labels: document

#2600 docs: fix URLs in README post-experimental move
  README.md
Labels: document

#2576 docs(instrumentation): update links in the Readme
  experimental/packages/opentelemetry-instrumentation-fetch/README.md
  experimental/packages/opentelemetry-instrumentation-grpc/README.md
  experimental/packages/opentelemetry-instrumentation-http/README.md
Labels: document, Merge:LGTM, size/S

#2584 fix: fixing compatibility versions for detectors
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Labels: bug

#2570 chore: adding selenium tests with browserstack
  .github/workflows/peer-api.yaml
  .github/workflows/unit-test.yml
  lerna.json
  selenium-tests/.gitignore
  selenium-tests/README.md
  selenium-tests/babel.config.js
  selenium-tests/example.env
  selenium-tests/nightwatch.conf.js
  selenium-tests/package.json
  selenium-tests/pages/fetch/index.html
  selenium-tests/pages/fetch/index.js
  selenium-tests/pages/helper.js
  selenium-tests/pages/tracing.js
  selenium-tests/pages/xhr/index.html
  selenium-tests/pages/xhr/index.js
  selenium-tests/scripts/local.runner.js
  selenium-tests/tests-helpers/constants.js
  selenium-tests/tests/fetch/fetch.js
  selenium-tests/tests/xhr/xhr.js
  selenium-tests/webpack.common.js
  selenium-tests/webpack.config.js
  selenium-tests/webpack.dev.js
  selenium-tests/webpack.production.js
Labels: internal

#2607 chore: update npm badge image links
  experimental/packages/opentelemetry-exporter-trace-otlp-grpc/README.md
  experimental/packages/opentelemetry-exporter-trace-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-trace-otlp-proto/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/README.md
  packages/opentelemetry-sdk-trace-base/README.md
  packages/opentelemetry-sdk-trace-node/README.md
  packages/opentelemetry-sdk-trace-web/README.md
Labels: internal

#2581 feat: lazy initialization of the gzip stream
  experimental/packages/opentelemetry-exporter-trace-otlp-http/src/platform/node/OTLPExporterNodeBase.ts
  experimental/packages/opentelemetry-exporter-trace-otlp-http/src/platform/node/util.ts
Labels: enhancement

#2610 fix: preventing double enable for instrumentation that has been already enabled
  experimental/packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts
  experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
Labels: bug

#2561 Use new canonical path to Getting Started
  README.md
Labels: document

#2404 chore: Fix lint warnings in instrumentation package
  experimental/packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts
  experimental/packages/opentelemetry-instrumentation/src/instrumentation.ts
  experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
  experimental/packages/opentelemetry-instrumentation/src/platform/node/types.ts
  experimental/packages/opentelemetry-instrumentation/src/types.ts
  experimental/packages/opentelemetry-instrumentation/src/utils.ts
  experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
Labels: internal

#2598 chore: Remove old metrics SDK
  experimental/packages/opentelemetry-sdk-metrics-base/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/src/BoundInstrument.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/CounterMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/HistogramMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Metric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/ObservableBaseMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/ObservableCounterMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/ObservableGaugeMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/ObservableUpDownCounterMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/UpDownCounterMetric.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Utils.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/ConsoleMetricExporter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/Controller.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/NoopExporter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/Processor.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/aggregators/Histogram.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/aggregators/LastValue.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/aggregators/Sum.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/aggregators/index.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/types.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/index.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/types.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/Meter.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/Processor.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/export/ConsoleMetricExporter.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/export/Controller.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/export/aggregators/Histogram.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/noop.test.ts
Labels: internal

#2623 chore: fix the compilation for typescript 4.4
  experimental/packages/opentelemetry-instrumentation-xml-http-request/src/types.ts
  tsconfig.base.json
Labels: internal

#2451 chore(sdk-trace-web): fix lint warnings
  packages/opentelemetry-sdk-trace-web/src/StackContextManager.ts
  packages/opentelemetry-sdk-trace-web/src/WebTracerProvider.ts
  packages/opentelemetry-sdk-trace-web/src/utils.ts
Labels: internal

#2629 chore: rename metrics packages to prevent lerna linking
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/tsconfig.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.esm.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/tsconfig.json
  experimental/packages/opentelemetry-exporter-prometheus/tsconfig.json
  experimental/packages/opentelemetry-instrumentation-grpc/tsconfig.json
  experimental/packages/opentelemetry-instrumentation/tsconfig.esm.json
  experimental/packages/opentelemetry-instrumentation/tsconfig.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/tsconfig.json
Labels: internal

#2569 feat(api-metrics): async instruments spec compliance
  examples/metrics/metrics/observer.js
  experimental/packages/opentelemetry-api-metrics/src/NoopMeter.ts
  experimental/packages/opentelemetry-api-metrics/src/index.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Metric.ts
  experimental/packages/opentelemetry-api-metrics/src/types/ObservableResult.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Observation.ts
Labels: breaking

#2638 chore: Update wip metrics references
  experimental/packages/opentelemetry-sdk-metrics-base/src/InstrumentDescriptor.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Instruments.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Measurement.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/state/MultiWritableMetricStorage.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/state/WritableMetricStorage.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/view/AttributesProcessor.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/view/Predicate.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/view/ViewRegistry.test.ts
Labels: internal
