Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-07, with the labels that each got.

#2312 chore: remove ts-node from dev-deps
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-web/package.json
Labels: dependencies

#2326 chore: fix tracer-web example webpack config
  examples/tracer-web/webpack.config.js
Labels: document

#2328 chore: updating compatibility matrix
  README.md
Labels: document

#2266 fix(exporter-collector-grpc): incorrect URL format on docs after 0.20.0 update
  packages/opentelemetry-exporter-collector-grpc/README.md
Labels: document

#2324 fix: update and make website docs work
  website_docs/getting_started/browser.md
  website_docs/getting_started/nodejs.md
  website_docs/instrumentation.md
Labels: document

#2331 Change default HTTP exporter port to 55681
  packages/opentelemetry-exporter-collector-proto/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-proto/src/CollectorTraceExporter.ts
Labels: bug

#2350 chore: ignore backcompat in renovate
  renovate.json
Labels: internal

#2309 chore: add includePrerelease option to instrumentation config
  packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
  packages/opentelemetry-instrumentation/src/platform/node/types.ts
Labels: enhancement

#2343 feat(opentelemetry-web): capture decodedBodySize / http.response_content_length_uncompressed
  packages/opentelemetry-web/src/enums/PerformanceTimingNames.ts
  packages/opentelemetry-web/src/types.ts
  packages/opentelemetry-web/src/utils.ts
  packages/opentelemetry-web/test/utils.test.ts
Labels: enhancement, spec-v1

#2308 chore: use typedoc to build sdk reference
  .github/workflows/docs.yaml
  README.md
  package.json
  tsconfig.json
Labels: document

#2351 style: use single quotes everywhere and add a rule to eslint
  eslint.config.js
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-grpc/test/helper.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
  packages/opentelemetry-node/test/registration.test.ts
  packages/opentelemetry-sdk-node/test/sdk.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
  packages/opentelemetry-tracing/test/common/Tracer.test.ts
  packages/opentelemetry-web/test/registration.test.ts
Labels: internal

#2322 fix(@opentelemetry/exporter-collector-grpc) regression from #2130 when host specified without protocol
  packages/opentelemetry-exporter-collector-grpc/src/util.ts
  packages/opentelemetry-exporter-collector-grpc/test/util.test.ts
Labels: bug

#2357 fix: headers are appended to existing one (open-telemetry#2335)
  packages/opentelemetry-exporter-collector/src/platform/browser/util.ts
  packages/opentelemetry-exporter-collector/test/browser/util.test.ts
Labels: bug

#2366 chore: adding Rauno56 to js approvers
  .github/CODEOWNERS
  README.md
Labels: internal

#2345 feat: updated spec to v1.5.0 and renamed resource class
  README.md
  examples/basic-tracer-node/index.js
  examples/collector-exporter-node/metrics.js
  examples/collector-exporter-node/tracing.js
  examples/grpc-js/tracer.js
  examples/grpc/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/opentracing-shim/shim.js
  examples/tracer-web/examples/metrics/index.js
  getting-started/README.md
  getting-started/traced-example/tracing.js
  getting-started/ts-example/README.md
  getting-started/ts-example/traced-example/tracing.ts
  packages/opentelemetry-core/src/platform/browser/sdk-info.ts
  packages/opentelemetry-core/src/platform/node/sdk-info.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsBeanstalkDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsLambdaDetector.ts
  packages/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts
  packages/opentelemetry-resources/README.md
  packages/opentelemetry-resources/src/Resource.ts
  packages/opentelemetry-resources/src/platform/node/detectors/EnvDetector.ts
  packages/opentelemetry-resources/src/platform/node/detectors/ProcessDetector.ts
  packages/opentelemetry-resources/test/Resource.test.ts
  packages/opentelemetry-resources/test/detectors/EnvDetector.test.ts
  packages/opentelemetry-resources/test/resource-assertions.test.ts
  packages/opentelemetry-resources/test/util/resource-assertions.ts
  packages/opentelemetry-resources/test/util/sample-detector.ts
  packages/opentelemetry-semantic-conventions/src/resource/SemanticResourceAttributes.ts
  packages/opentelemetry-semantic-conventions/src/resource/index.ts
  packages/opentelemetry-semantic-conventions/src/trace/SemanticAttributes.ts
  packages/opentelemetry-web/test/WebTracerProvider.test.ts
  scripts/semconv/generate.sh
Labels: breaking

#2365 docs: add quickstart code example
  README.md
Labels: document

#2379 fix: fixup aws detector readme
  packages/opentelemetry-resource-detector-aws/README.md
  packages/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts
Labels: document

#2332 feat(@opentelemetry-instrumentation-http): support adding custom attributes before a span is started
  packages/opentelemetry-instrumentation-http/README.md
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-http/src/types.ts
  packages/opentelemetry-instrumentation-http/src/utils.ts
  packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
Labels: enhancement

#2337 Support gzip compression for node exporter collector
  packages/opentelemetry-exporter-collector-proto/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-proto/src/util.ts
  packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts
  packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/src/platform/node/types.ts
  packages/opentelemetry-exporter-collector/src/platform/node/util.ts
  packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts
Labels: enhancement

#2344 Additional website docs updates
  website_docs/exporters.md
  website_docs/getting_started/browser.md
  website_docs/getting_started/nodejs.md
  website_docs/instrumentation_examples.md
Labels: document
