Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-09, with the labels that each got.

#2447 chore(exporter): fix lint warnings
  packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  packages/opentelemetry-exporter-prometheus/src/PrometheusLabelsBatcher.ts
  packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
  packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
  packages/opentelemetry-exporter-zipkin/src/transform.ts
  packages/opentelemetry-exporter-zipkin/src/types.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
  packages/opentelemetry-shim-opentracing/src/shim.ts
Labels: internal

#2446 chore(sdk-trace): fix lint warnings
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/src/Tracer.ts
  packages/opentelemetry-sdk-trace-base/src/config.ts
  packages/opentelemetry-sdk-trace-base/src/export/InMemorySpanExporter.ts
  packages/opentelemetry-sdk-trace-base/src/utility.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/MultiSpanProcessor.test.ts
  packages/opentelemetry-sdk-trace-node/src/NodeTracerProvider.ts
Labels: internal

#2454 chore(instrumentation-fetch): fix lint warnings
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
Labels: internal

#2430 feat(opentelemetry-sdk-trace-base): implemented general limits of attributes
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-sdk-trace-base/src/Tracer.ts
  packages/opentelemetry-sdk-trace-base/src/config.ts
  packages/opentelemetry-sdk-trace-base/src/types.ts
  packages/opentelemetry-sdk-trace-base/src/utility.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: enhancement

#2126 feat(instrumentation-http): add diag debug on http request events
  packages/opentelemetry-instrumentation-http/src/http.ts
Labels: internal

#2491 fix: remove usage of serviceName property in tests for otel collector
  packages/opentelemetry-exporter-otlp-http/test/node/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-otlp-http/test/node/CollectorTraceExporter.test.ts
Labels: internal

#2494 fix: remove setting http.route in http span attributes
  experimental/packages/opentelemetry-instrumentation-http/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
Labels: bug

#2504 fix: update typescript getting-started tracing example and docs
  getting-started/ts-example/README.md
  getting-started/ts-example/traced-example/tracing.ts
Labels: document

#2508 chore: move backwards compatibility to experimental
  experimental/backwards-compatability/node10/index.ts
  experimental/backwards-compatability/node10/package.json
  experimental/backwards-compatability/node10/tsconfig.json
  experimental/backwards-compatability/node12/index.ts
  experimental/backwards-compatability/node12/package.json
  experimental/backwards-compatability/node12/tsconfig.json
  experimental/backwards-compatability/node8/index.ts
  experimental/backwards-compatability/node8/package.json
  experimental/backwards-compatability/node8/tsconfig.json
  experimental/lerna.json
  experimental/tsconfig.esm.json
  experimental/tsconfig.json
  lerna.json
  tsconfig.esm.json
  tsconfig.json
Labels: internal

#2499 fix: 2389- replaced logger unformatted strings with template literals
  CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
  packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
Labels: bug
