Repository open-telemetry/opentelemetry-js, pull requests merged in 2021-06, with the labels that each got.

#2241 chore: update typescript to 4.3 and enable noImplicitOverride
  backwards-compatability/node10/package.json
  backwards-compatability/node12/package.json
  backwards-compatability/node8/package.json
  integration-tests/propagation-validation-server/package.json
  package.json
  packages/opentelemetry-api-metrics/package.json
  packages/opentelemetry-api-metrics/test/api/api.test.ts
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-collector-grpc/package.json
  packages/opentelemetry-exporter-collector-proto/package.json
  packages/opentelemetry-exporter-collector-proto/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector/package.json
  packages/opentelemetry-exporter-collector/src/types.ts
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-prometheus/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-instrumentation-fetch/package.json
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-grpc/package.json
  packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts
  packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
  packages/opentelemetry-instrumentation-http/package.json
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-xml-http-request/package.json
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation/package.json
  packages/opentelemetry-instrumentation/src/platform/browser/instrumentation.ts
  packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
  packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
  packages/opentelemetry-instrumentation/test/common/autoLoaderUtils.test.ts
  packages/opentelemetry-metrics/package.json
  packages/opentelemetry-metrics/src/BaseObserverMetric.ts
  packages/opentelemetry-metrics/src/SumObserverMetric.ts
  packages/opentelemetry-node/package.json
  packages/opentelemetry-node/src/NodeTracerProvider.ts
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resource-detector-aws/package.json
  packages/opentelemetry-resource-detector-gcp/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-node/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-tracing/package.json
  packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
  packages/opentelemetry-tracing/test/export/TestTracingSpanExporter.ts
  packages/opentelemetry-web/package.json
  packages/opentelemetry-web/src/WebTracerProvider.ts
  packages/template/package.json
  tsconfig.base.json
Labels: internal

#2221 feat: add startActiveSpan method to Tracer
  package.json
  packages/opentelemetry-tracing/src/Tracer.ts
  packages/opentelemetry-tracing/test/Tracer.test.ts
Labels: enhancement

#2194 feat(shim-opentracing): update setTag based on new spec
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: enhancement

#2254 chore: update compatibility matrix
  README.md
Labels: document, express

#2261 Adding ComponentLogger into instrumentations
  .github/workflows/unit-test.yml
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
  packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts
  packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
  packages/opentelemetry-instrumentation-http/src/http.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-instrumentation/src/instrumentation.ts
Labels: enhancement

#2263 docs(README): update link to @opentelemetry/api package
  README.md
Labels: document

#2287 chore(doc): update compatibility matrix
  README.md
Labels: document

#2283 Module opentelemetry/instrumentation-grpc required
  getting-started/README.md
Labels: document

#2289 docs(opentelemetry-resources): fix wrong sample code in readme
  packages/opentelemetry-resources/README.md
Labels: document

#2226 fix(xhr): make performance observer work with relative urls
  packages/opentelemetry-core/src/utils/url.ts
  packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
  packages/opentelemetry-web/src/utils.ts
Labels: enhancement

#2290 fix: service.name resource attribute
  examples/basic-tracer-node/index.js
  examples/collector-exporter-node/metrics.js
  examples/collector-exporter-node/tracing.js
  examples/grpc-js/tracer.js
  examples/grpc/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/tracer-web/examples/metrics/index.js
  getting-started/README.md
  getting-started/traced-example/tracing.js
  getting-started/ts-example/README.md
  getting-started/ts-example/traced-example/tracing.ts
  packages/opentelemetry-exporter-jaeger/README.md
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-sdk-node/README.md
Labels: document

#2300 chore(README): update link to BatchSpanProcessor in sdk node
  packages/opentelemetry-sdk-node/README.md
Labels: document, express

#2302 chore: use setup-node
  .github/workflows/unit-test.yml
Labels: internal

#2296 chore: do not upgrade backwards compatibility
  renovate.json
Labels: internal

#2285 fix(propagator-b3): update extract to check for array
  packages/opentelemetry-propagator-b3/src/B3Propagator.ts
  packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts
Labels: enhancement

#2304 feat: otlp-grpc exporter uses headers environment variables
  packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorMetricExporter.ts
  packages/opentelemetry-exporter-collector-grpc/src/CollectorTraceExporter.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts
  packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
Labels: enhancement

#2306 chore: update the website getting started docs
  getting-started/README.md
  website_docs/_index.md
  website_docs/getting_started/browser.md
  website_docs/getting_started/nodejs.md
Labels: document

#2247 feat: unify the signatures of bind and with
  packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
  packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts
  packages/opentelemetry-web/src/StackContextManager.ts
Labels: internal
