Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-02, with the labels that each got.

#2757 fix: add parentContext to onStart
  packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts
  packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/BatchSpanProcessorBase.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/SimpleSpanProcessor.test.ts
Labels: bug

#2754 fix(exporter-jaeger): add env variable for agent port
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
Labels: enhancement

#2726 docs(otlp-grpc-exporter): update default url
  packages/exporter-trace-otlp-grpc/README.md
Labels: document

#2728 docs: specify minimun version of npm to run command in subproject
  CONTRIBUTING.md
Labels: document

#2766 fix(baggage): include baggage metadata when propagating baggage entries
  packages/opentelemetry-core/src/baggage/utils.ts
  packages/opentelemetry-core/test/baggage/W3CBaggagePropagator.test.ts
Labels: bug

#2743 test(sdk-metrics-base): test metric instrument interfaces
  experimental/packages/opentelemetry-sdk-metrics-base/test/Instruments.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/util.ts
Labels: internal

#2776 feat(sdk-metrics-base): add ValueType support for sync instruments
  experimental/packages/opentelemetry-sdk-metrics-base/src/Instruments.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/Instruments.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/util.ts
Labels: enhancement

#2790 fix: pass same context to Sampler and SpanProcessor in root span case
  packages/opentelemetry-sdk-trace-base/src/Tracer.ts
  packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts
Labels: bug

#2802 docs(prom-example): remove deprecated startServer option
  examples/prometheus/index.js
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer.js
Labels: document

#2788 fix(deps): use 1.x trace otlp http exporter
  packages/exporter-trace-otlp-grpc/package.json
  packages/exporter-trace-otlp-grpc/src/OTLPExporterNodeBase.ts
  packages/exporter-trace-otlp-http/src/OTLPExporterBase.ts
  packages/exporter-trace-otlp-proto/package.json
  packages/exporter-trace-otlp-proto/src/OTLPExporterNodeBase.ts
Labels: bug, dependencies
