Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-03, with the labels that each got.

#2768 test(sdk-trace-base): pin core.hrtime dependencies on timeOrigin
  karma.webpack.js
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: internal

#2796 feat(trace-otlp-http-exporter): add compression env vars
  packages/exporter-trace-otlp-http/src/platform/node/OTLPExporterNodeBase.ts
  packages/exporter-trace-otlp-http/src/platform/node/util.ts
  packages/exporter-trace-otlp-http/test/node/CollectorTraceExporter.test.ts
  packages/exporter-trace-otlp-http/test/node/utils.test.ts
  packages/opentelemetry-core/src/utils/environment.ts
Labels: enhancement

#2814 docs: simplify contrib part in readme
  README.md
Labels: document

#2830 Cleanup removed documentation for missing benchmarks
  .github/workflows/docs.yaml
  .github/workflows/w3c-integration-test.yml
  CONTRIBUTING.md
  lerna.json
  package.json
Labels: document

#2832 fix(opentelemtry-core): fix header extraction
  packages/opentelemetry-core/src/baggage/propagation/W3CBaggagePropagator.ts
  packages/opentelemetry-core/test/baggage/W3CBaggagePropagator.test.ts
Labels: bug

#2813 Add grpc compression to trace-otlp-grpc exporter
  packages/exporter-trace-otlp-grpc/README.md
  packages/exporter-trace-otlp-grpc/src/OTLPExporterNodeBase.ts
  packages/exporter-trace-otlp-grpc/src/types.ts
  packages/exporter-trace-otlp-grpc/src/util.ts
  packages/exporter-trace-otlp-grpc/test/OTLPTraceExporter.test.ts
  packages/exporter-trace-otlp-grpc/test/util.test.ts
Labels: enhancement

#2746 feat(proto): add @opentelemetry/otlp-transformer package with hand-rolled transformation
  .github/workflows/peer-api.yaml
  .nycrc
  experimental/packages/otlp-transformer/.eslintignore
  experimental/packages/otlp-transformer/.eslintrc.js
  experimental/packages/otlp-transformer/.gitignore
  experimental/packages/otlp-transformer/README.md
  experimental/packages/otlp-transformer/karma.conf.js
  experimental/packages/otlp-transformer/package.json
  experimental/packages/otlp-transformer/src/common/internal.ts
  experimental/packages/otlp-transformer/src/common/types.ts
  experimental/packages/otlp-transformer/src/index.ts
  experimental/packages/otlp-transformer/src/metrics/index.ts
  experimental/packages/otlp-transformer/src/metrics/internal.ts
  experimental/packages/otlp-transformer/src/metrics/types.ts
  experimental/packages/otlp-transformer/src/resource/types.ts
  experimental/packages/otlp-transformer/src/trace/index.ts
  experimental/packages/otlp-transformer/src/trace/internal.ts
  experimental/packages/otlp-transformer/src/trace/types.ts
  experimental/packages/otlp-transformer/test/common.test.ts
  experimental/packages/otlp-transformer/test/index-webpack.ts
  experimental/packages/otlp-transformer/test/metrics.test.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
  experimental/packages/otlp-transformer/tsconfig.all.json
  experimental/packages/otlp-transformer/tsconfig.esm.json
  experimental/packages/otlp-transformer/tsconfig.esnext.json
  experimental/packages/otlp-transformer/tsconfig.json
  experimental/tsconfig.json
Labels: enhancement

#2789 HTTP 400 status code should not set span status to error on servers
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  experimental/packages/opentelemetry-instrumentation-http/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
Labels: bug
