Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-11, with the labels that each got.

#3369 Update README
  README.md
  package.json
Labels: document, Skip Changelog

#3351 docs: document how to implement a propagator
  doc/propagation.md
Labels: document, Skip Changelog

#3401 Update API readme and doc links
  README.md
  api/README.md
  doc/context.md
  doc/sdk-registration.md
  doc/tracing.md
  packages/opentelemetry-context-async-hooks/README.md
Labels: Skip Changelog

#3403 chore: remove experimental note in sdk-metrics
  packages/sdk-metrics/README.md
  packages/sdk-metrics/package.json
Labels: Skip Changelog

#3411 fix(sdk-metrics): use default Resource to comply with semconv
  CHANGELOG.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
  experimental/packages/opentelemetry-exporter-prometheus/test/util.ts
  experimental/packages/opentelemetry-exporter-prometheus/tsconfig.json
  packages/sdk-metrics/src/MeterProvider.ts
  packages/sdk-metrics/test/util.ts
Labels: bug
