Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-12, with the labels that each got.

#3453 docs(otlp-*-exporter-base): add internal use note
  experimental/packages/otlp-exporter-base/README.md
  experimental/packages/otlp-grpc-exporter-base/README.md
  experimental/packages/otlp-proto-exporter-base/README.md
Labels: document, Skip Changelog

#3475 chore: improve windows compatibility of update-ts-config
  scripts/update-ts-configs-constants.js
  scripts/update-ts-configs.js
Labels: Skip Changelog

#3443 feat(api-logs): add the SeverityNumber enumeration
  experimental/CHANGELOG.md
  experimental/packages/api-logs/README.md
  experimental/packages/api-logs/src/types/LogRecord.ts
  experimental/packages/api-logs/test/noop-implementations/noop-logger.test.ts
Labels: api:logs
