Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-09, with the labels that each got.

#3198 chore(api-metrics): clean up exports
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-api-metrics/src/NoopMeter.ts
  experimental/packages/opentelemetry-api-metrics/src/index.ts
  experimental/packages/opentelemetry-api-metrics/test/api/api.test.ts
  experimental/packages/opentelemetry-api-metrics/test/api/global.test.ts
  experimental/packages/opentelemetry-api-metrics/test/noop-implementations/noop-meter.test.ts
  experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
  experimental/packages/opentelemetry-sdk-metrics/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics/test/MeterProvider.test.ts
  experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Labels: api:metrics

#3231 fix(build): rollback linkinator to 3.0.3
  package.json
Labels: Skip Changelog

#3226 docs(node-sdk): update outdated metric documentation.
  experimental/packages/opentelemetry-sdk-node/README.md
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
Labels: Skip Changelog, signal:metrics

#3134 feat: anchored clock
  CHANGELOG.md
  packages/opentelemetry-core/src/common/anchored-clock.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/test/common/anchored-clock.test.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/src/Tracer.ts
Labels: bug, priority:p2

#3225 feat(sdk-metrics): align MetricReader with specification and other language implementations
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
  experimental/packages/opentelemetry-sdk-metrics/src/export/AggregationSelector.ts
  experimental/packages/opentelemetry-sdk-metrics/src/export/MetricExporter.ts
  experimental/packages/opentelemetry-sdk-metrics/src/export/MetricReader.ts
  experimental/packages/opentelemetry-sdk-metrics/src/export/PeriodicExportingMetricReader.ts
  experimental/packages/opentelemetry-sdk-metrics/src/index.ts
  experimental/packages/opentelemetry-sdk-metrics/test/export/MetricReader.test.ts
  experimental/packages/opentelemetry-sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
  experimental/packages/opentelemetry-sdk-metrics/test/export/TestMetricReader.ts
  experimental/packages/opentelemetry-sdk-metrics/test/export/utils.ts
Labels: sdk:metrics

#3170 feat(opentelemetry-api-metrics): Adding generics to `create{metricType}`
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts
  experimental/packages/opentelemetry-api-metrics/src/types/Metric.ts
  experimental/packages/opentelemetry-api-metrics/src/types/ObservableResult.ts
  experimental/packages/opentelemetry-api-metrics/test/types/Metric.test.ts
Labels: api:metrics

#3241 chore: upgrade linkinator to 4.0.3
  package.json
Labels: dependencies, Skip Changelog

#3244 docs(sdk-metrics): fix typos and add missing parameter docs
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-metrics/src/aggregator/types.ts
  experimental/packages/opentelemetry-sdk-metrics/src/exemplar/ExemplarFilter.ts
  experimental/packages/opentelemetry-sdk-metrics/src/export/MetricExporter.ts
  experimental/packages/opentelemetry-sdk-metrics/src/state/MeterSharedState.ts
  experimental/packages/opentelemetry-sdk-metrics/src/state/TemporalMetricProcessor.ts
  experimental/packages/opentelemetry-sdk-metrics/src/view/Predicate.ts
Labels: sdk:metrics

#3265 chore: ignore @opentelemetry/api in renovate config
  renovate.json
Labels: internal, Skip Changelog

#3256 docs: update exporter guide
  doc/contributing/web-api.md
  doc/exporter-guide.md
Labels: Skip Changelog

#3260 chore: remove repo specific files from api dir
  api/.commitlintrc.yml
  api/.editorconfig
  api/.eslintrc.js
  api/.gitattributes
  api/.github/CODEOWNERS
  api/.github/workflows/codeql-analysis.yml
  api/.github/workflows/docs.yaml
  api/.github/workflows/lint.yaml
  api/.github/workflows/release-please.yml
  api/.github/workflows/test.yaml
  api/.gitignore
  api/.markdownlint.json
  api/.npmignore
  api/TODO.md
  api/karma.base.js
  api/karma.conf.js
  api/karma.webpack.js
  api/renovate.json
  api/scripts/version-update.js
  api/tsconfig.esm.json
  api/tsconfig.json
  api/webpack.node-polyfills.js
Labels: Skip Changelog
