Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-08, with the labels that each got.

#3126 fix(otlp-proto-exporter-base): spawn pbjs without node
  experimental/packages/otlp-proto-exporter-base/scripts/protos.js
Labels: Skip Changelog

#3133 Prevent double wrapping event emitter listeners
  CHANGELOG.md
  packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: bug, priority:p1

#3044 Fix docs deployment
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
Labels: Skip Changelog

#3157 Update non-web dev deps
  examples/https/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-sdk-trace-web/test/utils.test.ts
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/template/package.json
Labels: dependencies

#3136 chore: add windows unit test action
  .github/workflows/unit-test.yml
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
Labels: Skip Changelog

#3110 docs(prometheus-exporter): fix prometheus exporter examples in README
  experimental/packages/opentelemetry-api-metrics/README.md
  experimental/packages/opentelemetry-exporter-prometheus/README.md
Labels: Skip Changelog

#3182 Add svetlanabrennan as an approver
  README.md
Labels: Skip Changelog

#3209 chore: cleanup eslint
  eslint.config.js
Labels: Skip Changelog
