Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-01, with the labels that each got.

#2699 chore: rename `--include-filtered-dependencies`
  experimental/lerna.json
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  lerna.json
  packages/exporter-trace-otlp-grpc/package.json
  packages/exporter-trace-otlp-http/package.json
  packages/exporter-trace-otlp-proto/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/template/package.json
Labels: internal

#2701 chore: add Rauno Viskus as maintainer
  README.md
  renovate.json
Labels: internal

#2703 chore: add Amir Blum as maintainer
  README.md
  renovate.json
Labels: internal

#2702 chore: add Chengzhong Wu as maintainer
  README.md
  renovate.json
Labels: internal

#2694 fix(propagator-jaeger): 0-pad span-id to match 16-symbol validation
  packages/opentelemetry-propagator-jaeger/src/JaegerPropagator.ts
  packages/opentelemetry-propagator-jaeger/test/JaegerPropagator.test.ts
Labels: bug

#2695 refactor: unifying shutdown once with BindOnceFuture
  packages/exporter-trace-otlp-grpc/tsconfig.json
  packages/exporter-trace-otlp-http/src/OTLPExporterBase.ts
  packages/exporter-trace-otlp-http/src/platform/browser/OTLPExporterBrowserBase.ts
  packages/exporter-trace-otlp-http/src/platform/node/OTLPExporterNodeBase.ts
  packages/exporter-trace-otlp-http/tsconfig.json
  packages/exporter-trace-otlp-proto/tsconfig.json
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/callback.ts
  packages/opentelemetry-core/src/utils/promise.ts
  packages/opentelemetry-core/test/test-utils.ts
  packages/opentelemetry-core/test/utils/callback.test.ts
  packages/opentelemetry-core/test/utils/promise.test.ts
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
  packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts
  packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
Labels: enhancement

#2666 feat(sdk-metrics-base): meter registration
  experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/state/MeterProviderSharedState.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/state/MetricCollector.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/export/TestMetricReader.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/state/MetricCollector.test.ts
Labels: enhancement

#2676 fix(sdk-metrics-base): remove aggregator.toMetricData dependency on AggregationTemporality
  experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/Drop.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/Histogram.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/LastValue.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/Sum.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/types.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/state/TemporalMetricProcessor.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/aggregator/Drop.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/aggregator/Histogram.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/aggregator/LastValue.test.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/aggregator/Sum.test.ts
Labels: bug

#2704 feat(instrumentation-http): add options to ignore requests
  experimental/packages/opentelemetry-instrumentation-http/README.md
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  experimental/packages/opentelemetry-instrumentation-http/src/types.ts
  experimental/packages/opentelemetry-instrumentation-http/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
Labels: enhancement

#2720 docs: document node v10 EOL
  README.md
Labels: document

#2712 docs(api-metrics): add notes on ObservableResult.observe
  experimental/packages/opentelemetry-api-metrics/src/types/ObservableResult.ts
Labels: document

#2557 feat(otlp-exporter-http): change otlp-http port to canonical 4318
  examples/basic-tracer-node/docker/ot/collector-config.yaml
  examples/basic-tracer-node/docker/ot/docker-compose.yaml
  examples/otlp-exporter-node/docker/collector-config.yaml
  examples/otlp-exporter-node/docker/docker-compose.yaml
  examples/otlp-exporter-node/metrics.js
  examples/otlp-exporter-node/package.json
  examples/otlp-exporter-node/tracing.js
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/browser/OTLPMetricExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/node/OTLPMetricExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/OTLPMetricExporter.ts
  packages/exporter-trace-otlp-http/README.md
  packages/exporter-trace-otlp-http/src/platform/browser/OTLPTraceExporter.ts
  packages/exporter-trace-otlp-http/src/platform/node/OTLPTraceExporter.ts
  packages/exporter-trace-otlp-http/test/browser/CollectorTraceExporter.test.ts
  packages/exporter-trace-otlp-http/test/node/CollectorTraceExporter.test.ts
  packages/exporter-trace-otlp-proto/README.md
  packages/exporter-trace-otlp-proto/src/OTLPTraceExporter.ts
Labels: enhancement

#2715 chore: update actions/checkout to v2
  .github/workflows/unit-test.yml
Labels: internal

#2733 feat(views): add FilteringAttributesProcessor
  experimental/packages/opentelemetry-sdk-metrics-base/src/view/AttributesProcessor.ts
  experimental/packages/opentelemetry-sdk-metrics-base/test/view/AttributesProcessor.test.ts
Labels: enhancement

#2752 test(integration-w3c): fix inconsistent api versions loaded
  .github/workflows/w3c-integration-test.yml
  integration-tests/propagation-validation-server/package.json
Labels: internal

#2731 fix(exporter-jaeger): transform all links to jaeger reference
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
Labels: bug
