Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-07, with the labels that each got.

#3075 docs(sdk-metrics): update document on public interfaces
  experimental/examples/prometheus/index.js
  experimental/packages/opentelemetry-sdk-metrics-base/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/src/InstrumentDescriptor.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricData.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricExporter.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricProducer.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricReader.ts
  experimental/packages/opentelemetry-sdk-metrics-base/src/export/PeriodicExportingMetricReader.ts
Labels: Skip Changelog

#3083 typo on example link
  examples/http/README.md
Labels: document, Skip Changelog

#3101 Use latest npm after setup node
  .github/workflows/unit-test.yml
Labels: Skip Changelog

#3023 feat: allow extending `BasicTracerProvider` with custom registered components
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-node/src/NodeTracerProvider.ts
  packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-node/test/registration.test.ts
Labels: Skip Changelog

#3114 docs: add homepage links
  examples/basic-tracer-node/package.json
  examples/grpc-js/package.json
  examples/grpc/package.json
  examples/http/package.json
  examples/https/package.json
  examples/opentracing-shim/package.json
  examples/otlp-exporter-node/package.json
  examples/tracer-web/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/template/package.json
Labels: Skip Changelog

#3068 fix(sdk-trace-base): fix spanLimits attribute length/count to consider env values
  CHANGELOG.md
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-sdk-trace-base/src/config.ts
  packages/opentelemetry-sdk-trace-base/src/utility.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
Labels: priority:p4, spec-inconsistency

#3041 feat: export unit block when unit is set in metric descriptor
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
Labels: spec-feature

#3037 refactor(fetch): revert to original code in endSpanOnSuccess
  experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts
Labels: Skip Changelog
