Repository open-telemetry/opentelemetry-js, pull requests merged in 2022-04, with the labels that each got.

#2879 fix(otlp-http-exporter): remove content length header
  experimental/CHANGELOG.md
  experimental/packages/exporter-trace-otlp-http/src/platform/node/util.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts
Labels: bug

#2898 chore: remove husky hooks
  package.json
Labels: Skip Changelog

#2909 Update example in ContextZone README.md
  packages/opentelemetry-context-zone/README.md
Labels: Skip Changelog

#2908 chore: add coverage scripts to experimental
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/otlp-transformer/package.json
Labels: Skip Changelog

#2913 Fix code coverage paths
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-transformer/package.json
Labels: Skip Changelog

#2904 chore: cleanup API dependencies
  experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-transformer/package.json
Labels: Skip Changelog

#2928 Include metrics in release
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
Labels: Skip Changelog

#2920 chore(deps): update dependency ts-mocha to v9
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-api-metrics/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-metrics-base/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
Labels: dependencies, Skip Changelog

#2939 chore: update prometheus examples
  .github/workflows/unit-test.yml
  examples/prometheus/images/prom-counter.png
  examples/prometheus/images/prom-updowncounter.png
  examples/prometheus/index.js
  experimental/examples/.eslintrc.js
  experimental/examples/README.md
  experimental/examples/prometheus/README.md
  experimental/examples/prometheus/images/prom-counter.png
  experimental/examples/prometheus/images/prom-updowncounter.png
  experimental/examples/prometheus/index.js
  experimental/examples/prometheus/package.json
  experimental/examples/prometheus/prometheus.yml
  experimental/packages/opentelemetry-sdk-metrics-base/examples/.eslintrc.json
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/README.md
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer.js
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer.png
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer_batch.png
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer_batch2.png
  experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/package.json
Labels: Skip Changelog
