Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-02, with the labels that each got.

#3594 Add Martin Kuba to approvers list
  README.md
Labels: Skip Changelog

#3593 Add haddasbronfman as approver
  README.md
Labels: Skip Changelog

#3596 Add pichlermarc to maintainers
  README.md
Labels: Skip Changelog

#3599 chore: enable merge queues
  .github/repository-settings.md
Labels: Skip Changelog

#3607 chore: enable merge queue checks
  .github/workflows/lint.yml
  .github/workflows/peer-api.yml
  .github/workflows/unit-test.yml
  .github/workflows/w3c-integration-test.yml
Labels: Skip Changelog

#3626 chore: remove unused argument
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
Labels: Skip Changelog

#3629 chore: improve logging for api registration mismatches
  api/src/internal/global-utils.ts
  api/test/common/internal/global.test.ts
Labels: Skip Changelog

#3617 fix(core): added falsy check to make otel core work with browser where webpack config had process as false or null
  CHANGELOG.md
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-sdk-trace-web/test/NodeGlobalsFoolProofing.test.ts
Labels: bug, priority:p1

#3636 fix: batchspanprocessor.test for TS > 4.6.0
  packages/opentelemetry-sdk-trace-base/test/browser/export/BatchSpanProcessor.test.ts
Labels: Skip Changelog

#3603 feat: improve http span name
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-package.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/integrations/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/integrations/https-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
Labels: enhancement, instrumentation, spec-inconsistency
