Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-03, with the labels that each got.

#3641 Rename Diag/LoggerOptions to DiagLoggerOptions
  api/CHANGELOG.md
  api/src/diag/types.ts
Labels: pkg:api

#3624 fix(sdk-node): update instrumentations once MeterProvider is initialized
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/opentelemetry-sdk-node/src/utils.ts
Labels: bug

#3657 fix(build): add `example/http` to ignore list in `update-ts-configs`
  scripts/update-ts-configs.js
Labels: internal, Skip Changelog

#3576 feat(sdk-trace-base): add dropped attributes and events count on span
  CHANGELOG.md
  api/CHANGELOG.md
  api/src/trace/link.ts
  experimental/CHANGELOG.md
  experimental/packages/exporter-trace-otlp-grpc/test/traceHelper.ts
  experimental/packages/exporter-trace-otlp-http/test/traceHelper.ts
  experimental/packages/exporter-trace-otlp-proto/test/traceHelper.ts
  experimental/packages/otlp-grpc-exporter-base/test/traceHelper.ts
  experimental/packages/otlp-transformer/src/trace/internal.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/src/transform.ts
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/helper.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/src/TimedEvent.ts
  packages/opentelemetry-sdk-trace-base/src/config.ts
  packages/opentelemetry-sdk-trace-base/src/export/ReadableSpan.ts
  packages/opentelemetry-sdk-trace-base/src/types.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: api:traces, sdk:traces

#3660 fix: Minor typing issues for web sandbox
  experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts
  packages/opentelemetry-context-zone-peer-dep/src/util.ts
  packages/opentelemetry-sdk-trace-web/src/utils.ts
Labels: Skip Changelog

#3671 docs: update CONTRIBUTING.md merge requirements
  CONTRIBUTING.md
Labels: Skip Changelog

#3688 docs(readme): exporter should be metricExporter
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
Labels: Skip Changelog

#3691 docs: fix links to OpenTelemetry Metrics documentation
  README.md
  experimental/examples/prometheus/README.md
  experimental/packages/opentelemetry-exporter-prometheus/README.md
Labels: Skip Changelog

#3700 fix(ci): use npx to run tsc 4.4.4 in api-eol-node-test
  .github/workflows/unit-test.yml
Labels: internal, Skip Changelog

#3696 chore: remove handling of node versions 8, 9 and 10 in tests
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Labels: internal, Skip Changelog
