Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-10, with the labels that each got.

#4172 fix(benchmark): write benchmark results to file
  .github/workflows/benchmark.yml
  .gitignore
  packages/opentelemetry-sdk-trace-base/package.json
Labels: internal, Skip Changelog

#4181 chore: remove outdated and empty docs
  doc/library-author.md
  doc/metrics.md
  doc/processor-api.md
  doc/tracing.md
Labels: document, Skip Changelog

#4192 deps: update proto-loader
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
Labels: dependencies

#4163 fix(sdk-metrics): prevent per-reader storages from keeping unreported accumulations in memory
  CHANGELOG.md
  packages/sdk-metrics/src/state/AsyncMetricStorage.ts
  packages/sdk-metrics/src/state/MeterSharedState.ts
  packages/sdk-metrics/src/state/MetricStorage.ts
  packages/sdk-metrics/src/state/SyncMetricStorage.ts
  packages/sdk-metrics/src/state/TemporalMetricProcessor.ts
  packages/sdk-metrics/test/state/AsyncMetricStorage.test.ts
  packages/sdk-metrics/test/state/MetricStorageRegistry.test.ts
  packages/sdk-metrics/test/state/SyncMetricStorage.test.ts
  packages/sdk-metrics/test/state/TemporalMetricProcessor.test.ts
Labels: bug, priority:p1

#3876 feat(metrics): prototype experimental advice support
  CHANGELOG.md
  api/CHANGELOG.md
  api/src/index.ts
  api/src/metrics/Metric.ts
  packages/sdk-metrics/src/InstrumentDescriptor.ts
  packages/sdk-metrics/src/ObservableResult.ts
  packages/sdk-metrics/src/aggregator/Drop.ts
  packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts
  packages/sdk-metrics/src/aggregator/Histogram.ts
  packages/sdk-metrics/src/aggregator/LastValue.ts
  packages/sdk-metrics/src/aggregator/Sum.ts
  packages/sdk-metrics/src/aggregator/types.ts
  packages/sdk-metrics/src/export/MetricData.ts
  packages/sdk-metrics/src/index.ts
  packages/sdk-metrics/src/state/MetricStorage.ts
  packages/sdk-metrics/src/state/ObservableRegistry.ts
  packages/sdk-metrics/src/view/Aggregation.ts
  packages/sdk-metrics/test/InstrumentDescriptor.test.ts
  packages/sdk-metrics/test/Instruments.test.ts
  packages/sdk-metrics/test/ObservableResult.test.ts
  packages/sdk-metrics/test/state/MetricStorageRegistry.test.ts
  packages/sdk-metrics/test/util.ts
Labels: api:metrics, sdk:metrics

#4199 fix: bump deploy docs workflow to node 18
  .github/workflows/docs.yaml
Labels: dependencies, internal
