Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-01, with the labels that each got.

#3484 docs(sdk-metrics): fix badge and reword introductory sentence
  packages/sdk-metrics/README.md
Labels: document, Skip Changelog

#3519 Document repo settings
  .github/repository-settings.md
Labels: Skip Changelog

#3536 Fix changelog link
  api/CHANGELOG.md
Labels: Skip Changelog

#3517 fix(sdk-metrics): collect metrics when periodic exporting metric reader flushes
  CHANGELOG.md
  packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts
  packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
Labels: sdk:metrics

#3547 fix(typo): Fix typo in Resource.default docstring
  packages/opentelemetry-resources/src/Resource.ts
Labels: Skip Changelog

#3567 chore: fix proto generation
  experimental/packages/otlp-proto-exporter-base/scripts/protos.js
Labels: Skip Changelog

#3578 chore(tsconfig): abort on invalid json content
  doc/contributing/style.md
  experimental/backwards-compatability/node14/tsconfig.json
  experimental/backwards-compatability/node16/tsconfig.json
  experimental/packages/otlp-grpc-exporter-base/tsconfig.json
  scripts/update-ts-configs.js
  tsconfig.base.es5.json
  tsconfig.base.esm.json
Labels: Skip Changelog
