Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-08, with the labels that each got.

#4030 fix(ci): don't collect coverage for eol tests
  .github/workflows/unit-test.yml
  api/package.json
Labels: bug, internal, Skip Changelog

#4032 chore(exporter-logs-otlp-http): commit missing generated changes to tsconfig.json
  experimental/packages/exporter-logs-otlp-http/tsconfig.esm.json
  experimental/packages/exporter-logs-otlp-http/tsconfig.esnext.json
  experimental/packages/exporter-logs-otlp-http/tsconfig.json
Labels: internal, Skip Changelog

#4037 docs(README): clarify browser support
  README.md
Labels: document, Skip Changelog

#4052 chore: update blumamir employee name in the README
  README.md
Labels: Skip Changelog

#4069 chore: move inactive approvers to emeritus
  README.md
Labels: internal, Skip Changelog

#4085 docs: fix broken link to renovate.json
  doc/GUIDELINES.md
Labels: Skip Changelog

#4076 Semver Minor Version bumpup (7.5.1 -> 7.5.2)
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/shim-opencensus/package.json
  packages/opentelemetry-sdk-trace-node/package.json
Labels: Merge:LGTM, dependencies

#4075 chore(deps): update prettier to v3 and prettier-plugin-eslint to v5
  api/src/metrics/Meter.ts
  api/src/metrics/Metric.ts
  api/src/metrics/ObservableResult.ts
  experimental/packages/exporter-logs-otlp-http/test/node/OTLPLogExporter.test.ts
  experimental/packages/exporter-logs-otlp-proto/test/logHelper.ts
  experimental/packages/exporter-trace-otlp-http/test/node/nodeHelpers.ts
  experimental/packages/exporter-trace-otlp-proto/test/traceHelper.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/nodeHelpers.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  experimental/packages/otlp-exporter-base/src/OTLPExporterBase.ts
  experimental/packages/otlp-exporter-base/src/platform/browser/OTLPExporterBrowserBase.ts
  experimental/packages/otlp-exporter-base/src/platform/node/OTLPExporterNodeBase.ts
  experimental/packages/otlp-grpc-exporter-base/src/OTLPGRPCExporterNodeBase.ts
  experimental/packages/otlp-proto-exporter-base/src/platform/browser/OTLPProtoExporterBrowserBase.ts
  experimental/packages/otlp-proto-exporter-base/src/platform/node/OTLPProtoExporterNodeBase.ts
  experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts
  package.json
  packages/opentelemetry-core/src/utils/callback.ts
  packages/opentelemetry-core/test/utils/merge.test.ts
  packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts
  packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts
  packages/sdk-metrics/src/state/MeterSharedState.ts
  packages/sdk-metrics/src/view/Aggregation.ts
Labels: Merge:LGTM, dependencies, internal, Skip Changelog

#4091 fix(renovate): remove faulty '@types/node' rule and explicitly apply it to the whole repo
  renovate.json
Labels: Skip Changelog

#4077 feat: update PeriodicExportingMetricReader and PrometheusExporter to accept optional metric producers
  CHANGELOG.md
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  experimental/packages/opentelemetry-exporter-prometheus/src/export/types.ts
  packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts
Labels: Merge:LGTM

#4068 chore(sdk-node): add notice to manually install '@opentelemetry/exporter-jaeger'
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/package.json
Labels: Merge:LGTM

#3968 fix(exporter-logs-otlp-http): add @opentelemetry/api-logs as dependency
  experimental/CHANGELOG.md
  experimental/packages/exporter-logs-otlp-http/package.json
Labels: Merge:LGTM
