Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-09, with the labels that each got.

#4111 fix: limit npm to <10.0.0 on node v14 and v16
  .github/workflows/unit-test.yml
Labels: internal, Skip Changelog

#4119 docs(guidelines) tiny fix, add comma on docs
  doc/tracing.md
Labels: document, Skip Changelog

#4124 fix(ci): pin nx to 15.9.6 for Node.js v14
  .github/workflows/unit-test.yml
Labels: internal, Skip Changelog

#4110 fix(codeql): run workflow for pushes to main and pull requests
  .github/workflows/codeql-analysis.yml
Labels: internal, Skip Changelog

#4049 fix(sdk-node): move @opentelemetry/exporter-jaeger to dev dependencies
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/README.md
  experimental/packages/opentelemetry-sdk-node/package.json
Labels: Dependency on other PR

#4104 fix(readme): update compatibility table and remove API column
  README.md
Labels: document, Skip Changelog

#4078 docs: update OpenCensus shim example for metrics
  experimental/examples/opencensus-shim/README.md
  experimental/examples/opencensus-shim/images/prom-metrics.png
  experimental/examples/opencensus-shim/package.json
  experimental/examples/opencensus-shim/server.js
  experimental/examples/opencensus-shim/setup.js
  experimental/packages/shim-opencensus/README.md
Labels: document, Skip Changelog

#4105 Introduce benchmark tests
  CHANGELOG.md
  package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-base/test/performance/benchmark/index.js
  packages/opentelemetry-sdk-trace-base/test/performance/benchmark/span.js
Labels: Skip Changelog
