Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-05, with the labels that each got.

#3751 feat(opencensus-shim) add mapping logic and propagation shim
  experimental/packages/opentelemetry-shim-opencensus/package.json
  experimental/packages/opentelemetry-shim-opencensus/src/propagation.ts
  experimental/packages/opentelemetry-shim-opencensus/src/transform.ts
  experimental/packages/opentelemetry-shim-opencensus/test/propagation.test.ts
  experimental/packages/opentelemetry-shim-opencensus/test/transform.test.ts
Labels: Skip Changelog

#3784 chore: remove "opentelemetry" prefix from opencensus-shim package directory
  experimental/packages/shim-opencensus/.eslintignore
  experimental/packages/shim-opencensus/.eslintrc.js
  experimental/packages/shim-opencensus/.npmignore
  experimental/packages/shim-opencensus/LICENSE
  experimental/packages/shim-opencensus/README.md
  experimental/packages/shim-opencensus/package.json
  experimental/packages/shim-opencensus/src/index.ts
  experimental/packages/shim-opencensus/src/propagation.ts
  experimental/packages/shim-opencensus/src/transform.ts
  experimental/packages/shim-opencensus/test/ShimTracer.test.ts
  experimental/packages/shim-opencensus/test/propagation.test.ts
  experimental/packages/shim-opencensus/test/transform.test.ts
  experimental/packages/shim-opencensus/tsconfig.json
  tsconfig.json
Labels: Skip Changelog

#3756 feat(opencensus-shim) add ShimTracer and ShimSpan implementations
  experimental/packages/shim-opencensus/package.json
  experimental/packages/shim-opencensus/src/ShimSpan.ts
  experimental/packages/shim-opencensus/src/ShimTracer.ts
  experimental/packages/shim-opencensus/src/index.ts
  experimental/packages/shim-opencensus/test/ShimSpan.test.ts
  experimental/packages/shim-opencensus/test/ShimTracer.test.ts
  experimental/packages/shim-opencensus/test/otel-sandwich.test.ts
  experimental/packages/shim-opencensus/test/util.ts
  experimental/packages/shim-opencensus/tsconfig.json
Labels: Skip Changelog

#3805 Add scripts to prepare releases automatically
  .github/workflows/label-releases.yml
  package.json
Labels: Skip Changelog

#3831 Add Hector to approvers
  README.md
Labels: Skip Changelog

#3832 Add Purvi to approvers
  README.md
Labels: Skip Changelog

#3840 deps(exporter-logs-otlp-http): remove unused rimraf devDependency
  experimental/packages/exporter-logs-otlp-http/package.json
Labels: dependencies, Skip Changelog

#3833 chore(instrumentation-grpc): add 'grpc' deprecation notice postinstall script
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
Labels: Merge:LGTM

#3843 fix(opentelemetry-semantic-conventions): update trace semantic conventions url
  packages/opentelemetry-semantic-conventions/README.md
Labels: Skip Changelog

#3842 fix(exporter-logs-otlp-grpc): make test server use port 1503
  experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts
Labels: internal, Skip Changelog
