Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-06, with the labels that each got.

#3821 feat/logattributes support map type
  experimental/CHANGELOG.md
  experimental/packages/api-logs/src/types/LogRecord.ts
  experimental/packages/api-logs/src/types/LoggerOptions.ts
  experimental/packages/otlp-transformer/package.json
  experimental/packages/otlp-transformer/src/common/internal.ts
  experimental/packages/otlp-transformer/src/logs/index.ts
  experimental/packages/sdk-logs/package.json
  experimental/packages/sdk-logs/src/LogRecord.ts
  experimental/packages/sdk-logs/src/export/ReadableLogRecord.ts
  experimental/packages/sdk-logs/test/common/utils.ts
Labels: release:next-minor-version

#3846 fix: missing `entryPoints` in tsconfig.json
  tsconfig.json
Labels: Skip Changelog

#3868 chore(renovate): improve PR grouping and add @pichlermarc to assignees
  .github/workflows/docs.yaml
  experimental/backwards-compatibility/node14/index.ts
  experimental/backwards-compatibility/node14/package.json
  experimental/backwards-compatibility/node14/tsconfig.json
  experimental/backwards-compatibility/node16/index.ts
  experimental/backwards-compatibility/node16/package.json
  experimental/backwards-compatibility/node16/tsconfig.json
  lerna.json
  renovate.json
  scripts/update-ts-configs.js
Labels: internal, Skip Changelog

#3857 fix(npm-scripts): support windows platform using `cross-var`
  api/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: internal, Skip Changelog

#3807 chore(instrumentation-grpc): drop support for `grpc`
  examples/grpc/README.md
  examples/grpc/client.js
  examples/grpc/helloworld_grpc_pb.js
  examples/grpc/helloworld_pb.js
  examples/grpc/images/jaeger.png
  examples/grpc/images/zipkin.png
  examples/grpc/package.json
  examples/grpc/server.js
  examples/grpc/tracer.js
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-grpc/README.md
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/clientUtils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/clientUtils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/serverUtils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/types.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/internal-types.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/test/grpc.test.ts
  experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
  experimental/packages/opentelemetry-instrumentation-grpc/test/utils/assertionUtils.ts
Labels: release:next-minor-version

#3847 fix: align dependency versions
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: Skip Changelog

#3905 chore(deps): update dependency prettier to v2.8.8
  experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
  experimental/packages/opentelemetry-instrumentation/src/types_internal.ts
  experimental/packages/otlp-grpc-exporter-base/.eslintignore
  package.json
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-semantic-conventions/src/resource/SemanticResourceAttributes.ts
  packages/opentelemetry-semantic-conventions/src/trace/SemanticAttributes.ts
Labels: dependencies, internal, Skip Changelog

#3909 chore: add lerna to devDependencies in all packages
  api/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: dependencies, internal

#3924 chore: fix misaligned dependency versions
  examples/esm-http-ts/package.json
  experimental/packages/otlp-transformer/package.json
Labels: dependencies, internal, Skip Changelog

#3926 chore: bump lerna to 7.0.2, add @lerna/legacy-package-management
  api/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: Skip Changelog

#3937 fix(otlp-proto-exporter-base): add missing type import
  experimental/CHANGELOG.md
  experimental/packages/otlp-proto-exporter-base/src/platform/util.ts
Labels: bug, priority:p1, release:next-minor-version

#3923 fix(selenium-tests): restore tests to functional state
  selenium-tests/babel.config.js
  selenium-tests/pages/fetch/index.js
  selenium-tests/pages/xhr/index.js
  selenium-tests/tests-helpers/constants.js
  selenium-tests/webpack.common.js
Labels: internal, Skip Changelog

#3934 fix(sdk-metrics): preserve startTime for cumulative ExponentialHistograms
  CHANGELOG.md
  packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts
  packages/sdk-metrics/test/aggregator/ExponentialHistogram.test.ts
  packages/sdk-metrics/test/regression/cumulative-exponential-histogram.test.ts
Labels: bug, priority:p2, release:next-minor-version

#3915 LowMemory metrics temporality preference
  CHANGELOG.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/OTLPMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterOptions.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/CollectorMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts
Labels: release:next-minor-version
