Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-12, with the labels that each got.

#4271 ci(opentelemetry-core): add npm cache in actions/setup-node@v3
  .github/workflows/benchmark.yml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  .github/workflows/w3c-integration-test.yml
Labels: Skip Changelog

#4359 chore(ci): use node 20 in lint workflow
  .github/workflows/lint.yml
Labels: internal, Skip Changelog

#4211 fix(otlp-exporter-base): decrease default concurrency limit
  CHANGELOG.md
  experimental/packages/otlp-exporter-base/src/OTLPExporterBase.ts
Labels: bug, priority:p1, pkg:otlp-exporter-base

#4361 chore(deps): use actions/checkout >4 instead of 4.0.0 exactly
  .github/workflows/unit-test.yml
Labels: internal, Skip Changelog

#4340 chore(deps): update webpack to latest
  api/package.json
  api/test/tree-shaking/tree-shaking.test.ts
  examples/opentelemetry-web/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-logs/package.json
  package-lock.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
  renovate.json
  selenium-tests/package.json
Labels: Skip Changelog

#4349 fix(sdk-logs): await async resources in log processors
  experimental/CHANGELOG.md
  experimental/packages/sdk-logs/package.json
  experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts
  experimental/packages/sdk-logs/src/export/SimpleLogRecordProcessor.ts
  experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts
  experimental/packages/sdk-logs/test/common/export/SimpleLogRecordProcessor.test.ts
  experimental/packages/sdk-logs/test/common/export/TestExporterWithDelay.ts
  package-lock.json
Labels: pkg:sdk-logs

#4223 feat(sdk-trace-base): improve log messages when dropping span events
  CHANGELOG.md
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: sdk:traces

#4377 fix(benchmark): bring back accidentally deleted data
  benchmarks/data.js
Labels: document, Skip Changelog

#4376 fix(ci): ensure deploy workflow does not override benchmark data
  .github/workflows/docs.yaml
Labels: internal, Skip Changelog

#4379 fix(instrumentation): bump import-in-the-middle to 1.7.2
  experimental/packages/opentelemetry-instrumentation/package.json
  package-lock.json
Labels: dependencies

#4380 fix(instrumentation): use caret range on import-in-the-middle
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation/package.json
  package-lock.json
Labels: pkg:instrumentation
