Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-07, with the labels that each got.

#3938 docs(otlp-exporters): update docs to reflect OTLP 0.20.0 is used
  experimental/packages/exporter-logs-otlp-grpc/README.md
  experimental/packages/exporter-logs-otlp-http/README.md
  experimental/packages/exporter-logs-otlp-proto/README.md
  experimental/packages/exporter-trace-otlp-grpc/README.md
  experimental/packages/exporter-trace-otlp-http/README.md
  experimental/packages/exporter-trace-otlp-proto/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/README.md
Labels: document, Skip Changelog, release:next-minor-version

#3918 chore: replace istanbul-instrumenter-loader with maintained component
  .nycrc
  api/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-logs/package.json
  karma.base.js
  karma.webpack.js
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
  tsconfig.tsbuildinfo
Labels: dependencies, internal, Skip Changelog

#3979 docs(api-logs): add disclaimers
  experimental/packages/api-logs/README.md
Labels: document, Skip Changelog

#3987 chore: apply update-ts-configs
  experimental/packages/opentelemetry-sdk-node/tsconfig.json
Labels: Skip Changelog
