Repository open-telemetry/opentelemetry-js, pull requests merged in 2023-11, with the labels that each got.

#4233 docs: fixed link to benchmark results
  doc/contributing/benchmark-tests.md
Labels: Skip Changelog

#4268 docs: add docker-compose to run prometheus for the experimental example
  experimental/examples/prometheus/README.md
  experimental/examples/prometheus/docker-compose.yaml
  experimental/examples/prometheus/prometheus.docker.yml
Labels: document, Skip Changelog

#4275 chore: fix npm release preparation scripts, add .npmrc and release script
  .npmrc
  package.json
Labels: internal, Skip Changelog

#4302 Execute binaries from root node modules
  scripts/generate-protos.js
Labels: Skip Changelog

#4304 [next] Execute binaries from root node modules
  scripts/generate-protos.js
Labels: Skip Changelog

#4311 Add Trent Mick to approvers
  README.md
Labels: Skip Changelog

#4308 [next] merge main
  .npmrc
  api/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-proto-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  package-lock.json
  package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  selenium-tests/package.json
Labels: Skip Changelog

#4276 chore(renovate): require dashboard approval for lerna updates
  renovate.json
Labels: internal, Skip Changelog

#4270 chore(ci): install semver globally to speed up "peer-api" workflow
  .github/workflows/peer-api.yml
Labels: Skip Changelog

#4329 fix(ci): remove token setup via environment variable from .npmrc
  .npmrc
Labels: internal, Skip Changelog

#4315 feat: add script to update changelogs on release preparation
  CHANGELOG.md
  experimental/CHANGELOG.md
  package.json
  scripts/update-changelog.js
Labels: internal
