Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-05, with the labels that each got.

#4686 doc: update legendecas affiliation
  README.md
Labels: Skip Changelog

#4688 chore: remove obsolete submodules
  .gitmodules
Labels: Skip Changelog

#4684 chore(renovate): remove import-in-the-middle from the all-patch ignore list
  renovate.json
Labels: internal, Skip Changelog

#4714 chore: fix personal info in README
  README.md
Labels: Skip Changelog

#4726 docs: fix code example in README
  packages/sdk-metrics/README.md
Labels: Skip Changelog

#4723 docs: fix instrumentation-graphql package name in documentation
  packages/opentelemetry-sdk-trace-node/README.md
Labels: Skip Changelog

#4510 chore(deps): remove unused cpx dependencies and update used ones to cpx2
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-instrumentation/test/node/RequireInTheMiddleSingleton.test.ts
  experimental/packages/otlp-grpc-exporter-base/package.json
  package-lock.json
Labels: dependencies, Skip Changelog

#4732 fix(deps): remove protobufjs from grpc-base (otlp-transformer used instead), update protobufjs (security)
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  package-lock.json
Labels: dependencies, Skip Changelog
