Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-12, with the labels that each got.

#5227 fix: de-confuse Nuxt build tooling by not using 'export *' in comments
  experimental/CHANGELOG.md
  experimental/packages/exporter-logs-otlp-grpc/src/index.ts
  experimental/packages/exporter-trace-otlp-grpc/src/index.ts
  experimental/packages/exporter-trace-otlp-http/src/index.ts
  experimental/packages/exporter-trace-otlp-http/src/platform/browser/index.ts
  experimental/packages/exporter-trace-otlp-http/src/platform/index.ts
  experimental/packages/exporter-trace-otlp-http/src/platform/node/index.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/src/index.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/index.ts
  experimental/packages/opentelemetry-sdk-node/src/index.ts
Labels: bug

#5200 feat(otlp-transformer)!: remove internal types and functions from public API
  experimental/CHANGELOG.md
  experimental/packages/otlp-transformer/README.md
  experimental/packages/otlp-transformer/src/index.ts
  experimental/packages/otlp-transformer/src/json/serializers.ts
  experimental/packages/otlp-transformer/src/protobuf/serializers.ts
  experimental/packages/otlp-transformer/test/common.test.ts
  experimental/packages/otlp-transformer/test/logs.test.ts
  experimental/packages/otlp-transformer/test/metrics.test.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
Labels: pkg:otlp-transformer

#5237 ci: run browser and worker tests on Node.js 22
  .github/workflows/unit-test.yml
Labels: internal, Skip Changelog

#5246 docs: document compatible versions
  README.md
Labels: document, Skip Changelog

#5248 docs: re-categoize misplaced changelog entry
  CHANGELOG.md
Labels: document, Skip Changelog

#5261 chore: update prettier to 3.4.2
  package-lock.json
  package.json
Labels: Skip Changelog

#5277 fix(ci): adapt workflow to use supported npm versions
  .github/workflows/benchmark.yml
  .github/workflows/unit-test.yml
Labels: Skip Changelog

#5279 chore: removed circular dependency from BasicTracerProvider
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
Labels: Skip Changelog

#5276 ci: prepare release script to run on v1.x branch
  .github/workflows/create-or-update-release-pr.yml
  doc/contributing/releasing.md
  package.json
Labels: Skip Changelog

#5287 chore: update supported versions in 2.0 README
  README.md
Labels: document, Skip Changelog
