Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-06, with the labels that each got.

#4753 refactor(examples/https): use new exported string constants for semconv
  examples/https/tracer.js
Labels: Skip Changelog

#4754 docs(instrumentation-http): remove semconv key column from readme
  experimental/packages/opentelemetry-instrumentation-http/README.md
Labels: Skip Changelog

#4757 chore: move flarna from approver to emeritus
  README.md
Labels: Skip Changelog

#4769 fix(sdk-logs): adapt versions for release
  experimental/packages/sdk-logs/package.json
  package-lock.json
Labels: Skip Changelog

#4766 chore: add @david-luna to approvers
  README.md
Labels: Skip Changelog

#4765 chore: move haddasbronfman from approver to emeritus
  README.md
Labels: Skip Changelog

#4797 docs: usage of SEMRESATTRS_XXXXX
  .github/ISSUE_TEMPLATE/bug_report.yaml
  README.md
  experimental/packages/opentelemetry-browser-detector/README.md
Labels: Skip Changelog

#4798 docs: add SimpleSpanProcessor warning
  packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
Labels: Skip Changelog

#4532 feat(sdk-metrics)!: replace attributeKeys with custom processors option
  CHANGELOG_NEXT.md
  packages/sdk-metrics/src/index.ts
  packages/sdk-metrics/src/state/AsyncMetricStorage.ts
  packages/sdk-metrics/src/state/MeterSharedState.ts
  packages/sdk-metrics/src/state/SyncMetricStorage.ts
  packages/sdk-metrics/src/view/AttributesProcessor.ts
  packages/sdk-metrics/src/view/View.ts
  packages/sdk-metrics/test/MeterProvider.test.ts
  packages/sdk-metrics/test/state/AsyncMetricStorage.test.ts
  packages/sdk-metrics/test/state/SyncMetricStorage.test.ts
  packages/sdk-metrics/test/view/AttributesProcessor.test.ts
  packages/sdk-metrics/test/view/View.test.ts
Labels: pkg:sdk-metrics, target:next-major-release

#4793 feat: add release-pr update chores as scripts to package.json
  package.json
  scripts/extract-latest-release-notes.js
Labels: internal, Skip Changelog

#4821 chore: add @maryliag to triagers
  README.md
Labels: Skip Changelog

#4824 chore: add @JamieDanielson to maintainers
  README.md
Labels: Skip Changelog
