Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-08, with the labels that each got.

#4849 feat: add release PR workflow
  .github/workflows/create-or-update-release-pr.yml
  doc/contributing/releasing.md
  package.json
Labels: Skip Changelog

#4900 Sync package-lock.json
  package-lock.json
Labels: Skip Changelog

#4889 fix(otlp-exporter-base)!: ensure we do not retry after the timeout has elapsed
  experimental/packages/otlp-exporter-base/src/exporter-transport.ts
  experimental/packages/otlp-exporter-base/src/platform/node/OTLPExporterNodeBase.ts
  experimental/packages/otlp-exporter-base/src/platform/node/http-exporter-transport.ts
  experimental/packages/otlp-exporter-base/src/platform/node/http-transport-types.ts
  experimental/packages/otlp-exporter-base/src/platform/node/http-transport-utils.ts
  experimental/packages/otlp-exporter-base/src/retrying-transport.ts
  experimental/packages/otlp-exporter-base/test/common/retrying-transport.test.ts
  experimental/packages/otlp-grpc-exporter-base/src/OTLPGRPCExporterNodeBase.ts
  experimental/packages/otlp-grpc-exporter-base/src/grpc-exporter-transport.ts
  experimental/packages/otlp-grpc-exporter-base/test/grpc-exporter-transport.test.ts
Labels: bug, Skip Changelog, target:next-minor-release

#4893 fix(api-logs): align AnyValue to spec
  experimental/CHANGELOG.md
  experimental/packages/api-logs/src/types/AnyValue.ts
Labels: bug, pkg:api-logs, target:next-minor-release

#4906 docs(api): add `@since` annotations to all types
  api/src/api/context.ts
  api/src/api/diag.ts
  api/src/api/propagation.ts
  api/src/api/trace.ts
  api/src/baggage/types.ts
  api/src/baggage/utils.ts
  api/src/common/Attributes.ts
  api/src/common/Exception.ts
  api/src/common/Time.ts
  api/src/context-api.ts
  api/src/context/context.ts
  api/src/context/types.ts
  api/src/diag-api.ts
  api/src/diag/consoleLogger.ts
  api/src/diag/types.ts
  api/src/metrics-api.ts
  api/src/metrics/Meter.ts
  api/src/metrics/MeterProvider.ts
  api/src/metrics/Metric.ts
  api/src/metrics/NoopMeter.ts
  api/src/metrics/ObservableResult.ts
  api/src/propagation-api.ts
  api/src/propagation/TextMapPropagator.ts
  api/src/trace-api.ts
  api/src/trace/ProxyTracer.ts
  api/src/trace/ProxyTracerProvider.ts
  api/src/trace/Sampler.ts
  api/src/trace/SamplingResult.ts
  api/src/trace/SpanOptions.ts
  api/src/trace/attributes.ts
  api/src/trace/internal/utils.ts
  api/src/trace/invalid-span-constants.ts
  api/src/trace/link.ts
  api/src/trace/span.ts
  api/src/trace/span_context.ts
  api/src/trace/span_kind.ts
  api/src/trace/spancontext-utils.ts
  api/src/trace/status.ts
  api/src/trace/trace_flags.ts
  api/src/trace/trace_state.ts
  api/src/trace/tracer.ts
  api/src/trace/tracer_options.ts
  api/src/trace/tracer_provider.ts
Labels: Skip Changelog

#4929 fix(otlp-exporter-base): fix handling of destroyed requests
  experimental/packages/exporter-trace-otlp-http/test/node/CollectorTraceExporter.test.ts
  experimental/packages/otlp-exporter-base/src/platform/node/http-transport-utils.ts
  experimental/packages/otlp-exporter-base/src/platform/node/util.ts
  experimental/packages/otlp-exporter-base/test/node/http-exporter-transport.test.ts
Labels: bug, Skip Changelog, priority:p3

#4937 chore(release): script to align workspace on new semconv package version
  package-lock.json
  package.json
  scripts/align-semconv-deps.js
Labels: Skip Changelog

#4935 fix(sdk-metrics): use inclusive upper bounds in histogram
  CHANGELOG.md
  packages/sdk-metrics/src/aggregator/Histogram.ts
  packages/sdk-metrics/src/aggregator/types.ts
  packages/sdk-metrics/src/utils.ts
  packages/sdk-metrics/test/Instruments.test.ts
  packages/sdk-metrics/test/aggregator/Histogram.test.ts
  packages/sdk-metrics/test/utils.test.ts
Labels: sdk:metrics

#4953 test(exporter-logs-otlp-grpc): improve error reporting in particular test failure
  experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts
Labels: Skip Changelog

#4876 docs: Describe support for ESM
  README.md
  doc/esm-support.md
  experimental/packages/opentelemetry-instrumentation/README.md
  experimental/packages/opentelemetry-sdk-node/README.md
  packages/opentelemetry-sdk-trace-node/README.md
Labels: Skip Changelog

#4957 chore: pin unit test to node 22.6 until 22.8 is available
  .github/workflows/unit-test.yml
Labels: Skip Changelog

#4956 docs: document console exporter output stability
  experimental/packages/sdk-logs/src/export/ConsoleLogRecordExporter.ts
  packages/opentelemetry-sdk-trace-base/src/export/ConsoleSpanExporter.ts
  packages/sdk-metrics/src/export/ConsoleMetricExporter.ts
Labels: document, Skip Changelog

#4961 chore(deps): update dependency webpack to v5.94.0
  api/package.json
  api/test/tree-shaking/tree-shaking.test.ts
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  package-lock.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/propagator-aws-xray/package.json
  packages/sdk-metrics/package.json
  selenium-tests/package.json
Labels: dependencies
