Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-02, with the labels that each got.

#4467 fix(instrumentation): normalize paths for internal files in scoped packages
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
  experimental/packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/scoped-test-module/package.json
  experimental/packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/scoped-test-module/src/index.js
  experimental/packages/opentelemetry-instrumentation/test/node/node_modules/@opentelemetry/scoped-test-module/src/internal.js
  experimental/packages/opentelemetry-instrumentation/test/node/scoped-package-instrumentation.test.ts
Labels: bug, priority:p2, pkg:instrumentation

#4477 docs: Update getting started link in README
  README.md
Labels: Skip Changelog

#4497 Add @david-luna to triagers
  README.md
Labels: Skip Changelog

#4515 fix(instrumentation): remove peer-dependency on @opentelemetry/api-logs
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation/package.json
  package-lock.json
Labels: bug, priority:p1
