Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-07, with the labels that each got.

#4840 chore: drop ts-mocha for mocha and ts-node
  .github/workflows/unit-test.yml
  .mocharc.yml
  api/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/propagator-aws-xray-lambda/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  package-lock.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-semantic-conventions/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/propagator-aws-xray/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: dependencies, Skip Changelog

#4768 docs(opentelemetry-browser-detector): Use tree-shakeable string constants for semconv in Readme
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-browser-detector/tsconfig.esm.json
  experimental/packages/opentelemetry-browser-detector/tsconfig.esnext.json
  experimental/packages/opentelemetry-browser-detector/tsconfig.json
  package-lock.json
Labels: Skip Changelog

#4855 docs(opentelemtry-instrumentation): fix reversed jsdoc comment
  experimental/packages/opentelemetry-instrumentation/src/instrumentation.ts
Labels: Skip Changelog

#4643 feat(http): Allow to opt-out of instrumenting incoming/outgoing requests
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-http/README.md
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  experimental/packages/opentelemetry-instrumentation-http/src/types.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
Labels: enhancement
