Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-03, with the labels that each got.

#4522 fix: ConsoleMetricExporter Should Not Export Shallowly
  CHANGELOG.md
  packages/sdk-metrics/src/export/ConsoleMetricExporter.ts
Labels: bug, priority:p4

#4513 chore(renovate): remove import-in-the-middle from all-patch group
  renovate.json
Labels: internal, Skip Changelog

#4530 docs: spelling corrections
  CONTRIBUTING.md
  api/README.md
  api/test/common/metrics/Metric.test.ts
  doc/upgrade-guide.md
  experimental/packages/opentelemetry-browser-detector/README.md
  experimental/packages/opentelemetry-browser-detector/src/types.ts
  experimental/packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/clientUtils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
  experimental/packages/opentelemetry-instrumentation-http/README.md
  experimental/packages/opentelemetry-instrumentation-http/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
  experimental/packages/opentelemetry-instrumentation/README.md
  experimental/packages/opentelemetry-sdk-node/README.md
  experimental/packages/opentelemetry-sdk-node/test/TracerProviderWithEnvExporter.test.ts
  experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
  experimental/packages/otlp-exporter-base/test/common/util.test.ts
  experimental/packages/shim-opencensus/src/ShimTracer.ts
  packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts
  packages/opentelemetry-core/src/internal/exporter.ts
  packages/opentelemetry-core/test/common/time.test.ts
  packages/opentelemetry-exporter-jaeger/src/types.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/README.md
  packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-resources/src/detectors/EnvDetectorSync.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/InMemorySpanExporter.test.ts
  packages/opentelemetry-sdk-trace-web/README.md
  packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts
  packages/sdk-metrics/src/exemplar/ExemplarReservoir.ts
  scripts/semconv/templates/SemanticAttributes.ts.j2
Labels: Skip Changelog

#4540 fix(exporters): use parseHeaders() to ensure header-values are not 'undefined'
  experimental/CHANGELOG.md
  experimental/packages/exporter-logs-otlp-http/src/platform/node/OTLPLogExporter.ts
  experimental/packages/exporter-logs-otlp-proto/src/platform/node/OTLPLogExporter.ts
  experimental/packages/exporter-trace-otlp-http/src/platform/node/OTLPTraceExporter.ts
  experimental/packages/exporter-trace-otlp-proto/src/platform/node/OTLPTraceExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/src/OTLPMetricExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/node/OTLPMetricExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/OTLPMetricExporter.ts
  experimental/packages/otlp-exporter-base/src/util.ts
  experimental/packages/otlp-exporter-base/test/common/util.test.ts
Labels: bug, priority:p1, pkg:exporter-trace-otlp-http, pkg:exporter-trace-otlp-proto, pkg:exporter-metrics-otlp-http, pkg:exporter-metrics-otlp-proto

#4521 SBOM workflow using "npm sbom"
  .github/workflows/sbom.yml
Labels: Skip Changelog

#4571 feat(opentelemetry-instrumentation-xhr): optionally ignore network events
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-xml-http-request/README.md
  experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
  experimental/packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Labels: pkg:instrumentation-xml-http-request
