Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-04, with the labels that each got.

#4600 feat(otlp-transformer): consolidate scope/resource creation in transformer
  experimental/CHANGELOG.md
  experimental/packages/otlp-transformer/src/common/internal.ts
  experimental/packages/otlp-transformer/src/logs/index.ts
  experimental/packages/otlp-transformer/src/metrics/internal.ts
  experimental/packages/otlp-transformer/src/resource/internal.ts
  experimental/packages/otlp-transformer/src/trace/index.ts
  experimental/packages/otlp-transformer/test/logs.test.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
Labels: pkg:otlp-transformer

#4620 test(exporter-*-grpc): use RegExp to match Deadline Exceeded error
  experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts
  experimental/packages/exporter-trace-otlp-grpc/test/OTLPTraceExporter.test.ts
  package-lock.json
Labels: Skip Changelog

#4624 doc(instr-fetch): mention instr-undici for Node.js fetch()
  experimental/packages/opentelemetry-instrumentation-fetch/README.md
Labels: Skip Changelog

#4612 fix(otlp-grpc-exporter-base): avoid TypeError on exporter shutdown
  experimental/CHANGELOG.md
  experimental/packages/otlp-grpc-exporter-base/src/grpc-exporter-transport.ts
  experimental/packages/otlp-grpc-exporter-base/test/grpc-exporter-transport.test.ts
Labels: bug, priority:p1, pkg:exporter-trace-otlp-grpc, pkg:exporter-metrics-otlp-grpc, pkg:exporter-logs-otlp-grpc

#4628 chore(renovate): enable lock file maintainance
  renovate.json
Labels: dependencies, internal, Skip Changelog

#4623 fix: ensure api is not dropped from workspaces in package-lock.json
  package.json
Labels: internal, Skip Changelog

#4640 fix: revert modifications to Apache license
  experimental/packages/opentelemetry-sdk-node/LICENSE
  experimental/packages/otlp-exporter-base/LICENSE
  packages/opentelemetry-resources/LICENSE
  packages/opentelemetry-semantic-conventions/LICENSE
  packages/propagator-aws-xray/LICENSE
Labels: Skip Changelog

#4649 fix(core): align inconsistent behavior of getEnv() and getEnvWithoutDefaults() when a process polyfill is used
  CHANGELOG.md
  packages/opentelemetry-core/src/platform/browser/environment.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/node/environment.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-core/src/utils/environment.ts
Labels: bug
