Repository open-telemetry/opentelemetry-js, pull requests merged in 2024-10, with the labels that each got.

#5034 fix(sdk-node): use warn instead of error on unknown OTEL_NODE_RESOURCE_DETECTORS values
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/src/utils.ts
Labels: bug, priority:p4, pkg:sdk-node

#5040 docs: use npm ci in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: document, Skip Changelog

#4931 feat(sdk-metrics)!: drop View and Aggregation for options
  CHANGELOG_NEXT.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts
  experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts
  experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/opentelemetry-sdk-node/src/types.ts
  experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
  packages/sdk-metrics/src/MeterProvider.ts
  packages/sdk-metrics/src/export/AggregationSelector.ts
  packages/sdk-metrics/src/export/MetricExporter.ts
  packages/sdk-metrics/src/export/MetricReader.ts
  packages/sdk-metrics/src/index.ts
  packages/sdk-metrics/src/state/MeterProviderSharedState.ts
  packages/sdk-metrics/src/view/Aggregation.ts
  packages/sdk-metrics/src/view/AggregationOption.ts
  packages/sdk-metrics/src/view/View.ts
  packages/sdk-metrics/test/MeterProvider.test.ts
  packages/sdk-metrics/test/export/MetricReader.test.ts
  packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
  packages/sdk-metrics/test/export/utils.ts
  packages/sdk-metrics/test/regression/cumulative-exponential-histogram.test.ts
  packages/sdk-metrics/test/regression/histogram-recording-nan.test.ts
  packages/sdk-metrics/test/state/MeterSharedState.test.ts
  packages/sdk-metrics/test/view/Aggregation.test.ts
  packages/sdk-metrics/test/view/View.test.ts
  packages/sdk-metrics/test/view/ViewRegistry.test.ts
Labels: target:next-major-release

#5053 ci: use codecov token when uploading reports
  .github/workflows/unit-test.yml
Labels: Skip Changelog

#5056 Added custom test instructions for browser-specific tests
  CONTRIBUTING.md
Labels: Skip Changelog

#5067 ci: add workflow to publish packages to npm
  .github/workflows/publish-to-npm.yml
Labels: Skip Changelog

#5071 test: use venv in w3c trace context test script
  integration-tests/tracecontext-integration-test.sh
Labels: Skip Changelog

#5074 chore: add markdown lint check to default lint command
  .github/workflows/lint.yml
  CONTRIBUTING.md
  package.json
Labels: Skip Changelog

#5048 refactor(sdk-trace-base)!: remove Span class from exports
  CHANGELOG_NEXT.md
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/src/Tracer.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/SimpleSpanProcessor.test.ts
  packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: target:next-major-release

#5081 fix(instrumentation-http): add server attributes after they become available
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  experimental/packages/opentelemetry-instrumentation-http/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts
Labels: Skip Changelog

#5072 Added limitation in ot-shim readme
  packages/opentelemetry-shim-opentracing/README.md
Labels: document, Skip Changelog, pkg:shim-opentracing

#5083 chore: add @maryliag to approvers
  README.md
Labels: Skip Changelog
