Repository open-telemetry/opentelemetry-js, pull requests merged in 2025-05, with the labels that each got.

#5641 chore: add @JacksonWeber to triagers
  README.md
Labels: Skip Changelog

#5654 feat(semantic-conventions): update semantic conventions to v1.33.0
  scripts/semconv/generate.sh
  semantic-conventions/CHANGELOG.md
  semantic-conventions/src/experimental_attributes.ts
  semantic-conventions/src/experimental_metrics.ts
  semantic-conventions/src/stable_attributes.ts
  semantic-conventions/src/stable_metrics.ts
Labels: pkg:semantic-conventions

#5656 chore: temporarily disable github link checking
  package.json
Labels: Skip Changelog

#5664 docs: update old/deprecated 'SemanticAttributes' usage
  doc/metrics.md
  doc/tracing.md
Labels: Skip Changelog

#5673 refactor(exporter-zipkin): update semconv usage to ATTR_ exports
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
Labels: Skip Changelog

#5674 refactor(shim-opentracing): update semconv usage to ATTR_ exports
  packages/opentelemetry-shim-opentracing/src/shim.ts
  packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Labels: Skip Changelog

#5675 refactor(exporter-prometheus): update semconv usage to ATTR_ exports
  experimental/packages/opentelemetry-exporter-prometheus/test/util.ts
Labels: Skip Changelog

#5670 refactor(sdk-trace-node): update semconv usage to ATTR_ exports
  packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
Labels: Skip Changelog

#5687 refactor(semantic-conventions): weaver 0.13.0 supports a 'stable_only' arg to semconv_attributes
  scripts/semconv/templates/registry/stable/weaver.yaml
Labels: Skip Changelog

#5688 refactor(semantic-conventions): tweak the leading spacing of comments on enum values
  scripts/semconv/templates/registry/stable/attributes.ts.j2
  semantic-conventions/src/experimental_attributes.ts
  semantic-conventions/src/stable_attributes.ts
Labels: Skip Changelog

#5689 refactor(semantic-conventions): use weaver 'file_name' template config
  scripts/semconv/templates/registry/stable/attributes.ts.j2
  scripts/semconv/templates/registry/stable/metrics.ts.j2
  scripts/semconv/templates/registry/stable/weaver.yaml
Labels: Skip Changelog

#5699 chore(opentelemetry-instrumentation-http): Fix link to docs
  experimental/packages/opentelemetry-instrumentation-http/src/types.ts
Labels: Skip Changelog

#5702 test(instrumentation-fetch): pin msw dep to avoid breakage in msw@2.8
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/test/mockServiceWorker.js
  package-lock.json
Labels: Skip Changelog

#5709 chore(deps): update to msw@2.8.4
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  karma.webpack.js
  package-lock.json
Labels: dependencies, Skip Changelog

#5725 docs: fix typo in 'http/dup' value to use with OTEL_SEMCONV_STABILITY_OPT_IN envvar
  experimental/packages/opentelemetry-instrumentation-grpc/README.md
  experimental/packages/opentelemetry-instrumentation-http/README.md
Labels: Skip Changelog
