Repository open-telemetry/opentelemetry-js, pull requests merged in 2025-04, with the labels that each got.

#5579 fix(exporter-oltp-metrics-*): Remove forceFlush
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/OTLPMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/OTLPMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/OTLPMetricExporter.test.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts
Labels: Skip Changelog

#5585 test(@opentelemetry/sdk-trace-web): refactor tests to allow use of mocha context
  packages/opentelemetry-sdk-trace-web/test/NodeGlobalsFoolProofing.test.ts
  packages/opentelemetry-sdk-trace-web/test/StackContextManager.test.ts
  packages/opentelemetry-sdk-trace-web/test/WebTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-web/test/registration.test.ts
  packages/opentelemetry-sdk-trace-web/test/utils.test.ts
  packages/opentelemetry-sdk-trace-web/test/window/utils.test.ts
Labels: Skip Changelog

#5584 test(@opentelemetry/api): refactor tests to allow use of mocha context
  api/test/common/api/api.test.ts
  api/test/common/baggage/Baggage.test.ts
  api/test/common/context/NoopContextManager.test.ts
  api/test/common/diag/ComponentLogger.test.ts
  api/test/common/diag/consoleLogger.test.ts
  api/test/common/diag/logLevel.test.ts
  api/test/common/diag/logger.test.ts
  api/test/common/experimental/trace/SugaredTracer.test.ts
  api/test/common/internal/global.test.ts
  api/test/common/internal/semver.test.ts
  api/test/common/metrics/Metric.test.ts
  api/test/common/noop-implementations/noop-meter.test.ts
  api/test/common/noop-implementations/noop-span.test.ts
  api/test/common/noop-implementations/noop-tracer-provider.test.ts
  api/test/common/noop-implementations/noop-tracer.test.ts
  api/test/common/proxy-implementations/proxy-tracer.test.ts
  api/test/common/trace/spancontext-utils.test.ts
  api/test/common/trace/tracestate-validators.test.ts
  api/test/common/trace/tracestate.test.ts
Labels: Skip Changelog

#5581 refactor(resources): replace deprecated semconv consts
  packages/opentelemetry-resources/src/detectors/platform/node/HostDetector.ts
  packages/opentelemetry-resources/src/detectors/platform/node/OSDetector.ts
  packages/opentelemetry-resources/src/detectors/platform/node/ProcessDetector.ts
  packages/opentelemetry-resources/src/detectors/platform/node/ServiceInstanceIdDetector.ts
  packages/opentelemetry-resources/src/semconv.ts
Labels: Skip Changelog

#5587 test(@opentelemetry/sdk-trace-node): refactor tests to allow use of mocha context
  packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-node/test/registration.test.ts
Labels: Skip Changelog

#5586 fix(examples): use correct node tracer provider function
  examples/otlp-exporter-node/package.json
  examples/otlp-exporter-node/tracing.js
Labels: Skip Changelog

#5588 feat(@opentelemetry/sdk-logs): align LoggerProvider constructor options with Trace and Metrics SDK
  experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts
  experimental/packages/exporter-logs-otlp-http/test/browser/OTLPLogExporter.test.ts
  experimental/packages/exporter-logs-otlp-http/test/node/OTLPLogExporter.test.ts
  experimental/packages/exporter-logs-otlp-proto/test/browser/OTLPLogExporter.test.ts
  experimental/packages/exporter-logs-otlp-proto/test/node/OTLPLogExporter.test.ts
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/sdk-logs/src/LoggerProvider.ts
  experimental/packages/sdk-logs/src/internal/LoggerProviderSharedState.ts
  experimental/packages/sdk-logs/src/types.ts
  experimental/packages/sdk-logs/test/common/LogRecord.test.ts
  experimental/packages/sdk-logs/test/common/Logger.test.ts
  experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts
  experimental/packages/sdk-logs/test/common/MultiLogRecordProcessor.test.ts
  experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts
  experimental/packages/sdk-logs/test/common/export/ConsoleLogRecordExporter.test.ts
  experimental/packages/sdk-logs/test/common/export/InMemoryLogRecordExporter.test.ts
  experimental/packages/sdk-logs/test/common/export/SimpleLogRecordProcessor.test.ts
  experimental/packages/web-common/test/SessionLogRecordProcessor.test.ts
Labels: Skip Changelog

#5591 refactor(instrumentation): change tests to allow use of mocha context
  experimental/packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
  experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
  experimental/packages/opentelemetry-instrumentation/test/common/semver.test.ts
  experimental/packages/opentelemetry-instrumentation/test/common/utils.test.ts
  experimental/packages/opentelemetry-instrumentation/test/node/InstrumentationBase.test.ts
  experimental/packages/opentelemetry-instrumentation/test/node/InstrumentationNodeModuleFile.test.ts
  experimental/packages/opentelemetry-instrumentation/test/node/ModuleNameTrie.test.ts
  experimental/packages/opentelemetry-instrumentation/test/node/RequireInTheMiddleSingleton.test.ts
Labels: Skip Changelog

#5578 refactor(opentelemetry-sdk-node): use new get*FromEnv() function in NodeSDK's metrics setup
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
Labels: Skip Changelog

#5604 docs: update from deprecated SEMRESATTRS_SERVICE_NAME to ATTR_SERVICE_NAME
  .github/ISSUE_TEMPLATE/bug_report.yaml
  examples/basic-tracer-node/index.js
  examples/esm-http-ts/index.ts
  examples/grpc-js/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/opentelemetry-web/examples/fetch-proto/index.js
  examples/opentelemetry-web/examples/fetch/index.js
  examples/opentelemetry-web/examples/fetchXhr/index.js
  examples/opentelemetry-web/examples/fetchXhrB3/index.js
  examples/opentelemetry-web/examples/xml-http-request/index.js
  examples/opentelemetry-web/examples/zipkin/index.js
  examples/opentracing-shim/shim.js
  examples/otlp-exporter-node/metrics.js
  examples/otlp-exporter-node/tracing.js
  experimental/examples/opencensus-shim/setup.js
  experimental/packages/opentelemetry-browser-detector/README.md
  packages/opentelemetry-resources/README.md
Labels: Skip Changelog

#5551 fix(otlp-transformer): do not throw when deserializing empty JSON response
  experimental/CHANGELOG.md
  experimental/packages/otlp-transformer/src/logs/json/logs.ts
  experimental/packages/otlp-transformer/src/metrics/json/metrics.ts
  experimental/packages/otlp-transformer/src/trace/json/trace.ts
  experimental/packages/otlp-transformer/test/logs.test.ts
  experimental/packages/otlp-transformer/test/metrics.test.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
Labels: bug, priority:p4, pkg:otlp-transformer

#5613 docs: fix api doc links
  doc/context.md
  doc/metrics.md
  doc/sdk-registration.md
  doc/tracing.md
Labels: document, Skip Changelog

#5606 fix(docs): remove WIP warning on the README
  README.md
Labels: Skip Changelog

#5495 ci: add sdk-v1.x dist-tag when publishing from v1.x
  .github/workflows/publish-to-npm.yml
Labels: Skip Changelog, target:v1.x

#5631 deps(instrumentation): remove unused @types/semver dev-dependency
  experimental/packages/opentelemetry-instrumentation/package.json
  package-lock.json
Labels: Skip Changelog

#5632 chore: add constraint for renovate to use npm@>10.8.0
  renovate.json
Labels: Skip Changelog

#5619 [docs] Upgrade note with Jest version requirements and workaround for older versions of Jest
  doc/frequently-asked-questions.md
Labels: document, Skip Changelog
