Repository open-telemetry/opentelemetry-js, pull requests merged in 2025-03, with the labels that each got.

#5513 doc: upgrade/migration guide for SDK 2.0
  CHANGELOG.md
  README.md
  doc/upgrade-guide.md
  doc/upgrade-to-2.x.md
  experimental/CHANGELOG.md
  package.json
Labels: Skip Changelog, target:next-major-release

#5512 chore: prepare 2.0.0-dev.1/0.200.0-dev.1 pre-release
  examples/esm-http-ts/package.json
  examples/http/package.json
  examples/https/package.json
  examples/opentelemetry-web/package.json
  examples/otlp-exporter-node/package.json
  experimental/backwards-compatibility/node14/package.json
  experimental/backwards-compatibility/node16/package.json
  experimental/examples/events/package.json
  experimental/examples/logs/package.json
  experimental/examples/opencensus-shim/package.json
  experimental/examples/prometheus/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sampler-jaeger-remote/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  experimental/packages/web-common/package.json
  integration-tests/api/package.json
  integration-tests/propagation-validation-server/package.json
  package-lock.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: Skip Changelog

#5524 fix(core): avoid using util in configuration.ts for browser compatibility
  CHANGELOG.md
  packages/opentelemetry-core/src/utils/configuration.ts
Labels: target:next-major-release

#5534 chore: prepare release 2.0.0-rc.1/0.200.0-rc.1
  examples/esm-http-ts/package.json
  examples/http/package.json
  examples/https/package.json
  examples/opentelemetry-web/package.json
  examples/otlp-exporter-node/package.json
  experimental/backwards-compatibility/node14/package.json
  experimental/backwards-compatibility/node16/package.json
  experimental/examples/events/package.json
  experimental/examples/logs/package.json
  experimental/examples/opencensus-shim/package.json
  experimental/examples/prometheus/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sampler-jaeger-remote/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  experimental/packages/web-common/package.json
  integration-tests/api/package.json
  integration-tests/propagation-validation-server/package.json
  package-lock.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: Skip Changelog

#5535 doc: add section to SDK 2.x migration guide for implementors of resource detectors
  doc/upgrade-to-2.x.md
Labels: Skip Changelog

#5521 chore: prepare release 2.0.0/0.200.0
  .github/workflows/docs.yaml
  .github/workflows/publish-to-npm.yml
  CHANGELOG.md
  examples/esm-http-ts/package.json
  examples/http/package.json
  examples/https/package.json
  examples/opentelemetry-web/package.json
  examples/otlp-exporter-node/package.json
  experimental/CHANGELOG.md
  experimental/backwards-compatibility/node14/package.json
  experimental/backwards-compatibility/node16/package.json
  experimental/examples/events/package.json
  experimental/examples/logs/package.json
  experimental/examples/opencensus-shim/package.json
  experimental/examples/prometheus/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sampler-jaeger-remote/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  experimental/packages/web-common/package.json
  integration-tests/api/package.json
  integration-tests/propagation-validation-server/package.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: target:next-major-release

#5542 docs: use ATTR_SERVICE_NAME in readme
  README.md
Labels: Skip Changelog

#5541 docs: clarify that Resource is not user-implementable
  packages/opentelemetry-resources/src/Resource.ts
Labels: document, Skip Changelog

#5553 fix: npm links
  experimental/packages/web-common/README.md
Labels: Skip Changelog
