Repository open-telemetry/opentelemetry-js, pull requests merged in 2025-02, with the labels that each got.

#5408 refactor(instrumentation-grpc): fix eslint warnings
  experimental/packages/opentelemetry-instrumentation-grpc/src/clientUtils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts
  experimental/packages/opentelemetry-instrumentation-grpc/src/serverUtils.ts
  experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
Labels: Skip Changelog

#5391 refactor(otlp-exporter-base): fix eslint warnigns
  experimental/packages/otlp-exporter-base/src/transport/http-exporter-transport.ts
  experimental/packages/otlp-exporter-base/src/transport/http-transport-utils.ts
Labels: Skip Changelog

#5416 test: Test Node.js 23 in CI
  .github/workflows/unit-test.yml
Labels: Skip Changelog

#5417 docs: Fix Markdown typo
  doc/metrics.md
Labels: Skip Changelog

#5385 refactor(sdk-trace-base): fix eslint warnings
  packages/opentelemetry-sdk-trace-base/src/Span.ts
Labels: Skip Changelog

#5425 docs: add 'Contrib Triagers' section to the README
  README.md
Labels: Skip Changelog

#5426 chore: remove obsolete comment
  experimental/packages/exporter-logs-otlp-grpc/src/index.ts
Labels: Skip Changelog

#5383 refactor(resources): fix eslint warning
  packages/opentelemetry-resources/src/utils.ts
Labels: Skip Changelog

#5427 chore(semantic-conventions): whitespace-only fixes in comments from weaver 0.12.0
  scripts/semconv/generate.sh
  semantic-conventions/src/experimental_attributes.ts
  semantic-conventions/src/experimental_metrics.ts
  semantic-conventions/src/stable_attributes.ts
  semantic-conventions/src/stable_metrics.ts
Labels: Skip Changelog, pkg:semantic-conventions

#5402 refactor(instrumentation-xhr): fix eslint warnings
  experimental/packages/opentelemetry-instrumentation-xml-http-request/src/types.ts
  experimental/packages/opentelemetry-instrumentation-xml-http-request/src/utils.ts
  experimental/packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Labels: Skip Changelog

#5434 docs(api): bring back detailed api documentation
  api/package.json
  api/src/experimental/index.ts
  api/src/index.ts
  api/typedoc.json
Labels: document, Skip Changelog

#5444 feat(core)!: remove unused/obsolete functions and types
  CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
  experimental/packages/otlp-exporter-base/src/configuration/otlp-http-env-configuration.ts
  experimental/packages/otlp-grpc-exporter-base/src/configuration/otlp-grpc-env-configuration.ts
  experimental/packages/otlp-transformer/src/common/hex-to-binary.ts
  experimental/packages/otlp-transformer/src/common/utils.ts
  experimental/packages/otlp-transformer/test/common.test.ts
  experimental/packages/otlp-transformer/test/logs.test.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
  experimental/packages/otlp-transformer/test/utils.ts
  integration-tests/api/test/core-entries.test.js
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/platform/browser/hex-to-base64.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/index.ts
  packages/opentelemetry-core/src/platform/node/hex-to-base64.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-core/src/utils/wrap.ts
  packages/opentelemetry-core/test/platform/hex-to-base64.test.ts
  packages/opentelemetry-core/test/utils/wrap.test.ts
  packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
Labels: pkg:core, target:next-major-release

#5432 chore: tweak the section titles for changelogs
  package.json
  scripts/update-changelog.js
Labels: Skip Changelog

#5430 doc: list all current javascript-contrib-triagers members
  README.md
Labels: Skip Changelog

#5446 refactor(web-common): add incubating semconv to package
  experimental/packages/web-common/src/SessionLogRecordProcessor.ts
  experimental/packages/web-common/src/SessionSpanProcessor.ts
  experimental/packages/web-common/src/semconv.ts
Labels: Skip Changelog

#5443 feat(core): add more scalable replacements for getEnv(), getEnvWithoutDefaults()
  CHANGELOG.md
  packages/opentelemetry-core/karma.conf.js
  packages/opentelemetry-core/package.json
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/platform/browser/environment.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/index.ts
  packages/opentelemetry-core/src/platform/node/environment.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-core/test/browser/environment.test.ts
  packages/opentelemetry-core/test/browser/index-webpack.ts
  packages/opentelemetry-core/test/common/baggage/W3CBaggagePropagator.test.ts
  packages/opentelemetry-core/test/common/internal/exporter.test.ts
  packages/opentelemetry-core/test/common/internal/validators.test.ts
  packages/opentelemetry-core/test/common/propagation/composite.test.ts
  packages/opentelemetry-core/test/common/trace/W3CTraceContextPropagator.test.ts
  packages/opentelemetry-core/test/common/trace/tracestate.test.ts
  packages/opentelemetry-core/test/common/utils/callback.test.ts
  packages/opentelemetry-core/test/common/utils/environment.test.ts
  packages/opentelemetry-core/test/common/utils/merge.test.ts
  packages/opentelemetry-core/test/common/utils/promise.test.ts
  packages/opentelemetry-core/test/common/utils/url.test.ts
  packages/opentelemetry-core/test/node/environment.test.ts
Labels: pkg:core, target:next-major-release

#5451 chore: add 'lint:semconv-deps'
  package.json
  scripts/lint-semconv-deps.mjs
Labels: Skip Changelog

#5457 docs(opentelemetry-readme): Updated circleci badge with github action badge
  README.md
Labels: document, Skip Changelog

#5420 Remove duplicate browser detector
  CHANGELOG.md
  packages/opentelemetry-resources/src/detectors/BrowserDetector.ts
  packages/opentelemetry-resources/src/detectors/index.ts
  packages/opentelemetry-resources/src/index.ts
  packages/opentelemetry-resources/test/detectors/browser/BrowserDetector.test.ts
  packages/opentelemetry-resources/test/detectors/node/BrowserDetector.test.ts
Labels: target:next-major-release

#5464 refactor(exporter-jaeger): migrate away from getEnv()
  CHANGELOG.md
  packages/opentelemetry-exporter-jaeger/src/jaeger.ts
Labels: target:next-major-release

#5468 chore: fix repo parameter
  .github/workflows/survey-on-merged-pr.yml
Labels: Skip Changelog

#5466 feat(resources)!: do not read environment variables from window
  CHANGELOG.md
  packages/opentelemetry-resources/src/detectors/EnvDetector.ts
  packages/opentelemetry-resources/test/detectors/browser/EnvDetector.test.ts
Labels: target:next-major-release

#5371 refactor(context-zone-peer-dep): fix eslint warnings
  packages/opentelemetry-context-zone-peer-dep/src/util.ts
Labels: Skip Changelog

#5475 feat: migrate sdk-node away from getEnv(), introduce diagLogLevelFromString() util
  CHANGELOG.md
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/opentelemetry-sdk-node/src/utils.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/configuration.ts
  packages/opentelemetry-core/test/common/utils/configuration.test.ts
Labels: pkg:sdk-node, pkg:core, target:next-major-release

#5472 feat(sdk-logs)!: do not read environment variables from window
  experimental/CHANGELOG.md
  experimental/packages/sdk-logs/karma.conf.js
  experimental/packages/sdk-logs/src/config.ts
  experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts
  experimental/packages/sdk-logs/test/browser/index-webpack.ts
  experimental/packages/sdk-logs/test/browser/index-webpack.worker.ts
  experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts
  experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts
  experimental/packages/sdk-logs/test/node/LoggerProvider.test.ts
Labels: target:next-major-release

#5469 refactor(instrumentation-http): migrate away from getEnv()
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
Labels: target:next-major-release

#5465 feat(exporter-zipkin)!: do not read environment variables from window
  CHANGELOG.md
  packages/opentelemetry-exporter-zipkin/src/zipkin.ts
Labels: target:next-major-release

#5473 feat(exporter-metrics-otlp-http)!: do not read environment variables from window
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
Labels: target:next-major-release

#5455 feat(sdk-trace-base)!: do not read environment variables from window
  CHANGELOG.md
  packages/opentelemetry-sdk-trace-base/karma.conf.js
  packages/opentelemetry-sdk-trace-base/karma.worker.js
  packages/opentelemetry-sdk-trace-base/src/config.ts
  packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts
  packages/opentelemetry-sdk-trace-base/src/utility.ts
  packages/opentelemetry-sdk-trace-base/test/browser/index-webpack.ts
  packages/opentelemetry-sdk-trace-base/test/browser/index-webpack.worker.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/BatchSpanProcessorBase.test.ts
  packages/opentelemetry-sdk-trace-base/test/node/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/node/Tracer.test.ts
  packages/opentelemetry-sdk-trace-base/test/node/config.test.ts
  packages/opentelemetry-sdk-trace-base/test/node/export/BatchSpanProcessorBase.test.ts
Labels: pkg:sdk-trace-base, target:next-major-release

#5481 feat(core): drop getEnv(), getEnvWithoutDefaults()
  CHANGELOG.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/platform/browser/environment.ts
  packages/opentelemetry-core/src/platform/browser/index.ts
  packages/opentelemetry-core/src/platform/index.ts
  packages/opentelemetry-core/src/platform/node/environment.ts
  packages/opentelemetry-core/src/platform/node/index.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/test/browser/environment.test.ts
  packages/opentelemetry-core/test/common/utils/environment.test.ts
Labels: pkg:core, target:next-major-release

#5485 docs(sdk-metrics): align documentation with current state
  doc/metrics.md
  examples/otlp-exporter-node/metrics.js
  packages/sdk-metrics/README.md
Labels: document, Skip Changelog

#5486 docs(resources): align documentation with current state
  .github/ISSUE_TEMPLATE/bug_report.yaml
  examples/basic-tracer-node/index.js
  examples/esm-http-ts/index.ts
  examples/grpc-js/tracer.js
  examples/http/tracer.js
  examples/https/tracer.js
  examples/opentelemetry-web/examples/fetch-proto/index.js
  examples/opentelemetry-web/examples/fetch/index.js
  examples/opentelemetry-web/examples/fetchXhr/index.js
  examples/opentelemetry-web/examples/fetchXhrB3/index.js
  examples/opentelemetry-web/examples/xml-http-request/index.js
  examples/opentelemetry-web/examples/zipkin/index.js
  examples/opentracing-shim/shim.js
  examples/otlp-exporter-node/metrics.js
  examples/otlp-exporter-node/tracing.js
  experimental/examples/opencensus-shim/setup.js
  experimental/packages/exporter-logs-otlp-proto/README.md
Labels: document, Skip Changelog

#5467 feat(resources): use functions over constants for default and empty resources
  CHANGELOG.md
  experimental/packages/opentelemetry-browser-detector/src/BrowserDetector.ts
  experimental/packages/opentelemetry-exporter-prometheus/test/util.ts
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
  experimental/packages/sampler-jaeger-remote/README.md
  experimental/packages/sdk-logs/src/LoggerProvider.ts
  experimental/packages/sdk-logs/test/common/LogRecord.test.ts
  experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts
  experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts
  experimental/packages/sdk-logs/test/common/export/SimpleLogRecordProcessor.test.ts
  experimental/packages/shim-opencensus/src/OpenCensusMetricProducer.ts
  experimental/packages/shim-opencensus/test/OpenCensusMetricProducer.test.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-resources/src/ResourceImpl.ts
  packages/opentelemetry-resources/src/detect-resources.ts
  packages/opentelemetry-resources/src/index.ts
  packages/opentelemetry-resources/test/Resource.test.ts
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/sdk-metrics/src/MeterProvider.ts
  packages/sdk-metrics/test/Instruments.test.ts
  packages/sdk-metrics/test/Meter.test.ts
  packages/sdk-metrics/test/MeterProvider.test.ts
  packages/sdk-metrics/test/export/ConsoleMetricExporter.test.ts
  packages/sdk-metrics/test/export/InMemoryMetricExporter.test.ts
  packages/sdk-metrics/test/export/MetricReader.test.ts
  packages/sdk-metrics/test/export/TestMetricProducer.ts
  packages/sdk-metrics/test/state/MeterSharedState.test.ts
  packages/sdk-metrics/test/state/MetricCollector.test.ts
  packages/sdk-metrics/test/util.ts
Labels: target:next-major-release

#5484 deps: clean up dependencies
  experimental/packages/sampler-jaeger-remote/package.json
  package-lock.json
  packages/opentelemetry-resources/package.json
Labels: dependencies

#5456 feat!: set compilation target to `es2022` for all packages but api and semantic-conventions
  CHANGELOG.md
  README.md
  api/package.json
  api/src/platform/browser/globalThis.ts
  api/test/common/baggage/Baggage.test.ts
  api/test/tree-shaking/tree-shaking.test.ts
  api/tsconfig.esm.json
  api/tsconfig.esnext.json
  api/tsconfig.json
  experimental/packages/api-events/package.json
  experimental/packages/api-events/src/platform/browser/globalThis.ts
  experimental/packages/api-events/tsconfig.esm.json
  experimental/packages/api-events/tsconfig.esnext.json
  experimental/packages/api-events/tsconfig.json
  experimental/packages/api-logs/package.json
  experimental/packages/api-logs/src/platform/browser/globalThis.ts
  experimental/packages/api-logs/tsconfig.esm.json
  experimental/packages/api-logs/tsconfig.esnext.json
  experimental/packages/api-logs/tsconfig.json
  experimental/packages/opentelemetry-instrumentation-http/src/http.ts
  package-lock.json
  semantic-conventions/package.json
  semantic-conventions/tsconfig.esm.json
  semantic-conventions/tsconfig.esnext.json
  semantic-conventions/tsconfig.json
  tsconfig.base.es5.json
  tsconfig.base.esm.json
  tsconfig.base.esnext.json
  tsconfig.base.json
Labels: target:next-major-release

#5496 ci: add `canary` dist-tag when publishing from main
  .github/workflows/publish-to-npm.yml
  package.json
Labels: Skip Changelog, target:next-major-release

#5498 chore: prepare 2.0.0-dev.0/0.200.0-dev.0 release
  examples/esm-http-ts/package.json
  examples/http/package.json
  examples/https/package.json
  examples/opentelemetry-web/package.json
  examples/otlp-exporter-node/package.json
  experimental/backwards-compatibility/node14/package.json
  experimental/backwards-compatibility/node16/package.json
  experimental/examples/events/package.json
  experimental/examples/logs/package.json
  experimental/examples/opencensus-shim/package.json
  experimental/examples/prometheus/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sampler-jaeger-remote/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  experimental/packages/web-common/package.json
  integration-tests/api/package.json
  integration-tests/propagation-validation-server/package.json
  package-lock.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: Skip Changelog, target:next-major-release

#5494 fix(sdk-trace-base)!: use parent-base-always-on on incorrect input
  CHANGELOG.md
  packages/opentelemetry-sdk-trace-base/src/config.ts
Labels: bug, priority:p2, target:next-major-release

#5504 feat(core)!: drop unused constants
  CHANGELOG.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-sdk-trace-base/src/utility.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Labels: pkg:core, target:next-major-release
