Repository open-telemetry/opentelemetry-js, pull requests merged in 2025-01, with the labels that each got.

#5268 [instrumentation-fetch] refactor fetch() tests for clarity, type safety and realism
  experimental/packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Labels: Skip Changelog

#5289 chore(deps): remove webpack-merge where it is not needed
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/web-common/package.json
  package-lock.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/sdk-metrics/package.json
Labels: dependencies

#5292 chore(deps): update dependency webpack-dev-server to v5
  examples/opentelemetry-web/package.json
  package-lock.json
  selenium-tests/package.json
Labels: Skip Changelog

#5308 feat(core)!: remove deprecated InstrumentationLibrary
  CHANGELOG.md
  experimental/packages/otlp-transformer/src/trace/internal.ts
  experimental/packages/otlp-transformer/test/trace.test.ts
  packages/opentelemetry-core/src/common/types.ts
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-exporter-jaeger/src/transform.ts
  packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
  packages/opentelemetry-exporter-jaeger/test/transform.test.ts
  packages/opentelemetry-exporter-zipkin/test/helper.ts
  packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
  packages/opentelemetry-sdk-trace-base/src/Span.ts
  packages/opentelemetry-sdk-trace-base/src/Tracer.ts
  packages/opentelemetry-sdk-trace-base/src/export/ConsoleSpanExporter.ts
  packages/opentelemetry-sdk-trace-base/src/export/ReadableSpan.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/ConsoleSpanExporter.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/SimpleSpanProcessor.test.ts
Labels: target:next-major-release

#5331 fix(exporter-metrics-otlp-http): browser OTLPMetricExporter was not passing config to OTLPMetricExporterBase super class
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/browser/OTLPMetricExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/OTLPMetricExporter.test.ts
Labels: bug, priority:p2, pkg:exporter-metrics-otlp-http

#5328 test(instrumentation-http): remove tests for deprecated request package
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts
  experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-package.test.ts
  package-lock.json
Labels: Skip Changelog, pkg:instrumentation-http

#5316 feat(core)!: remove deprecated samplers
  CHANGELOG.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/trace/sampler/AlwaysOffSampler.ts
  packages/opentelemetry-core/src/trace/sampler/AlwaysOnSampler.ts
  packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts
  packages/opentelemetry-core/src/trace/sampler/TraceIdRatioBasedSampler.ts
  packages/opentelemetry-core/test/trace/AlwaysOffSampler.test.ts
  packages/opentelemetry-core/test/trace/AlwaysOnSampler.test.ts
  packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts
  packages/opentelemetry-core/test/trace/TraceIdRatioBasedSampler.test.ts
  packages/opentelemetry-core/test/trace/fixtures/test-package/foo/bar/internal.d.ts
  packages/opentelemetry-core/test/trace/fixtures/test-package/foo/bar/internal.js
  packages/opentelemetry-core/test/trace/fixtures/test-package/index.js
  packages/opentelemetry-core/test/trace/fixtures/test-package/package.json
Labels: pkg:core, target:next-major-release

#5338 [backport/v1.x] ci: make changelog workflow check v1.x
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: backport

#5340 [backport/v1.x] fix(sdk-metrics): don't export from PeriodicExportingMetricReader with no metrics (#5288)
  CHANGELOG.md
  packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts
  packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
Labels: bug, priority:p3, backport

#5337 [backport/v1.x] fix(exporter-metrics-otlp-http): browser OTLPMetricExporter was not passing config to OTLPMetricExporterBase super class [#5331]
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/browser/OTLPMetricExporter.ts
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/OTLPMetricExporter.test.ts
Labels: bug, priority:p2, backport

#5341 [backport/v1.x] ci: make v1.x release PR workflow checkout correct branch
  .github/workflows/create-or-update-release-pr.yml
Labels: internal, Skip Changelog

#5123 feat(instrumentation): re-export initialize from import-in-the-middle
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-instrumentation/hook.mjs
Labels: stale

#5239 feat(sdk-trace)!: remove ability to have BasicTracerProvider instantiate exporters
  CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
Labels: pkg:sdk-trace-base, pkg:sdk-trace-node, target:next-major-release

#5311 feat(sdk-metrics)!: extract IMetricReader interface and use it over abstract class
  CHANGELOG.md
  experimental/CHANGELOG.md
  experimental/packages/opentelemetry-sdk-node/src/sdk.ts
  experimental/packages/opentelemetry-sdk-node/src/types.ts
  packages/sdk-metrics/src/MeterProvider.ts
  packages/sdk-metrics/src/export/MetricProducer.ts
  packages/sdk-metrics/src/export/MetricReader.ts
  packages/sdk-metrics/src/index.ts
  packages/sdk-metrics/src/state/MetricCollector.ts
  packages/sdk-metrics/test/Instruments.test.ts
  packages/sdk-metrics/test/export/utils.ts
  packages/sdk-metrics/test/regression/cumulative-exponential-histogram.test.ts
  packages/sdk-metrics/test/regression/histogram-recording-nan.test.ts
  packages/sdk-metrics/test/regression/two-metric-readers-async-instrument.test.ts
  packages/sdk-metrics/test/state/MeterSharedState.test.ts
Labels: pkg:sdk-metrics, target:next-major-release

#5349 doc: migrate away from defunct `addMetricReader` in examples
  doc/metrics.md
  examples/opentelemetry-web/examples/metrics/index.js
  examples/otlp-exporter-node/metrics.js
  experimental/examples/opencensus-shim/setup.js
  experimental/examples/prometheus/index.js
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/README.md
  experimental/packages/opentelemetry-exporter-prometheus/README.md
  experimental/packages/shim-opencensus/README.md
  experimental/packages/shim-opencensus/src/OpenCensusMetricProducer.ts
Labels: Skip Changelog

#5386 refactor(sdk-metrics): fix eslint warning
  packages/sdk-metrics/src/state/DeltaMetricProcessor.ts
Labels: Skip Changelog

#5389 refactor(instrumentation): fix eslint warnings
  experimental/packages/opentelemetry-instrumentation/src/types.ts
Labels: Skip Changelog

#5388 refactor(sdk-trace-web): fix eslint warning
  packages/opentelemetry-sdk-trace-web/src/utils.ts
Labels: Skip Changelog

#5387 refactor(sdk-trace-node): fix eslint warning
  packages/opentelemetry-sdk-trace-node/test/registration.test.ts
Labels: Skip Changelog

#5384 refactor(browser-detector): fix eslint warning
  experimental/packages/opentelemetry-browser-detector/src/BrowserDetector.ts
Labels: Skip Changelog

#5382 refactor(core): fix eslint warning
  packages/opentelemetry-core/src/utils/lodash.merge.ts
Labels: Skip Changelog

#5282 [instrumentation-fetch] Use `msw` for fetch instrumentation tests
  experimental/packages/opentelemetry-instrumentation-fetch/karma.conf.js
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
  experimental/packages/opentelemetry-instrumentation-fetch/test/mockServiceWorker.js
  package-lock.json
Labels: Skip Changelog

#5396 refactor(exporter-metrics-otlp-http): fix eslint warning
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
Labels: Skip Changelog

#5401 refactor(instrumentation-fetch): fix eslint warnings
  experimental/packages/opentelemetry-instrumentation-fetch/src/utils.ts
Labels: Skip Changelog

#5407 chore(semantic-conventions): restore min-supported node to >=14
  semantic-conventions/package.json
Labels: Skip Changelog

#5406 feat(core)!: remove TracesSamplerValues from exports
  CHANGELOG.md
  packages/opentelemetry-core/src/index.ts
  packages/opentelemetry-core/src/utils/environment.ts
  packages/opentelemetry-core/src/utils/sampling.ts
  packages/opentelemetry-core/test/utils/environment.test.ts
  packages/opentelemetry-sdk-trace-base/src/config.ts
Labels: pkg:core, pkg:sdk-trace-base, target:next-major-release

#5397 chore!: bump min-supported node to ^18.19.0 || >=20.6.0
  .github/workflows/unit-test.yml
  CHANGELOG.md
  examples/basic-tracer-node/package.json
  examples/esm-http-ts/package.json
  examples/grpc-js/package.json
  examples/http/package.json
  examples/https/package.json
  examples/opentelemetry-web/package.json
  examples/opentracing-shim/package.json
  examples/otlp-exporter-node/package.json
  experimental/CHANGELOG.md
  experimental/backwards-compatibility/node14/package.json
  experimental/backwards-compatibility/node16/package.json
  experimental/examples/opencensus-shim/package.json
  experimental/packages/api-events/package.json
  experimental/packages/api-logs/package.json
  experimental/packages/exporter-logs-otlp-grpc/package.json
  experimental/packages/exporter-logs-otlp-http/package.json
  experimental/packages/exporter-logs-otlp-proto/package.json
  experimental/packages/exporter-trace-otlp-grpc/package.json
  experimental/packages/exporter-trace-otlp-http/package.json
  experimental/packages/exporter-trace-otlp-proto/package.json
  experimental/packages/opentelemetry-browser-detector/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json
  experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json
  experimental/packages/opentelemetry-exporter-prometheus/package.json
  experimental/packages/opentelemetry-instrumentation-fetch/package.json
  experimental/packages/opentelemetry-instrumentation-grpc/package.json
  experimental/packages/opentelemetry-instrumentation-http/package.json
  experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json
  experimental/packages/opentelemetry-instrumentation/package.json
  experimental/packages/opentelemetry-sdk-node/package.json
  experimental/packages/otlp-exporter-base/package.json
  experimental/packages/otlp-grpc-exporter-base/package.json
  experimental/packages/otlp-transformer/package.json
  experimental/packages/sampler-jaeger-remote/package.json
  experimental/packages/sdk-events/package.json
  experimental/packages/sdk-logs/package.json
  experimental/packages/shim-opencensus/package.json
  experimental/packages/web-common/package.json
  integration-tests/api/package.json
  integration-tests/propagation-validation-server/package.json
  package-lock.json
  packages/opentelemetry-context-async-hooks/package.json
  packages/opentelemetry-context-zone-peer-dep/package.json
  packages/opentelemetry-context-zone/package.json
  packages/opentelemetry-core/package.json
  packages/opentelemetry-exporter-jaeger/package.json
  packages/opentelemetry-exporter-zipkin/package.json
  packages/opentelemetry-propagator-b3/package.json
  packages/opentelemetry-propagator-jaeger/package.json
  packages/opentelemetry-resources/package.json
  packages/opentelemetry-sdk-trace-base/package.json
  packages/opentelemetry-sdk-trace-node/package.json
  packages/opentelemetry-sdk-trace-web/package.json
  packages/opentelemetry-shim-opentracing/package.json
  packages/sdk-metrics/package.json
  packages/template/package.json
Labels: target:next-major-release

#5405 feat(sdk-trace-*):! drop unintentional/unnecessary exports
  CHANGELOG.md
  experimental/packages/shim-opencensus/test/ShimTracer.test.ts
  packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
  packages/opentelemetry-sdk-trace-base/src/index.ts
  packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/SimpleSpanProcessor.test.ts
  packages/opentelemetry-sdk-trace-base/test/common/export/TestTracingSpanExporter.ts
  packages/opentelemetry-sdk-trace-node/src/index.ts
  packages/opentelemetry-sdk-trace-web/src/index.ts
  packages/opentelemetry-sdk-trace-web/test/NodeGlobalsFoolProofing.test.ts
  packages/opentelemetry-sdk-trace-web/test/WebTracerProvider.test.ts
Labels: pkg:sdk-trace-base, pkg:sdk-trace-node, pkg:sdk-trace-web, target:next-major-release
